// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/browser.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrowserServiceName is the fully-qualified name of the BrowserService service.
	BrowserServiceName = "runtime.v1.BrowserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrowserServiceExecuteBrowserActionProcedure is the fully-qualified name of the BrowserService's
	// ExecuteBrowserAction RPC.
	BrowserServiceExecuteBrowserActionProcedure = "/runtime.v1.BrowserService/ExecuteBrowserAction"
	// BrowserServiceGetBrowserStatusProcedure is the fully-qualified name of the BrowserService's
	// GetBrowserStatus RPC.
	BrowserServiceGetBrowserStatusProcedure = "/runtime.v1.BrowserService/GetBrowserStatus"
	// BrowserServiceClearBrowserDataProcedure is the fully-qualified name of the BrowserService's
	// ClearBrowserData RPC.
	BrowserServiceClearBrowserDataProcedure = "/runtime.v1.BrowserService/ClearBrowserData"
	// BrowserServiceNotifyBrowserConfigUpdateProcedure is the fully-qualified name of the
	// BrowserService's NotifyBrowserConfigUpdate RPC.
	BrowserServiceNotifyBrowserConfigUpdateProcedure = "/runtime.v1.BrowserService/NotifyBrowserConfigUpdate"
	// BrowserServiceRenewPresignedURLsProcedure is the fully-qualified name of the BrowserService's
	// RenewPresignedURLs RPC.
	BrowserServiceRenewPresignedURLsProcedure = "/runtime.v1.BrowserService/RenewPresignedURLs"
)

// BrowserServiceClient is a client for the runtime.v1.BrowserService service.
type BrowserServiceClient interface {
	ExecuteBrowserAction(context.Context, *connect.Request[v1.ExecuteBrowserActionRequest]) (*connect.Response[v1.ExecuteBrowserActionResponse], error)
	GetBrowserStatus(context.Context, *connect.Request[v1.GetBrowserStatusRequest]) (*connect.Response[v1.GetBrowserStatusResponse], error)
	ClearBrowserData(context.Context, *connect.Request[v1.ClearBrowserDataRequest]) (*connect.Response[v1.ClearBrowserDataResponse], error)
	NotifyBrowserConfigUpdate(context.Context, *connect.Request[v1.NotifyBrowserConfigUpdateRequest]) (*connect.Response[v1.NotifyBrowserConfigUpdateResponse], error)
	RenewPresignedURLs(context.Context, *connect.Request[v1.RenewPresignedURLsRequest]) (*connect.Response[v1.RenewPresignedURLsResponse], error)
}

// NewBrowserServiceClient constructs a client for the runtime.v1.BrowserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrowserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrowserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	browserServiceMethods := v1.File_runtime_v1_browser_proto.Services().ByName("BrowserService").Methods()
	return &browserServiceClient{
		executeBrowserAction: connect.NewClient[v1.ExecuteBrowserActionRequest, v1.ExecuteBrowserActionResponse](
			httpClient,
			baseURL+BrowserServiceExecuteBrowserActionProcedure,
			connect.WithSchema(browserServiceMethods.ByName("ExecuteBrowserAction")),
			connect.WithClientOptions(opts...),
		),
		getBrowserStatus: connect.NewClient[v1.GetBrowserStatusRequest, v1.GetBrowserStatusResponse](
			httpClient,
			baseURL+BrowserServiceGetBrowserStatusProcedure,
			connect.WithSchema(browserServiceMethods.ByName("GetBrowserStatus")),
			connect.WithClientOptions(opts...),
		),
		clearBrowserData: connect.NewClient[v1.ClearBrowserDataRequest, v1.ClearBrowserDataResponse](
			httpClient,
			baseURL+BrowserServiceClearBrowserDataProcedure,
			connect.WithSchema(browserServiceMethods.ByName("ClearBrowserData")),
			connect.WithClientOptions(opts...),
		),
		notifyBrowserConfigUpdate: connect.NewClient[v1.NotifyBrowserConfigUpdateRequest, v1.NotifyBrowserConfigUpdateResponse](
			httpClient,
			baseURL+BrowserServiceNotifyBrowserConfigUpdateProcedure,
			connect.WithSchema(browserServiceMethods.ByName("NotifyBrowserConfigUpdate")),
			connect.WithClientOptions(opts...),
		),
		renewPresignedURLs: connect.NewClient[v1.RenewPresignedURLsRequest, v1.RenewPresignedURLsResponse](
			httpClient,
			baseURL+BrowserServiceRenewPresignedURLsProcedure,
			connect.WithSchema(browserServiceMethods.ByName("RenewPresignedURLs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// browserServiceClient implements BrowserServiceClient.
type browserServiceClient struct {
	executeBrowserAction      *connect.Client[v1.ExecuteBrowserActionRequest, v1.ExecuteBrowserActionResponse]
	getBrowserStatus          *connect.Client[v1.GetBrowserStatusRequest, v1.GetBrowserStatusResponse]
	clearBrowserData          *connect.Client[v1.ClearBrowserDataRequest, v1.ClearBrowserDataResponse]
	notifyBrowserConfigUpdate *connect.Client[v1.NotifyBrowserConfigUpdateRequest, v1.NotifyBrowserConfigUpdateResponse]
	renewPresignedURLs        *connect.Client[v1.RenewPresignedURLsRequest, v1.RenewPresignedURLsResponse]
}

// ExecuteBrowserAction calls runtime.v1.BrowserService.ExecuteBrowserAction.
func (c *browserServiceClient) ExecuteBrowserAction(ctx context.Context, req *connect.Request[v1.ExecuteBrowserActionRequest]) (*connect.Response[v1.ExecuteBrowserActionResponse], error) {
	return c.executeBrowserAction.CallUnary(ctx, req)
}

// GetBrowserStatus calls runtime.v1.BrowserService.GetBrowserStatus.
func (c *browserServiceClient) GetBrowserStatus(ctx context.Context, req *connect.Request[v1.GetBrowserStatusRequest]) (*connect.Response[v1.GetBrowserStatusResponse], error) {
	return c.getBrowserStatus.CallUnary(ctx, req)
}

// ClearBrowserData calls runtime.v1.BrowserService.ClearBrowserData.
func (c *browserServiceClient) ClearBrowserData(ctx context.Context, req *connect.Request[v1.ClearBrowserDataRequest]) (*connect.Response[v1.ClearBrowserDataResponse], error) {
	return c.clearBrowserData.CallUnary(ctx, req)
}

// NotifyBrowserConfigUpdate calls runtime.v1.BrowserService.NotifyBrowserConfigUpdate.
func (c *browserServiceClient) NotifyBrowserConfigUpdate(ctx context.Context, req *connect.Request[v1.NotifyBrowserConfigUpdateRequest]) (*connect.Response[v1.NotifyBrowserConfigUpdateResponse], error) {
	return c.notifyBrowserConfigUpdate.CallUnary(ctx, req)
}

// RenewPresignedURLs calls runtime.v1.BrowserService.RenewPresignedURLs.
func (c *browserServiceClient) RenewPresignedURLs(ctx context.Context, req *connect.Request[v1.RenewPresignedURLsRequest]) (*connect.Response[v1.RenewPresignedURLsResponse], error) {
	return c.renewPresignedURLs.CallUnary(ctx, req)
}

// BrowserServiceHandler is an implementation of the runtime.v1.BrowserService service.
type BrowserServiceHandler interface {
	ExecuteBrowserAction(context.Context, *connect.Request[v1.ExecuteBrowserActionRequest]) (*connect.Response[v1.ExecuteBrowserActionResponse], error)
	GetBrowserStatus(context.Context, *connect.Request[v1.GetBrowserStatusRequest]) (*connect.Response[v1.GetBrowserStatusResponse], error)
	ClearBrowserData(context.Context, *connect.Request[v1.ClearBrowserDataRequest]) (*connect.Response[v1.ClearBrowserDataResponse], error)
	NotifyBrowserConfigUpdate(context.Context, *connect.Request[v1.NotifyBrowserConfigUpdateRequest]) (*connect.Response[v1.NotifyBrowserConfigUpdateResponse], error)
	RenewPresignedURLs(context.Context, *connect.Request[v1.RenewPresignedURLsRequest]) (*connect.Response[v1.RenewPresignedURLsResponse], error)
}

// NewBrowserServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrowserServiceHandler(svc BrowserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	browserServiceMethods := v1.File_runtime_v1_browser_proto.Services().ByName("BrowserService").Methods()
	browserServiceExecuteBrowserActionHandler := connect.NewUnaryHandler(
		BrowserServiceExecuteBrowserActionProcedure,
		svc.ExecuteBrowserAction,
		connect.WithSchema(browserServiceMethods.ByName("ExecuteBrowserAction")),
		connect.WithHandlerOptions(opts...),
	)
	browserServiceGetBrowserStatusHandler := connect.NewUnaryHandler(
		BrowserServiceGetBrowserStatusProcedure,
		svc.GetBrowserStatus,
		connect.WithSchema(browserServiceMethods.ByName("GetBrowserStatus")),
		connect.WithHandlerOptions(opts...),
	)
	browserServiceClearBrowserDataHandler := connect.NewUnaryHandler(
		BrowserServiceClearBrowserDataProcedure,
		svc.ClearBrowserData,
		connect.WithSchema(browserServiceMethods.ByName("ClearBrowserData")),
		connect.WithHandlerOptions(opts...),
	)
	browserServiceNotifyBrowserConfigUpdateHandler := connect.NewUnaryHandler(
		BrowserServiceNotifyBrowserConfigUpdateProcedure,
		svc.NotifyBrowserConfigUpdate,
		connect.WithSchema(browserServiceMethods.ByName("NotifyBrowserConfigUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	browserServiceRenewPresignedURLsHandler := connect.NewUnaryHandler(
		BrowserServiceRenewPresignedURLsProcedure,
		svc.RenewPresignedURLs,
		connect.WithSchema(browserServiceMethods.ByName("RenewPresignedURLs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.BrowserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrowserServiceExecuteBrowserActionProcedure:
			browserServiceExecuteBrowserActionHandler.ServeHTTP(w, r)
		case BrowserServiceGetBrowserStatusProcedure:
			browserServiceGetBrowserStatusHandler.ServeHTTP(w, r)
		case BrowserServiceClearBrowserDataProcedure:
			browserServiceClearBrowserDataHandler.ServeHTTP(w, r)
		case BrowserServiceNotifyBrowserConfigUpdateProcedure:
			browserServiceNotifyBrowserConfigUpdateHandler.ServeHTTP(w, r)
		case BrowserServiceRenewPresignedURLsProcedure:
			browserServiceRenewPresignedURLsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrowserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrowserServiceHandler struct{}

func (UnimplementedBrowserServiceHandler) ExecuteBrowserAction(context.Context, *connect.Request[v1.ExecuteBrowserActionRequest]) (*connect.Response[v1.ExecuteBrowserActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.BrowserService.ExecuteBrowserAction is not implemented"))
}

func (UnimplementedBrowserServiceHandler) GetBrowserStatus(context.Context, *connect.Request[v1.GetBrowserStatusRequest]) (*connect.Response[v1.GetBrowserStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.BrowserService.GetBrowserStatus is not implemented"))
}

func (UnimplementedBrowserServiceHandler) ClearBrowserData(context.Context, *connect.Request[v1.ClearBrowserDataRequest]) (*connect.Response[v1.ClearBrowserDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.BrowserService.ClearBrowserData is not implemented"))
}

func (UnimplementedBrowserServiceHandler) NotifyBrowserConfigUpdate(context.Context, *connect.Request[v1.NotifyBrowserConfigUpdateRequest]) (*connect.Response[v1.NotifyBrowserConfigUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.BrowserService.NotifyBrowserConfigUpdate is not implemented"))
}

func (UnimplementedBrowserServiceHandler) RenewPresignedURLs(context.Context, *connect.Request[v1.RenewPresignedURLsRequest]) (*connect.Response[v1.RenewPresignedURLsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.BrowserService.RenewPresignedURLs is not implemented"))
}
