// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/config.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "runtime.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceMountProcedure is the fully-qualified name of the ConfigService's Mount RPC.
	ConfigServiceMountProcedure = "/runtime.v1.ConfigService/Mount"
	// ConfigServiceSetEnvProcedure is the fully-qualified name of the ConfigService's SetEnv RPC.
	ConfigServiceSetEnvProcedure = "/runtime.v1.ConfigService/SetEnv"
	// ConfigServiceGetGitHubAuthStatusProcedure is the fully-qualified name of the ConfigService's
	// GetGitHubAuthStatus RPC.
	ConfigServiceGetGitHubAuthStatusProcedure = "/runtime.v1.ConfigService/GetGitHubAuthStatus"
	// ConfigServiceNekoPreAuthProcedure is the fully-qualified name of the ConfigService's NekoPreAuth
	// RPC.
	ConfigServiceNekoPreAuthProcedure = "/runtime.v1.ConfigService/NekoPreAuth"
	// ConfigServiceVNCPreAuthProcedure is the fully-qualified name of the ConfigService's VNCPreAuth
	// RPC.
	ConfigServiceVNCPreAuthProcedure = "/runtime.v1.ConfigService/VNCPreAuth"
	// ConfigServiceRefreshTurnTokenProcedure is the fully-qualified name of the ConfigService's
	// RefreshTurnToken RPC.
	ConfigServiceRefreshTurnTokenProcedure = "/runtime.v1.ConfigService/RefreshTurnToken"
)

// ConfigServiceClient is a client for the runtime.v1.ConfigService service.
type ConfigServiceClient interface {
	Mount(context.Context, *connect.Request[v1.MountRequest]) (*connect.Response[v1.MountResponse], error)
	SetEnv(context.Context, *connect.Request[v1.SetEnvRequest]) (*connect.Response[v1.SetEnvResponse], error)
	GetGitHubAuthStatus(context.Context, *connect.Request[v1.GetGitHubAuthStatusRequest]) (*connect.Response[v1.GetGitHubAuthStatusResponse], error)
	NekoPreAuth(context.Context, *connect.Request[v1.NekoPreAuthRequest]) (*connect.Response[v1.NekoPreAuthResponse], error)
	VNCPreAuth(context.Context, *connect.Request[v1.VNCPreAuthRequest]) (*connect.Response[v1.VNCPreAuthResponse], error)
	RefreshTurnToken(context.Context, *connect.Request[v1.RefreshTurnTokenRequest]) (*connect.Response[v1.RefreshTurnTokenResponse], error)
}

// NewConfigServiceClient constructs a client for the runtime.v1.ConfigService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1.File_runtime_v1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		mount: connect.NewClient[v1.MountRequest, v1.MountResponse](
			httpClient,
			baseURL+ConfigServiceMountProcedure,
			connect.WithSchema(configServiceMethods.ByName("Mount")),
			connect.WithClientOptions(opts...),
		),
		setEnv: connect.NewClient[v1.SetEnvRequest, v1.SetEnvResponse](
			httpClient,
			baseURL+ConfigServiceSetEnvProcedure,
			connect.WithSchema(configServiceMethods.ByName("SetEnv")),
			connect.WithClientOptions(opts...),
		),
		getGitHubAuthStatus: connect.NewClient[v1.GetGitHubAuthStatusRequest, v1.GetGitHubAuthStatusResponse](
			httpClient,
			baseURL+ConfigServiceGetGitHubAuthStatusProcedure,
			connect.WithSchema(configServiceMethods.ByName("GetGitHubAuthStatus")),
			connect.WithClientOptions(opts...),
		),
		nekoPreAuth: connect.NewClient[v1.NekoPreAuthRequest, v1.NekoPreAuthResponse](
			httpClient,
			baseURL+ConfigServiceNekoPreAuthProcedure,
			connect.WithSchema(configServiceMethods.ByName("NekoPreAuth")),
			connect.WithClientOptions(opts...),
		),
		vNCPreAuth: connect.NewClient[v1.VNCPreAuthRequest, v1.VNCPreAuthResponse](
			httpClient,
			baseURL+ConfigServiceVNCPreAuthProcedure,
			connect.WithSchema(configServiceMethods.ByName("VNCPreAuth")),
			connect.WithClientOptions(opts...),
		),
		refreshTurnToken: connect.NewClient[v1.RefreshTurnTokenRequest, v1.RefreshTurnTokenResponse](
			httpClient,
			baseURL+ConfigServiceRefreshTurnTokenProcedure,
			connect.WithSchema(configServiceMethods.ByName("RefreshTurnToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	mount               *connect.Client[v1.MountRequest, v1.MountResponse]
	setEnv              *connect.Client[v1.SetEnvRequest, v1.SetEnvResponse]
	getGitHubAuthStatus *connect.Client[v1.GetGitHubAuthStatusRequest, v1.GetGitHubAuthStatusResponse]
	nekoPreAuth         *connect.Client[v1.NekoPreAuthRequest, v1.NekoPreAuthResponse]
	vNCPreAuth          *connect.Client[v1.VNCPreAuthRequest, v1.VNCPreAuthResponse]
	refreshTurnToken    *connect.Client[v1.RefreshTurnTokenRequest, v1.RefreshTurnTokenResponse]
}

// Mount calls runtime.v1.ConfigService.Mount.
func (c *configServiceClient) Mount(ctx context.Context, req *connect.Request[v1.MountRequest]) (*connect.Response[v1.MountResponse], error) {
	return c.mount.CallUnary(ctx, req)
}

// SetEnv calls runtime.v1.ConfigService.SetEnv.
func (c *configServiceClient) SetEnv(ctx context.Context, req *connect.Request[v1.SetEnvRequest]) (*connect.Response[v1.SetEnvResponse], error) {
	return c.setEnv.CallUnary(ctx, req)
}

// GetGitHubAuthStatus calls runtime.v1.ConfigService.GetGitHubAuthStatus.
func (c *configServiceClient) GetGitHubAuthStatus(ctx context.Context, req *connect.Request[v1.GetGitHubAuthStatusRequest]) (*connect.Response[v1.GetGitHubAuthStatusResponse], error) {
	return c.getGitHubAuthStatus.CallUnary(ctx, req)
}

// NekoPreAuth calls runtime.v1.ConfigService.NekoPreAuth.
func (c *configServiceClient) NekoPreAuth(ctx context.Context, req *connect.Request[v1.NekoPreAuthRequest]) (*connect.Response[v1.NekoPreAuthResponse], error) {
	return c.nekoPreAuth.CallUnary(ctx, req)
}

// VNCPreAuth calls runtime.v1.ConfigService.VNCPreAuth.
func (c *configServiceClient) VNCPreAuth(ctx context.Context, req *connect.Request[v1.VNCPreAuthRequest]) (*connect.Response[v1.VNCPreAuthResponse], error) {
	return c.vNCPreAuth.CallUnary(ctx, req)
}

// RefreshTurnToken calls runtime.v1.ConfigService.RefreshTurnToken.
func (c *configServiceClient) RefreshTurnToken(ctx context.Context, req *connect.Request[v1.RefreshTurnTokenRequest]) (*connect.Response[v1.RefreshTurnTokenResponse], error) {
	return c.refreshTurnToken.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the runtime.v1.ConfigService service.
type ConfigServiceHandler interface {
	Mount(context.Context, *connect.Request[v1.MountRequest]) (*connect.Response[v1.MountResponse], error)
	SetEnv(context.Context, *connect.Request[v1.SetEnvRequest]) (*connect.Response[v1.SetEnvResponse], error)
	GetGitHubAuthStatus(context.Context, *connect.Request[v1.GetGitHubAuthStatusRequest]) (*connect.Response[v1.GetGitHubAuthStatusResponse], error)
	NekoPreAuth(context.Context, *connect.Request[v1.NekoPreAuthRequest]) (*connect.Response[v1.NekoPreAuthResponse], error)
	VNCPreAuth(context.Context, *connect.Request[v1.VNCPreAuthRequest]) (*connect.Response[v1.VNCPreAuthResponse], error)
	RefreshTurnToken(context.Context, *connect.Request[v1.RefreshTurnTokenRequest]) (*connect.Response[v1.RefreshTurnTokenResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1.File_runtime_v1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceMountHandler := connect.NewUnaryHandler(
		ConfigServiceMountProcedure,
		svc.Mount,
		connect.WithSchema(configServiceMethods.ByName("Mount")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceSetEnvHandler := connect.NewUnaryHandler(
		ConfigServiceSetEnvProcedure,
		svc.SetEnv,
		connect.WithSchema(configServiceMethods.ByName("SetEnv")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceGetGitHubAuthStatusHandler := connect.NewUnaryHandler(
		ConfigServiceGetGitHubAuthStatusProcedure,
		svc.GetGitHubAuthStatus,
		connect.WithSchema(configServiceMethods.ByName("GetGitHubAuthStatus")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceNekoPreAuthHandler := connect.NewUnaryHandler(
		ConfigServiceNekoPreAuthProcedure,
		svc.NekoPreAuth,
		connect.WithSchema(configServiceMethods.ByName("NekoPreAuth")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceVNCPreAuthHandler := connect.NewUnaryHandler(
		ConfigServiceVNCPreAuthProcedure,
		svc.VNCPreAuth,
		connect.WithSchema(configServiceMethods.ByName("VNCPreAuth")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceRefreshTurnTokenHandler := connect.NewUnaryHandler(
		ConfigServiceRefreshTurnTokenProcedure,
		svc.RefreshTurnToken,
		connect.WithSchema(configServiceMethods.ByName("RefreshTurnToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceMountProcedure:
			configServiceMountHandler.ServeHTTP(w, r)
		case ConfigServiceSetEnvProcedure:
			configServiceSetEnvHandler.ServeHTTP(w, r)
		case ConfigServiceGetGitHubAuthStatusProcedure:
			configServiceGetGitHubAuthStatusHandler.ServeHTTP(w, r)
		case ConfigServiceNekoPreAuthProcedure:
			configServiceNekoPreAuthHandler.ServeHTTP(w, r)
		case ConfigServiceVNCPreAuthProcedure:
			configServiceVNCPreAuthHandler.ServeHTTP(w, r)
		case ConfigServiceRefreshTurnTokenProcedure:
			configServiceRefreshTurnTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) Mount(context.Context, *connect.Request[v1.MountRequest]) (*connect.Response[v1.MountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.Mount is not implemented"))
}

func (UnimplementedConfigServiceHandler) SetEnv(context.Context, *connect.Request[v1.SetEnvRequest]) (*connect.Response[v1.SetEnvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.SetEnv is not implemented"))
}

func (UnimplementedConfigServiceHandler) GetGitHubAuthStatus(context.Context, *connect.Request[v1.GetGitHubAuthStatusRequest]) (*connect.Response[v1.GetGitHubAuthStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.GetGitHubAuthStatus is not implemented"))
}

func (UnimplementedConfigServiceHandler) NekoPreAuth(context.Context, *connect.Request[v1.NekoPreAuthRequest]) (*connect.Response[v1.NekoPreAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.NekoPreAuth is not implemented"))
}

func (UnimplementedConfigServiceHandler) VNCPreAuth(context.Context, *connect.Request[v1.VNCPreAuthRequest]) (*connect.Response[v1.VNCPreAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.VNCPreAuth is not implemented"))
}

func (UnimplementedConfigServiceHandler) RefreshTurnToken(context.Context, *connect.Request[v1.RefreshTurnTokenRequest]) (*connect.Response[v1.RefreshTurnTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ConfigService.RefreshTurnToken is not implemented"))
}
