// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/deploy.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeployServiceName is the fully-qualified name of the DeployService service.
	DeployServiceName = "runtime.v1.DeployService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeployServiceCreateWebdevProjectProcedure is the fully-qualified name of the DeployService's
	// CreateWebdevProject RPC.
	DeployServiceCreateWebdevProjectProcedure = "/runtime.v1.DeployService/CreateWebdevProject"
	// DeployServiceZipAndUploadProcedure is the fully-qualified name of the DeployService's
	// ZipAndUpload RPC.
	DeployServiceZipAndUploadProcedure = "/runtime.v1.DeployService/ZipAndUpload"
	// DeployServiceSwitchVersionProcedure is the fully-qualified name of the DeployService's
	// SwitchVersion RPC.
	DeployServiceSwitchVersionProcedure = "/runtime.v1.DeployService/SwitchVersion"
)

// DeployServiceClient is a client for the runtime.v1.DeployService service.
type DeployServiceClient interface {
	CreateWebdevProject(context.Context, *connect.Request[v1.CreateWebdevProjectRequest]) (*connect.Response[v1.CreateWebdevProjectResponse], error)
	ZipAndUpload(context.Context, *connect.Request[v1.ZipAndUploadRequest]) (*connect.Response[v1.ZipAndUploadResponse], error)
	SwitchVersion(context.Context, *connect.Request[v1.SwitchVersionRequest]) (*connect.Response[v1.SwitchVersionResponse], error)
}

// NewDeployServiceClient constructs a client for the runtime.v1.DeployService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeployServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeployServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deployServiceMethods := v1.File_runtime_v1_deploy_proto.Services().ByName("DeployService").Methods()
	return &deployServiceClient{
		createWebdevProject: connect.NewClient[v1.CreateWebdevProjectRequest, v1.CreateWebdevProjectResponse](
			httpClient,
			baseURL+DeployServiceCreateWebdevProjectProcedure,
			connect.WithSchema(deployServiceMethods.ByName("CreateWebdevProject")),
			connect.WithClientOptions(opts...),
		),
		zipAndUpload: connect.NewClient[v1.ZipAndUploadRequest, v1.ZipAndUploadResponse](
			httpClient,
			baseURL+DeployServiceZipAndUploadProcedure,
			connect.WithSchema(deployServiceMethods.ByName("ZipAndUpload")),
			connect.WithClientOptions(opts...),
		),
		switchVersion: connect.NewClient[v1.SwitchVersionRequest, v1.SwitchVersionResponse](
			httpClient,
			baseURL+DeployServiceSwitchVersionProcedure,
			connect.WithSchema(deployServiceMethods.ByName("SwitchVersion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deployServiceClient implements DeployServiceClient.
type deployServiceClient struct {
	createWebdevProject *connect.Client[v1.CreateWebdevProjectRequest, v1.CreateWebdevProjectResponse]
	zipAndUpload        *connect.Client[v1.ZipAndUploadRequest, v1.ZipAndUploadResponse]
	switchVersion       *connect.Client[v1.SwitchVersionRequest, v1.SwitchVersionResponse]
}

// CreateWebdevProject calls runtime.v1.DeployService.CreateWebdevProject.
func (c *deployServiceClient) CreateWebdevProject(ctx context.Context, req *connect.Request[v1.CreateWebdevProjectRequest]) (*connect.Response[v1.CreateWebdevProjectResponse], error) {
	return c.createWebdevProject.CallUnary(ctx, req)
}

// ZipAndUpload calls runtime.v1.DeployService.ZipAndUpload.
func (c *deployServiceClient) ZipAndUpload(ctx context.Context, req *connect.Request[v1.ZipAndUploadRequest]) (*connect.Response[v1.ZipAndUploadResponse], error) {
	return c.zipAndUpload.CallUnary(ctx, req)
}

// SwitchVersion calls runtime.v1.DeployService.SwitchVersion.
func (c *deployServiceClient) SwitchVersion(ctx context.Context, req *connect.Request[v1.SwitchVersionRequest]) (*connect.Response[v1.SwitchVersionResponse], error) {
	return c.switchVersion.CallUnary(ctx, req)
}

// DeployServiceHandler is an implementation of the runtime.v1.DeployService service.
type DeployServiceHandler interface {
	CreateWebdevProject(context.Context, *connect.Request[v1.CreateWebdevProjectRequest]) (*connect.Response[v1.CreateWebdevProjectResponse], error)
	ZipAndUpload(context.Context, *connect.Request[v1.ZipAndUploadRequest]) (*connect.Response[v1.ZipAndUploadResponse], error)
	SwitchVersion(context.Context, *connect.Request[v1.SwitchVersionRequest]) (*connect.Response[v1.SwitchVersionResponse], error)
}

// NewDeployServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeployServiceHandler(svc DeployServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deployServiceMethods := v1.File_runtime_v1_deploy_proto.Services().ByName("DeployService").Methods()
	deployServiceCreateWebdevProjectHandler := connect.NewUnaryHandler(
		DeployServiceCreateWebdevProjectProcedure,
		svc.CreateWebdevProject,
		connect.WithSchema(deployServiceMethods.ByName("CreateWebdevProject")),
		connect.WithHandlerOptions(opts...),
	)
	deployServiceZipAndUploadHandler := connect.NewUnaryHandler(
		DeployServiceZipAndUploadProcedure,
		svc.ZipAndUpload,
		connect.WithSchema(deployServiceMethods.ByName("ZipAndUpload")),
		connect.WithHandlerOptions(opts...),
	)
	deployServiceSwitchVersionHandler := connect.NewUnaryHandler(
		DeployServiceSwitchVersionProcedure,
		svc.SwitchVersion,
		connect.WithSchema(deployServiceMethods.ByName("SwitchVersion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.DeployService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeployServiceCreateWebdevProjectProcedure:
			deployServiceCreateWebdevProjectHandler.ServeHTTP(w, r)
		case DeployServiceZipAndUploadProcedure:
			deployServiceZipAndUploadHandler.ServeHTTP(w, r)
		case DeployServiceSwitchVersionProcedure:
			deployServiceSwitchVersionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeployServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeployServiceHandler struct{}

func (UnimplementedDeployServiceHandler) CreateWebdevProject(context.Context, *connect.Request[v1.CreateWebdevProjectRequest]) (*connect.Response[v1.CreateWebdevProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.DeployService.CreateWebdevProject is not implemented"))
}

func (UnimplementedDeployServiceHandler) ZipAndUpload(context.Context, *connect.Request[v1.ZipAndUploadRequest]) (*connect.Response[v1.ZipAndUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.DeployService.ZipAndUpload is not implemented"))
}

func (UnimplementedDeployServiceHandler) SwitchVersion(context.Context, *connect.Request[v1.SwitchVersionRequest]) (*connect.Response[v1.SwitchVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.DeployService.SwitchVersion is not implemented"))
}
