// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/email.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EmailServiceName is the fully-qualified name of the EmailService service.
	EmailServiceName = "runtime.v1.EmailService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EmailServiceDownloadGmailAttachmentsProcedure is the fully-qualified name of the EmailService's
	// DownloadGmailAttachments RPC.
	EmailServiceDownloadGmailAttachmentsProcedure = "/runtime.v1.EmailService/DownloadGmailAttachments"
	// EmailServiceDownloadOutlookAttachmentsProcedure is the fully-qualified name of the EmailService's
	// DownloadOutlookAttachments RPC.
	EmailServiceDownloadOutlookAttachmentsProcedure = "/runtime.v1.EmailService/DownloadOutlookAttachments"
	// EmailServiceSendOrSaveGmailDraftProcedure is the fully-qualified name of the EmailService's
	// SendOrSaveGmailDraft RPC.
	EmailServiceSendOrSaveGmailDraftProcedure = "/runtime.v1.EmailService/SendOrSaveGmailDraft"
	// EmailServiceSendOrSaveOutlookDraftProcedure is the fully-qualified name of the EmailService's
	// SendOrSaveOutlookDraft RPC.
	EmailServiceSendOrSaveOutlookDraftProcedure = "/runtime.v1.EmailService/SendOrSaveOutlookDraft"
)

// EmailServiceClient is a client for the runtime.v1.EmailService service.
type EmailServiceClient interface {
	DownloadGmailAttachments(context.Context, *connect.Request[v1.DownloadGmailAttachmentsRequest]) (*connect.Response[v1.DownloadGmailAttachmentsResponse], error)
	DownloadOutlookAttachments(context.Context, *connect.Request[v1.DownloadOutlookAttachmentsRequest]) (*connect.Response[v1.DownloadOutlookAttachmentsResponse], error)
	SendOrSaveGmailDraft(context.Context, *connect.Request[v1.SendOrSaveGmailDraftRequest]) (*connect.Response[v1.SendOrSaveGmailDraftResponse], error)
	SendOrSaveOutlookDraft(context.Context, *connect.Request[v1.SendOrSaveOutlookDraftRequest]) (*connect.Response[v1.SendOrSaveOutlookDraftResponse], error)
}

// NewEmailServiceClient constructs a client for the runtime.v1.EmailService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEmailServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EmailServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	emailServiceMethods := v1.File_runtime_v1_email_proto.Services().ByName("EmailService").Methods()
	return &emailServiceClient{
		downloadGmailAttachments: connect.NewClient[v1.DownloadGmailAttachmentsRequest, v1.DownloadGmailAttachmentsResponse](
			httpClient,
			baseURL+EmailServiceDownloadGmailAttachmentsProcedure,
			connect.WithSchema(emailServiceMethods.ByName("DownloadGmailAttachments")),
			connect.WithClientOptions(opts...),
		),
		downloadOutlookAttachments: connect.NewClient[v1.DownloadOutlookAttachmentsRequest, v1.DownloadOutlookAttachmentsResponse](
			httpClient,
			baseURL+EmailServiceDownloadOutlookAttachmentsProcedure,
			connect.WithSchema(emailServiceMethods.ByName("DownloadOutlookAttachments")),
			connect.WithClientOptions(opts...),
		),
		sendOrSaveGmailDraft: connect.NewClient[v1.SendOrSaveGmailDraftRequest, v1.SendOrSaveGmailDraftResponse](
			httpClient,
			baseURL+EmailServiceSendOrSaveGmailDraftProcedure,
			connect.WithSchema(emailServiceMethods.ByName("SendOrSaveGmailDraft")),
			connect.WithClientOptions(opts...),
		),
		sendOrSaveOutlookDraft: connect.NewClient[v1.SendOrSaveOutlookDraftRequest, v1.SendOrSaveOutlookDraftResponse](
			httpClient,
			baseURL+EmailServiceSendOrSaveOutlookDraftProcedure,
			connect.WithSchema(emailServiceMethods.ByName("SendOrSaveOutlookDraft")),
			connect.WithClientOptions(opts...),
		),
	}
}

// emailServiceClient implements EmailServiceClient.
type emailServiceClient struct {
	downloadGmailAttachments   *connect.Client[v1.DownloadGmailAttachmentsRequest, v1.DownloadGmailAttachmentsResponse]
	downloadOutlookAttachments *connect.Client[v1.DownloadOutlookAttachmentsRequest, v1.DownloadOutlookAttachmentsResponse]
	sendOrSaveGmailDraft       *connect.Client[v1.SendOrSaveGmailDraftRequest, v1.SendOrSaveGmailDraftResponse]
	sendOrSaveOutlookDraft     *connect.Client[v1.SendOrSaveOutlookDraftRequest, v1.SendOrSaveOutlookDraftResponse]
}

// DownloadGmailAttachments calls runtime.v1.EmailService.DownloadGmailAttachments.
func (c *emailServiceClient) DownloadGmailAttachments(ctx context.Context, req *connect.Request[v1.DownloadGmailAttachmentsRequest]) (*connect.Response[v1.DownloadGmailAttachmentsResponse], error) {
	return c.downloadGmailAttachments.CallUnary(ctx, req)
}

// DownloadOutlookAttachments calls runtime.v1.EmailService.DownloadOutlookAttachments.
func (c *emailServiceClient) DownloadOutlookAttachments(ctx context.Context, req *connect.Request[v1.DownloadOutlookAttachmentsRequest]) (*connect.Response[v1.DownloadOutlookAttachmentsResponse], error) {
	return c.downloadOutlookAttachments.CallUnary(ctx, req)
}

// SendOrSaveGmailDraft calls runtime.v1.EmailService.SendOrSaveGmailDraft.
func (c *emailServiceClient) SendOrSaveGmailDraft(ctx context.Context, req *connect.Request[v1.SendOrSaveGmailDraftRequest]) (*connect.Response[v1.SendOrSaveGmailDraftResponse], error) {
	return c.sendOrSaveGmailDraft.CallUnary(ctx, req)
}

// SendOrSaveOutlookDraft calls runtime.v1.EmailService.SendOrSaveOutlookDraft.
func (c *emailServiceClient) SendOrSaveOutlookDraft(ctx context.Context, req *connect.Request[v1.SendOrSaveOutlookDraftRequest]) (*connect.Response[v1.SendOrSaveOutlookDraftResponse], error) {
	return c.sendOrSaveOutlookDraft.CallUnary(ctx, req)
}

// EmailServiceHandler is an implementation of the runtime.v1.EmailService service.
type EmailServiceHandler interface {
	DownloadGmailAttachments(context.Context, *connect.Request[v1.DownloadGmailAttachmentsRequest]) (*connect.Response[v1.DownloadGmailAttachmentsResponse], error)
	DownloadOutlookAttachments(context.Context, *connect.Request[v1.DownloadOutlookAttachmentsRequest]) (*connect.Response[v1.DownloadOutlookAttachmentsResponse], error)
	SendOrSaveGmailDraft(context.Context, *connect.Request[v1.SendOrSaveGmailDraftRequest]) (*connect.Response[v1.SendOrSaveGmailDraftResponse], error)
	SendOrSaveOutlookDraft(context.Context, *connect.Request[v1.SendOrSaveOutlookDraftRequest]) (*connect.Response[v1.SendOrSaveOutlookDraftResponse], error)
}

// NewEmailServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEmailServiceHandler(svc EmailServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	emailServiceMethods := v1.File_runtime_v1_email_proto.Services().ByName("EmailService").Methods()
	emailServiceDownloadGmailAttachmentsHandler := connect.NewUnaryHandler(
		EmailServiceDownloadGmailAttachmentsProcedure,
		svc.DownloadGmailAttachments,
		connect.WithSchema(emailServiceMethods.ByName("DownloadGmailAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	emailServiceDownloadOutlookAttachmentsHandler := connect.NewUnaryHandler(
		EmailServiceDownloadOutlookAttachmentsProcedure,
		svc.DownloadOutlookAttachments,
		connect.WithSchema(emailServiceMethods.ByName("DownloadOutlookAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	emailServiceSendOrSaveGmailDraftHandler := connect.NewUnaryHandler(
		EmailServiceSendOrSaveGmailDraftProcedure,
		svc.SendOrSaveGmailDraft,
		connect.WithSchema(emailServiceMethods.ByName("SendOrSaveGmailDraft")),
		connect.WithHandlerOptions(opts...),
	)
	emailServiceSendOrSaveOutlookDraftHandler := connect.NewUnaryHandler(
		EmailServiceSendOrSaveOutlookDraftProcedure,
		svc.SendOrSaveOutlookDraft,
		connect.WithSchema(emailServiceMethods.ByName("SendOrSaveOutlookDraft")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.EmailService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EmailServiceDownloadGmailAttachmentsProcedure:
			emailServiceDownloadGmailAttachmentsHandler.ServeHTTP(w, r)
		case EmailServiceDownloadOutlookAttachmentsProcedure:
			emailServiceDownloadOutlookAttachmentsHandler.ServeHTTP(w, r)
		case EmailServiceSendOrSaveGmailDraftProcedure:
			emailServiceSendOrSaveGmailDraftHandler.ServeHTTP(w, r)
		case EmailServiceSendOrSaveOutlookDraftProcedure:
			emailServiceSendOrSaveOutlookDraftHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEmailServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEmailServiceHandler struct{}

func (UnimplementedEmailServiceHandler) DownloadGmailAttachments(context.Context, *connect.Request[v1.DownloadGmailAttachmentsRequest]) (*connect.Response[v1.DownloadGmailAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.EmailService.DownloadGmailAttachments is not implemented"))
}

func (UnimplementedEmailServiceHandler) DownloadOutlookAttachments(context.Context, *connect.Request[v1.DownloadOutlookAttachmentsRequest]) (*connect.Response[v1.DownloadOutlookAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.EmailService.DownloadOutlookAttachments is not implemented"))
}

func (UnimplementedEmailServiceHandler) SendOrSaveGmailDraft(context.Context, *connect.Request[v1.SendOrSaveGmailDraftRequest]) (*connect.Response[v1.SendOrSaveGmailDraftResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.EmailService.SendOrSaveGmailDraft is not implemented"))
}

func (UnimplementedEmailServiceHandler) SendOrSaveOutlookDraft(context.Context, *connect.Request[v1.SendOrSaveOutlookDraftRequest]) (*connect.Response[v1.SendOrSaveOutlookDraftResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.EmailService.SendOrSaveOutlookDraft is not implemented"))
}
