// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/file.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "runtime.v1.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceDownloadFileProcedure is the fully-qualified name of the FileService's DownloadFile
	// RPC.
	FileServiceDownloadFileProcedure = "/runtime.v1.FileService/DownloadFile"
	// FileServiceBatchReadFilesProcedure is the fully-qualified name of the FileService's
	// BatchReadFiles RPC.
	FileServiceBatchReadFilesProcedure = "/runtime.v1.FileService/BatchReadFiles"
	// FileServiceCheckFilesExistProcedure is the fully-qualified name of the FileService's
	// CheckFilesExist RPC.
	FileServiceCheckFilesExistProcedure = "/runtime.v1.FileService/CheckFilesExist"
	// FileServiceCheckFilesExistAbsProcedure is the fully-qualified name of the FileService's
	// CheckFilesExistAbs RPC.
	FileServiceCheckFilesExistAbsProcedure = "/runtime.v1.FileService/CheckFilesExistAbs"
	// FileServiceMultipartUploadProcedure is the fully-qualified name of the FileService's
	// MultipartUpload RPC.
	FileServiceMultipartUploadProcedure = "/runtime.v1.FileService/MultipartUpload"
	// FileServiceUploadFileToS3Procedure is the fully-qualified name of the FileService's
	// UploadFileToS3 RPC.
	FileServiceUploadFileToS3Procedure = "/runtime.v1.FileService/UploadFileToS3"
	// FileServiceUploadFilesToS3Procedure is the fully-qualified name of the FileService's
	// UploadFilesToS3 RPC.
	FileServiceUploadFilesToS3Procedure = "/runtime.v1.FileService/UploadFilesToS3"
	// FileServiceUploadSlideTemplateImageProcedure is the fully-qualified name of the FileService's
	// UploadSlideTemplateImage RPC.
	FileServiceUploadSlideTemplateImageProcedure = "/runtime.v1.FileService/UploadSlideTemplateImage"
	// FileServiceStoreParallelTasksResultProcedure is the fully-qualified name of the FileService's
	// StoreParallelTasksResult RPC.
	FileServiceStoreParallelTasksResultProcedure = "/runtime.v1.FileService/StoreParallelTasksResult"
	// FileServiceDownloadAttachmentsProcedure is the fully-qualified name of the FileService's
	// DownloadAttachments RPC.
	FileServiceDownloadAttachmentsProcedure = "/runtime.v1.FileService/DownloadAttachments"
	// FileServiceDownloadUserEditedProcedure is the fully-qualified name of the FileService's
	// DownloadUserEdited RPC.
	FileServiceDownloadUserEditedProcedure = "/runtime.v1.FileService/DownloadUserEdited"
)

// FileServiceClient is a client for the runtime.v1.FileService service.
type FileServiceClient interface {
	DownloadFile(context.Context, *connect.Request[v1.DownloadFileRequest]) (*connect.Response[v1.DownloadFileResponse], error)
	BatchReadFiles(context.Context, *connect.Request[v1.BatchReadFilesRequest]) (*connect.Response[v1.BatchReadFilesResponse], error)
	CheckFilesExist(context.Context, *connect.Request[v1.CheckFilesExistRequest]) (*connect.Response[v1.CheckFilesExistResponse], error)
	CheckFilesExistAbs(context.Context, *connect.Request[v1.CheckFilesExistAbsRequest]) (*connect.Response[v1.CheckFilesExistAbsResponse], error)
	MultipartUpload(context.Context, *connect.Request[v1.MultipartUploadRequest]) (*connect.Response[v1.MultipartUploadResponse], error)
	UploadFileToS3(context.Context, *connect.Request[v1.UploadFileToS3Request]) (*connect.Response[v1.UploadFileToS3Response], error)
	UploadFilesToS3(context.Context, *connect.Request[v1.UploadFilesToS3Request]) (*connect.Response[v1.UploadFilesToS3Response], error)
	UploadSlideTemplateImage(context.Context, *connect.Request[v1.UploadSlideTemplateImageRequest]) (*connect.Response[v1.UploadSlideTemplateImageResponse], error)
	StoreParallelTasksResult(context.Context, *connect.Request[v1.StoreParallelTasksResultRequest]) (*connect.Response[v1.StoreParallelTasksResultResponse], error)
	DownloadAttachments(context.Context, *connect.Request[v1.DownloadAttachmentsRequest]) (*connect.Response[v1.DownloadAttachmentsResponse], error)
	DownloadUserEdited(context.Context, *connect.Request[v1.DownloadUserEditedRequest]) (*connect.Response[v1.DownloadUserEditedResponse], error)
}

// NewFileServiceClient constructs a client for the runtime.v1.FileService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fileServiceMethods := v1.File_runtime_v1_file_proto.Services().ByName("FileService").Methods()
	return &fileServiceClient{
		downloadFile: connect.NewClient[v1.DownloadFileRequest, v1.DownloadFileResponse](
			httpClient,
			baseURL+FileServiceDownloadFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DownloadFile")),
			connect.WithClientOptions(opts...),
		),
		batchReadFiles: connect.NewClient[v1.BatchReadFilesRequest, v1.BatchReadFilesResponse](
			httpClient,
			baseURL+FileServiceBatchReadFilesProcedure,
			connect.WithSchema(fileServiceMethods.ByName("BatchReadFiles")),
			connect.WithClientOptions(opts...),
		),
		checkFilesExist: connect.NewClient[v1.CheckFilesExistRequest, v1.CheckFilesExistResponse](
			httpClient,
			baseURL+FileServiceCheckFilesExistProcedure,
			connect.WithSchema(fileServiceMethods.ByName("CheckFilesExist")),
			connect.WithClientOptions(opts...),
		),
		checkFilesExistAbs: connect.NewClient[v1.CheckFilesExistAbsRequest, v1.CheckFilesExistAbsResponse](
			httpClient,
			baseURL+FileServiceCheckFilesExistAbsProcedure,
			connect.WithSchema(fileServiceMethods.ByName("CheckFilesExistAbs")),
			connect.WithClientOptions(opts...),
		),
		multipartUpload: connect.NewClient[v1.MultipartUploadRequest, v1.MultipartUploadResponse](
			httpClient,
			baseURL+FileServiceMultipartUploadProcedure,
			connect.WithSchema(fileServiceMethods.ByName("MultipartUpload")),
			connect.WithClientOptions(opts...),
		),
		uploadFileToS3: connect.NewClient[v1.UploadFileToS3Request, v1.UploadFileToS3Response](
			httpClient,
			baseURL+FileServiceUploadFileToS3Procedure,
			connect.WithSchema(fileServiceMethods.ByName("UploadFileToS3")),
			connect.WithClientOptions(opts...),
		),
		uploadFilesToS3: connect.NewClient[v1.UploadFilesToS3Request, v1.UploadFilesToS3Response](
			httpClient,
			baseURL+FileServiceUploadFilesToS3Procedure,
			connect.WithSchema(fileServiceMethods.ByName("UploadFilesToS3")),
			connect.WithClientOptions(opts...),
		),
		uploadSlideTemplateImage: connect.NewClient[v1.UploadSlideTemplateImageRequest, v1.UploadSlideTemplateImageResponse](
			httpClient,
			baseURL+FileServiceUploadSlideTemplateImageProcedure,
			connect.WithSchema(fileServiceMethods.ByName("UploadSlideTemplateImage")),
			connect.WithClientOptions(opts...),
		),
		storeParallelTasksResult: connect.NewClient[v1.StoreParallelTasksResultRequest, v1.StoreParallelTasksResultResponse](
			httpClient,
			baseURL+FileServiceStoreParallelTasksResultProcedure,
			connect.WithSchema(fileServiceMethods.ByName("StoreParallelTasksResult")),
			connect.WithClientOptions(opts...),
		),
		downloadAttachments: connect.NewClient[v1.DownloadAttachmentsRequest, v1.DownloadAttachmentsResponse](
			httpClient,
			baseURL+FileServiceDownloadAttachmentsProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DownloadAttachments")),
			connect.WithClientOptions(opts...),
		),
		downloadUserEdited: connect.NewClient[v1.DownloadUserEditedRequest, v1.DownloadUserEditedResponse](
			httpClient,
			baseURL+FileServiceDownloadUserEditedProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DownloadUserEdited")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	downloadFile             *connect.Client[v1.DownloadFileRequest, v1.DownloadFileResponse]
	batchReadFiles           *connect.Client[v1.BatchReadFilesRequest, v1.BatchReadFilesResponse]
	checkFilesExist          *connect.Client[v1.CheckFilesExistRequest, v1.CheckFilesExistResponse]
	checkFilesExistAbs       *connect.Client[v1.CheckFilesExistAbsRequest, v1.CheckFilesExistAbsResponse]
	multipartUpload          *connect.Client[v1.MultipartUploadRequest, v1.MultipartUploadResponse]
	uploadFileToS3           *connect.Client[v1.UploadFileToS3Request, v1.UploadFileToS3Response]
	uploadFilesToS3          *connect.Client[v1.UploadFilesToS3Request, v1.UploadFilesToS3Response]
	uploadSlideTemplateImage *connect.Client[v1.UploadSlideTemplateImageRequest, v1.UploadSlideTemplateImageResponse]
	storeParallelTasksResult *connect.Client[v1.StoreParallelTasksResultRequest, v1.StoreParallelTasksResultResponse]
	downloadAttachments      *connect.Client[v1.DownloadAttachmentsRequest, v1.DownloadAttachmentsResponse]
	downloadUserEdited       *connect.Client[v1.DownloadUserEditedRequest, v1.DownloadUserEditedResponse]
}

// DownloadFile calls runtime.v1.FileService.DownloadFile.
func (c *fileServiceClient) DownloadFile(ctx context.Context, req *connect.Request[v1.DownloadFileRequest]) (*connect.Response[v1.DownloadFileResponse], error) {
	return c.downloadFile.CallUnary(ctx, req)
}

// BatchReadFiles calls runtime.v1.FileService.BatchReadFiles.
func (c *fileServiceClient) BatchReadFiles(ctx context.Context, req *connect.Request[v1.BatchReadFilesRequest]) (*connect.Response[v1.BatchReadFilesResponse], error) {
	return c.batchReadFiles.CallUnary(ctx, req)
}

// CheckFilesExist calls runtime.v1.FileService.CheckFilesExist.
func (c *fileServiceClient) CheckFilesExist(ctx context.Context, req *connect.Request[v1.CheckFilesExistRequest]) (*connect.Response[v1.CheckFilesExistResponse], error) {
	return c.checkFilesExist.CallUnary(ctx, req)
}

// CheckFilesExistAbs calls runtime.v1.FileService.CheckFilesExistAbs.
func (c *fileServiceClient) CheckFilesExistAbs(ctx context.Context, req *connect.Request[v1.CheckFilesExistAbsRequest]) (*connect.Response[v1.CheckFilesExistAbsResponse], error) {
	return c.checkFilesExistAbs.CallUnary(ctx, req)
}

// MultipartUpload calls runtime.v1.FileService.MultipartUpload.
func (c *fileServiceClient) MultipartUpload(ctx context.Context, req *connect.Request[v1.MultipartUploadRequest]) (*connect.Response[v1.MultipartUploadResponse], error) {
	return c.multipartUpload.CallUnary(ctx, req)
}

// UploadFileToS3 calls runtime.v1.FileService.UploadFileToS3.
func (c *fileServiceClient) UploadFileToS3(ctx context.Context, req *connect.Request[v1.UploadFileToS3Request]) (*connect.Response[v1.UploadFileToS3Response], error) {
	return c.uploadFileToS3.CallUnary(ctx, req)
}

// UploadFilesToS3 calls runtime.v1.FileService.UploadFilesToS3.
func (c *fileServiceClient) UploadFilesToS3(ctx context.Context, req *connect.Request[v1.UploadFilesToS3Request]) (*connect.Response[v1.UploadFilesToS3Response], error) {
	return c.uploadFilesToS3.CallUnary(ctx, req)
}

// UploadSlideTemplateImage calls runtime.v1.FileService.UploadSlideTemplateImage.
func (c *fileServiceClient) UploadSlideTemplateImage(ctx context.Context, req *connect.Request[v1.UploadSlideTemplateImageRequest]) (*connect.Response[v1.UploadSlideTemplateImageResponse], error) {
	return c.uploadSlideTemplateImage.CallUnary(ctx, req)
}

// StoreParallelTasksResult calls runtime.v1.FileService.StoreParallelTasksResult.
func (c *fileServiceClient) StoreParallelTasksResult(ctx context.Context, req *connect.Request[v1.StoreParallelTasksResultRequest]) (*connect.Response[v1.StoreParallelTasksResultResponse], error) {
	return c.storeParallelTasksResult.CallUnary(ctx, req)
}

// DownloadAttachments calls runtime.v1.FileService.DownloadAttachments.
func (c *fileServiceClient) DownloadAttachments(ctx context.Context, req *connect.Request[v1.DownloadAttachmentsRequest]) (*connect.Response[v1.DownloadAttachmentsResponse], error) {
	return c.downloadAttachments.CallUnary(ctx, req)
}

// DownloadUserEdited calls runtime.v1.FileService.DownloadUserEdited.
func (c *fileServiceClient) DownloadUserEdited(ctx context.Context, req *connect.Request[v1.DownloadUserEditedRequest]) (*connect.Response[v1.DownloadUserEditedResponse], error) {
	return c.downloadUserEdited.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the runtime.v1.FileService service.
type FileServiceHandler interface {
	DownloadFile(context.Context, *connect.Request[v1.DownloadFileRequest]) (*connect.Response[v1.DownloadFileResponse], error)
	BatchReadFiles(context.Context, *connect.Request[v1.BatchReadFilesRequest]) (*connect.Response[v1.BatchReadFilesResponse], error)
	CheckFilesExist(context.Context, *connect.Request[v1.CheckFilesExistRequest]) (*connect.Response[v1.CheckFilesExistResponse], error)
	CheckFilesExistAbs(context.Context, *connect.Request[v1.CheckFilesExistAbsRequest]) (*connect.Response[v1.CheckFilesExistAbsResponse], error)
	MultipartUpload(context.Context, *connect.Request[v1.MultipartUploadRequest]) (*connect.Response[v1.MultipartUploadResponse], error)
	UploadFileToS3(context.Context, *connect.Request[v1.UploadFileToS3Request]) (*connect.Response[v1.UploadFileToS3Response], error)
	UploadFilesToS3(context.Context, *connect.Request[v1.UploadFilesToS3Request]) (*connect.Response[v1.UploadFilesToS3Response], error)
	UploadSlideTemplateImage(context.Context, *connect.Request[v1.UploadSlideTemplateImageRequest]) (*connect.Response[v1.UploadSlideTemplateImageResponse], error)
	StoreParallelTasksResult(context.Context, *connect.Request[v1.StoreParallelTasksResultRequest]) (*connect.Response[v1.StoreParallelTasksResultResponse], error)
	DownloadAttachments(context.Context, *connect.Request[v1.DownloadAttachmentsRequest]) (*connect.Response[v1.DownloadAttachmentsResponse], error)
	DownloadUserEdited(context.Context, *connect.Request[v1.DownloadUserEditedRequest]) (*connect.Response[v1.DownloadUserEditedResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceMethods := v1.File_runtime_v1_file_proto.Services().ByName("FileService").Methods()
	fileServiceDownloadFileHandler := connect.NewUnaryHandler(
		FileServiceDownloadFileProcedure,
		svc.DownloadFile,
		connect.WithSchema(fileServiceMethods.ByName("DownloadFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceBatchReadFilesHandler := connect.NewUnaryHandler(
		FileServiceBatchReadFilesProcedure,
		svc.BatchReadFiles,
		connect.WithSchema(fileServiceMethods.ByName("BatchReadFiles")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceCheckFilesExistHandler := connect.NewUnaryHandler(
		FileServiceCheckFilesExistProcedure,
		svc.CheckFilesExist,
		connect.WithSchema(fileServiceMethods.ByName("CheckFilesExist")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceCheckFilesExistAbsHandler := connect.NewUnaryHandler(
		FileServiceCheckFilesExistAbsProcedure,
		svc.CheckFilesExistAbs,
		connect.WithSchema(fileServiceMethods.ByName("CheckFilesExistAbs")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceMultipartUploadHandler := connect.NewUnaryHandler(
		FileServiceMultipartUploadProcedure,
		svc.MultipartUpload,
		connect.WithSchema(fileServiceMethods.ByName("MultipartUpload")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceUploadFileToS3Handler := connect.NewUnaryHandler(
		FileServiceUploadFileToS3Procedure,
		svc.UploadFileToS3,
		connect.WithSchema(fileServiceMethods.ByName("UploadFileToS3")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceUploadFilesToS3Handler := connect.NewUnaryHandler(
		FileServiceUploadFilesToS3Procedure,
		svc.UploadFilesToS3,
		connect.WithSchema(fileServiceMethods.ByName("UploadFilesToS3")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceUploadSlideTemplateImageHandler := connect.NewUnaryHandler(
		FileServiceUploadSlideTemplateImageProcedure,
		svc.UploadSlideTemplateImage,
		connect.WithSchema(fileServiceMethods.ByName("UploadSlideTemplateImage")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceStoreParallelTasksResultHandler := connect.NewUnaryHandler(
		FileServiceStoreParallelTasksResultProcedure,
		svc.StoreParallelTasksResult,
		connect.WithSchema(fileServiceMethods.ByName("StoreParallelTasksResult")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDownloadAttachmentsHandler := connect.NewUnaryHandler(
		FileServiceDownloadAttachmentsProcedure,
		svc.DownloadAttachments,
		connect.WithSchema(fileServiceMethods.ByName("DownloadAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDownloadUserEditedHandler := connect.NewUnaryHandler(
		FileServiceDownloadUserEditedProcedure,
		svc.DownloadUserEdited,
		connect.WithSchema(fileServiceMethods.ByName("DownloadUserEdited")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServiceDownloadFileProcedure:
			fileServiceDownloadFileHandler.ServeHTTP(w, r)
		case FileServiceBatchReadFilesProcedure:
			fileServiceBatchReadFilesHandler.ServeHTTP(w, r)
		case FileServiceCheckFilesExistProcedure:
			fileServiceCheckFilesExistHandler.ServeHTTP(w, r)
		case FileServiceCheckFilesExistAbsProcedure:
			fileServiceCheckFilesExistAbsHandler.ServeHTTP(w, r)
		case FileServiceMultipartUploadProcedure:
			fileServiceMultipartUploadHandler.ServeHTTP(w, r)
		case FileServiceUploadFileToS3Procedure:
			fileServiceUploadFileToS3Handler.ServeHTTP(w, r)
		case FileServiceUploadFilesToS3Procedure:
			fileServiceUploadFilesToS3Handler.ServeHTTP(w, r)
		case FileServiceUploadSlideTemplateImageProcedure:
			fileServiceUploadSlideTemplateImageHandler.ServeHTTP(w, r)
		case FileServiceStoreParallelTasksResultProcedure:
			fileServiceStoreParallelTasksResultHandler.ServeHTTP(w, r)
		case FileServiceDownloadAttachmentsProcedure:
			fileServiceDownloadAttachmentsHandler.ServeHTTP(w, r)
		case FileServiceDownloadUserEditedProcedure:
			fileServiceDownloadUserEditedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) DownloadFile(context.Context, *connect.Request[v1.DownloadFileRequest]) (*connect.Response[v1.DownloadFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.DownloadFile is not implemented"))
}

func (UnimplementedFileServiceHandler) BatchReadFiles(context.Context, *connect.Request[v1.BatchReadFilesRequest]) (*connect.Response[v1.BatchReadFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.BatchReadFiles is not implemented"))
}

func (UnimplementedFileServiceHandler) CheckFilesExist(context.Context, *connect.Request[v1.CheckFilesExistRequest]) (*connect.Response[v1.CheckFilesExistResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.CheckFilesExist is not implemented"))
}

func (UnimplementedFileServiceHandler) CheckFilesExistAbs(context.Context, *connect.Request[v1.CheckFilesExistAbsRequest]) (*connect.Response[v1.CheckFilesExistAbsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.CheckFilesExistAbs is not implemented"))
}

func (UnimplementedFileServiceHandler) MultipartUpload(context.Context, *connect.Request[v1.MultipartUploadRequest]) (*connect.Response[v1.MultipartUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.MultipartUpload is not implemented"))
}

func (UnimplementedFileServiceHandler) UploadFileToS3(context.Context, *connect.Request[v1.UploadFileToS3Request]) (*connect.Response[v1.UploadFileToS3Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.UploadFileToS3 is not implemented"))
}

func (UnimplementedFileServiceHandler) UploadFilesToS3(context.Context, *connect.Request[v1.UploadFilesToS3Request]) (*connect.Response[v1.UploadFilesToS3Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.UploadFilesToS3 is not implemented"))
}

func (UnimplementedFileServiceHandler) UploadSlideTemplateImage(context.Context, *connect.Request[v1.UploadSlideTemplateImageRequest]) (*connect.Response[v1.UploadSlideTemplateImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.UploadSlideTemplateImage is not implemented"))
}

func (UnimplementedFileServiceHandler) StoreParallelTasksResult(context.Context, *connect.Request[v1.StoreParallelTasksResultRequest]) (*connect.Response[v1.StoreParallelTasksResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.StoreParallelTasksResult is not implemented"))
}

func (UnimplementedFileServiceHandler) DownloadAttachments(context.Context, *connect.Request[v1.DownloadAttachmentsRequest]) (*connect.Response[v1.DownloadAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.DownloadAttachments is not implemented"))
}

func (UnimplementedFileServiceHandler) DownloadUserEdited(context.Context, *connect.Request[v1.DownloadUserEditedRequest]) (*connect.Response[v1.DownloadUserEditedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.FileService.DownloadUserEdited is not implemented"))
}
