// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/image.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ImageServiceName is the fully-qualified name of the ImageService service.
	ImageServiceName = "runtime.v1.ImageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ImageServiceRemoveBackgroundProcedure is the fully-qualified name of the ImageService's
	// RemoveBackground RPC.
	ImageServiceRemoveBackgroundProcedure = "/runtime.v1.ImageService/RemoveBackground"
	// ImageServiceUploadSearchImageProcedure is the fully-qualified name of the ImageService's
	// UploadSearchImage RPC.
	ImageServiceUploadSearchImageProcedure = "/runtime.v1.ImageService/UploadSearchImage"
)

// ImageServiceClient is a client for the runtime.v1.ImageService service.
type ImageServiceClient interface {
	RemoveBackground(context.Context, *connect.Request[v1.RemoveBackgroundRequest]) (*connect.Response[v1.RemoveBackgroundResponse], error)
	UploadSearchImage(context.Context, *connect.Request[v1.UploadSearchImageRequest]) (*connect.Response[v1.UploadSearchImageResponse], error)
}

// NewImageServiceClient constructs a client for the runtime.v1.ImageService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewImageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ImageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	imageServiceMethods := v1.File_runtime_v1_image_proto.Services().ByName("ImageService").Methods()
	return &imageServiceClient{
		removeBackground: connect.NewClient[v1.RemoveBackgroundRequest, v1.RemoveBackgroundResponse](
			httpClient,
			baseURL+ImageServiceRemoveBackgroundProcedure,
			connect.WithSchema(imageServiceMethods.ByName("RemoveBackground")),
			connect.WithClientOptions(opts...),
		),
		uploadSearchImage: connect.NewClient[v1.UploadSearchImageRequest, v1.UploadSearchImageResponse](
			httpClient,
			baseURL+ImageServiceUploadSearchImageProcedure,
			connect.WithSchema(imageServiceMethods.ByName("UploadSearchImage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// imageServiceClient implements ImageServiceClient.
type imageServiceClient struct {
	removeBackground  *connect.Client[v1.RemoveBackgroundRequest, v1.RemoveBackgroundResponse]
	uploadSearchImage *connect.Client[v1.UploadSearchImageRequest, v1.UploadSearchImageResponse]
}

// RemoveBackground calls runtime.v1.ImageService.RemoveBackground.
func (c *imageServiceClient) RemoveBackground(ctx context.Context, req *connect.Request[v1.RemoveBackgroundRequest]) (*connect.Response[v1.RemoveBackgroundResponse], error) {
	return c.removeBackground.CallUnary(ctx, req)
}

// UploadSearchImage calls runtime.v1.ImageService.UploadSearchImage.
func (c *imageServiceClient) UploadSearchImage(ctx context.Context, req *connect.Request[v1.UploadSearchImageRequest]) (*connect.Response[v1.UploadSearchImageResponse], error) {
	return c.uploadSearchImage.CallUnary(ctx, req)
}

// ImageServiceHandler is an implementation of the runtime.v1.ImageService service.
type ImageServiceHandler interface {
	RemoveBackground(context.Context, *connect.Request[v1.RemoveBackgroundRequest]) (*connect.Response[v1.RemoveBackgroundResponse], error)
	UploadSearchImage(context.Context, *connect.Request[v1.UploadSearchImageRequest]) (*connect.Response[v1.UploadSearchImageResponse], error)
}

// NewImageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewImageServiceHandler(svc ImageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	imageServiceMethods := v1.File_runtime_v1_image_proto.Services().ByName("ImageService").Methods()
	imageServiceRemoveBackgroundHandler := connect.NewUnaryHandler(
		ImageServiceRemoveBackgroundProcedure,
		svc.RemoveBackground,
		connect.WithSchema(imageServiceMethods.ByName("RemoveBackground")),
		connect.WithHandlerOptions(opts...),
	)
	imageServiceUploadSearchImageHandler := connect.NewUnaryHandler(
		ImageServiceUploadSearchImageProcedure,
		svc.UploadSearchImage,
		connect.WithSchema(imageServiceMethods.ByName("UploadSearchImage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.ImageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ImageServiceRemoveBackgroundProcedure:
			imageServiceRemoveBackgroundHandler.ServeHTTP(w, r)
		case ImageServiceUploadSearchImageProcedure:
			imageServiceUploadSearchImageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedImageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedImageServiceHandler struct{}

func (UnimplementedImageServiceHandler) RemoveBackground(context.Context, *connect.Request[v1.RemoveBackgroundRequest]) (*connect.Response[v1.RemoveBackgroundResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ImageService.RemoveBackground is not implemented"))
}

func (UnimplementedImageServiceHandler) UploadSearchImage(context.Context, *connect.Request[v1.UploadSearchImageRequest]) (*connect.Response[v1.UploadSearchImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.ImageService.UploadSearchImage is not implemented"))
}
