// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/runtime.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RuntimeServiceName is the fully-qualified name of the RuntimeService service.
	RuntimeServiceName = "runtime.v1.RuntimeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RuntimeServiceInitSandboxProcedure is the fully-qualified name of the RuntimeService's
	// InitSandbox RPC.
	RuntimeServiceInitSandboxProcedure = "/runtime.v1.RuntimeService/InitSandbox"
	// RuntimeServiceGetHealthProcedure is the fully-qualified name of the RuntimeService's GetHealth
	// RPC.
	RuntimeServiceGetHealthProcedure = "/runtime.v1.RuntimeService/GetHealth"
	// RuntimeServiceGetVersionProcedure is the fully-qualified name of the RuntimeService's GetVersion
	// RPC.
	RuntimeServiceGetVersionProcedure = "/runtime.v1.RuntimeService/GetVersion"
	// RuntimeServiceHasFuseProcedure is the fully-qualified name of the RuntimeService's HasFuse RPC.
	RuntimeServiceHasFuseProcedure = "/runtime.v1.RuntimeService/HasFuse"
)

// RuntimeServiceClient is a client for the runtime.v1.RuntimeService service.
type RuntimeServiceClient interface {
	InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error)
	GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.GetHealthResponse], error)
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	HasFuse(context.Context, *connect.Request[v1.HasFuseRequest]) (*connect.Response[v1.HasFuseResponse], error)
}

// NewRuntimeServiceClient constructs a client for the runtime.v1.RuntimeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRuntimeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RuntimeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runtimeServiceMethods := v1.File_runtime_v1_runtime_proto.Services().ByName("RuntimeService").Methods()
	return &runtimeServiceClient{
		initSandbox: connect.NewClient[v1.InitSandboxRequest, v1.InitSandboxResponse](
			httpClient,
			baseURL+RuntimeServiceInitSandboxProcedure,
			connect.WithSchema(runtimeServiceMethods.ByName("InitSandbox")),
			connect.WithClientOptions(opts...),
		),
		getHealth: connect.NewClient[v1.GetHealthRequest, v1.GetHealthResponse](
			httpClient,
			baseURL+RuntimeServiceGetHealthProcedure,
			connect.WithSchema(runtimeServiceMethods.ByName("GetHealth")),
			connect.WithClientOptions(opts...),
		),
		getVersion: connect.NewClient[v1.GetVersionRequest, v1.GetVersionResponse](
			httpClient,
			baseURL+RuntimeServiceGetVersionProcedure,
			connect.WithSchema(runtimeServiceMethods.ByName("GetVersion")),
			connect.WithClientOptions(opts...),
		),
		hasFuse: connect.NewClient[v1.HasFuseRequest, v1.HasFuseResponse](
			httpClient,
			baseURL+RuntimeServiceHasFuseProcedure,
			connect.WithSchema(runtimeServiceMethods.ByName("HasFuse")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runtimeServiceClient implements RuntimeServiceClient.
type runtimeServiceClient struct {
	initSandbox *connect.Client[v1.InitSandboxRequest, v1.InitSandboxResponse]
	getHealth   *connect.Client[v1.GetHealthRequest, v1.GetHealthResponse]
	getVersion  *connect.Client[v1.GetVersionRequest, v1.GetVersionResponse]
	hasFuse     *connect.Client[v1.HasFuseRequest, v1.HasFuseResponse]
}

// InitSandbox calls runtime.v1.RuntimeService.InitSandbox.
func (c *runtimeServiceClient) InitSandbox(ctx context.Context, req *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error) {
	return c.initSandbox.CallUnary(ctx, req)
}

// GetHealth calls runtime.v1.RuntimeService.GetHealth.
func (c *runtimeServiceClient) GetHealth(ctx context.Context, req *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.GetHealthResponse], error) {
	return c.getHealth.CallUnary(ctx, req)
}

// GetVersion calls runtime.v1.RuntimeService.GetVersion.
func (c *runtimeServiceClient) GetVersion(ctx context.Context, req *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return c.getVersion.CallUnary(ctx, req)
}

// HasFuse calls runtime.v1.RuntimeService.HasFuse.
func (c *runtimeServiceClient) HasFuse(ctx context.Context, req *connect.Request[v1.HasFuseRequest]) (*connect.Response[v1.HasFuseResponse], error) {
	return c.hasFuse.CallUnary(ctx, req)
}

// RuntimeServiceHandler is an implementation of the runtime.v1.RuntimeService service.
type RuntimeServiceHandler interface {
	InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error)
	GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.GetHealthResponse], error)
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	HasFuse(context.Context, *connect.Request[v1.HasFuseRequest]) (*connect.Response[v1.HasFuseResponse], error)
}

// NewRuntimeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRuntimeServiceHandler(svc RuntimeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runtimeServiceMethods := v1.File_runtime_v1_runtime_proto.Services().ByName("RuntimeService").Methods()
	runtimeServiceInitSandboxHandler := connect.NewUnaryHandler(
		RuntimeServiceInitSandboxProcedure,
		svc.InitSandbox,
		connect.WithSchema(runtimeServiceMethods.ByName("InitSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeServiceGetHealthHandler := connect.NewUnaryHandler(
		RuntimeServiceGetHealthProcedure,
		svc.GetHealth,
		connect.WithSchema(runtimeServiceMethods.ByName("GetHealth")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeServiceGetVersionHandler := connect.NewUnaryHandler(
		RuntimeServiceGetVersionProcedure,
		svc.GetVersion,
		connect.WithSchema(runtimeServiceMethods.ByName("GetVersion")),
		connect.WithHandlerOptions(opts...),
	)
	runtimeServiceHasFuseHandler := connect.NewUnaryHandler(
		RuntimeServiceHasFuseProcedure,
		svc.HasFuse,
		connect.WithSchema(runtimeServiceMethods.ByName("HasFuse")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.RuntimeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RuntimeServiceInitSandboxProcedure:
			runtimeServiceInitSandboxHandler.ServeHTTP(w, r)
		case RuntimeServiceGetHealthProcedure:
			runtimeServiceGetHealthHandler.ServeHTTP(w, r)
		case RuntimeServiceGetVersionProcedure:
			runtimeServiceGetVersionHandler.ServeHTTP(w, r)
		case RuntimeServiceHasFuseProcedure:
			runtimeServiceHasFuseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRuntimeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRuntimeServiceHandler struct{}

func (UnimplementedRuntimeServiceHandler) InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.RuntimeService.InitSandbox is not implemented"))
}

func (UnimplementedRuntimeServiceHandler) GetHealth(context.Context, *connect.Request[v1.GetHealthRequest]) (*connect.Response[v1.GetHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.RuntimeService.GetHealth is not implemented"))
}

func (UnimplementedRuntimeServiceHandler) GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.RuntimeService.GetVersion is not implemented"))
}

func (UnimplementedRuntimeServiceHandler) HasFuse(context.Context, *connect.Request[v1.HasFuseRequest]) (*connect.Response[v1.HasFuseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.RuntimeService.HasFuse is not implemented"))
}
