// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/slide.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SlideServiceName is the fully-qualified name of the SlideService service.
	SlideServiceName = "runtime.v1.SlideService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SlideServiceInitSlideProjectProcedure is the fully-qualified name of the SlideService's
	// InitSlideProject RPC.
	SlideServiceInitSlideProjectProcedure = "/runtime.v1.SlideService/InitSlideProject"
	// SlideServiceModifySlideProcedure is the fully-qualified name of the SlideService's ModifySlide
	// RPC.
	SlideServiceModifySlideProcedure = "/runtime.v1.SlideService/ModifySlide"
	// SlideServicePresentSlideProcedure is the fully-qualified name of the SlideService's PresentSlide
	// RPC.
	SlideServicePresentSlideProcedure = "/runtime.v1.SlideService/PresentSlide"
	// SlideServiceFetchSlideNotesProcedure is the fully-qualified name of the SlideService's
	// FetchSlideNotes RPC.
	SlideServiceFetchSlideNotesProcedure = "/runtime.v1.SlideService/FetchSlideNotes"
	// SlideServiceUpdateSlideProcedure is the fully-qualified name of the SlideService's UpdateSlide
	// RPC.
	SlideServiceUpdateSlideProcedure = "/runtime.v1.SlideService/UpdateSlide"
	// SlideServiceUploadSlideProcedure is the fully-qualified name of the SlideService's UploadSlide
	// RPC.
	SlideServiceUploadSlideProcedure = "/runtime.v1.SlideService/UploadSlide"
	// SlideServiceUploadSlideTemplateProcedure is the fully-qualified name of the SlideService's
	// UploadSlideTemplate RPC.
	SlideServiceUploadSlideTemplateProcedure = "/runtime.v1.SlideService/UploadSlideTemplate"
)

// SlideServiceClient is a client for the runtime.v1.SlideService service.
type SlideServiceClient interface {
	InitSlideProject(context.Context, *connect.Request[v1.InitSlideProjectRequest]) (*connect.Response[v1.InitSlideProjectResponse], error)
	ModifySlide(context.Context, *connect.Request[v1.ModifySlideRequest]) (*connect.Response[v1.ModifySlideResponse], error)
	PresentSlide(context.Context, *connect.Request[v1.PresentSlideRequest]) (*connect.Response[v1.PresentSlideResponse], error)
	FetchSlideNotes(context.Context, *connect.Request[v1.FetchSlideNotesRequest]) (*connect.Response[v1.FetchSlideNotesResponse], error)
	UpdateSlide(context.Context, *connect.Request[v1.UpdateSlideRequest]) (*connect.Response[v1.UpdateSlideResponse], error)
	UploadSlide(context.Context, *connect.Request[v1.UploadSlideRequest]) (*connect.Response[v1.UploadSlideResponse], error)
	UploadSlideTemplate(context.Context, *connect.Request[v1.UploadSlideTemplateRequest]) (*connect.Response[v1.UploadSlideTemplateResponse], error)
}

// NewSlideServiceClient constructs a client for the runtime.v1.SlideService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSlideServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SlideServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	slideServiceMethods := v1.File_runtime_v1_slide_proto.Services().ByName("SlideService").Methods()
	return &slideServiceClient{
		initSlideProject: connect.NewClient[v1.InitSlideProjectRequest, v1.InitSlideProjectResponse](
			httpClient,
			baseURL+SlideServiceInitSlideProjectProcedure,
			connect.WithSchema(slideServiceMethods.ByName("InitSlideProject")),
			connect.WithClientOptions(opts...),
		),
		modifySlide: connect.NewClient[v1.ModifySlideRequest, v1.ModifySlideResponse](
			httpClient,
			baseURL+SlideServiceModifySlideProcedure,
			connect.WithSchema(slideServiceMethods.ByName("ModifySlide")),
			connect.WithClientOptions(opts...),
		),
		presentSlide: connect.NewClient[v1.PresentSlideRequest, v1.PresentSlideResponse](
			httpClient,
			baseURL+SlideServicePresentSlideProcedure,
			connect.WithSchema(slideServiceMethods.ByName("PresentSlide")),
			connect.WithClientOptions(opts...),
		),
		fetchSlideNotes: connect.NewClient[v1.FetchSlideNotesRequest, v1.FetchSlideNotesResponse](
			httpClient,
			baseURL+SlideServiceFetchSlideNotesProcedure,
			connect.WithSchema(slideServiceMethods.ByName("FetchSlideNotes")),
			connect.WithClientOptions(opts...),
		),
		updateSlide: connect.NewClient[v1.UpdateSlideRequest, v1.UpdateSlideResponse](
			httpClient,
			baseURL+SlideServiceUpdateSlideProcedure,
			connect.WithSchema(slideServiceMethods.ByName("UpdateSlide")),
			connect.WithClientOptions(opts...),
		),
		uploadSlide: connect.NewClient[v1.UploadSlideRequest, v1.UploadSlideResponse](
			httpClient,
			baseURL+SlideServiceUploadSlideProcedure,
			connect.WithSchema(slideServiceMethods.ByName("UploadSlide")),
			connect.WithClientOptions(opts...),
		),
		uploadSlideTemplate: connect.NewClient[v1.UploadSlideTemplateRequest, v1.UploadSlideTemplateResponse](
			httpClient,
			baseURL+SlideServiceUploadSlideTemplateProcedure,
			connect.WithSchema(slideServiceMethods.ByName("UploadSlideTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// slideServiceClient implements SlideServiceClient.
type slideServiceClient struct {
	initSlideProject    *connect.Client[v1.InitSlideProjectRequest, v1.InitSlideProjectResponse]
	modifySlide         *connect.Client[v1.ModifySlideRequest, v1.ModifySlideResponse]
	presentSlide        *connect.Client[v1.PresentSlideRequest, v1.PresentSlideResponse]
	fetchSlideNotes     *connect.Client[v1.FetchSlideNotesRequest, v1.FetchSlideNotesResponse]
	updateSlide         *connect.Client[v1.UpdateSlideRequest, v1.UpdateSlideResponse]
	uploadSlide         *connect.Client[v1.UploadSlideRequest, v1.UploadSlideResponse]
	uploadSlideTemplate *connect.Client[v1.UploadSlideTemplateRequest, v1.UploadSlideTemplateResponse]
}

// InitSlideProject calls runtime.v1.SlideService.InitSlideProject.
func (c *slideServiceClient) InitSlideProject(ctx context.Context, req *connect.Request[v1.InitSlideProjectRequest]) (*connect.Response[v1.InitSlideProjectResponse], error) {
	return c.initSlideProject.CallUnary(ctx, req)
}

// ModifySlide calls runtime.v1.SlideService.ModifySlide.
func (c *slideServiceClient) ModifySlide(ctx context.Context, req *connect.Request[v1.ModifySlideRequest]) (*connect.Response[v1.ModifySlideResponse], error) {
	return c.modifySlide.CallUnary(ctx, req)
}

// PresentSlide calls runtime.v1.SlideService.PresentSlide.
func (c *slideServiceClient) PresentSlide(ctx context.Context, req *connect.Request[v1.PresentSlideRequest]) (*connect.Response[v1.PresentSlideResponse], error) {
	return c.presentSlide.CallUnary(ctx, req)
}

// FetchSlideNotes calls runtime.v1.SlideService.FetchSlideNotes.
func (c *slideServiceClient) FetchSlideNotes(ctx context.Context, req *connect.Request[v1.FetchSlideNotesRequest]) (*connect.Response[v1.FetchSlideNotesResponse], error) {
	return c.fetchSlideNotes.CallUnary(ctx, req)
}

// UpdateSlide calls runtime.v1.SlideService.UpdateSlide.
func (c *slideServiceClient) UpdateSlide(ctx context.Context, req *connect.Request[v1.UpdateSlideRequest]) (*connect.Response[v1.UpdateSlideResponse], error) {
	return c.updateSlide.CallUnary(ctx, req)
}

// UploadSlide calls runtime.v1.SlideService.UploadSlide.
func (c *slideServiceClient) UploadSlide(ctx context.Context, req *connect.Request[v1.UploadSlideRequest]) (*connect.Response[v1.UploadSlideResponse], error) {
	return c.uploadSlide.CallUnary(ctx, req)
}

// UploadSlideTemplate calls runtime.v1.SlideService.UploadSlideTemplate.
func (c *slideServiceClient) UploadSlideTemplate(ctx context.Context, req *connect.Request[v1.UploadSlideTemplateRequest]) (*connect.Response[v1.UploadSlideTemplateResponse], error) {
	return c.uploadSlideTemplate.CallUnary(ctx, req)
}

// SlideServiceHandler is an implementation of the runtime.v1.SlideService service.
type SlideServiceHandler interface {
	InitSlideProject(context.Context, *connect.Request[v1.InitSlideProjectRequest]) (*connect.Response[v1.InitSlideProjectResponse], error)
	ModifySlide(context.Context, *connect.Request[v1.ModifySlideRequest]) (*connect.Response[v1.ModifySlideResponse], error)
	PresentSlide(context.Context, *connect.Request[v1.PresentSlideRequest]) (*connect.Response[v1.PresentSlideResponse], error)
	FetchSlideNotes(context.Context, *connect.Request[v1.FetchSlideNotesRequest]) (*connect.Response[v1.FetchSlideNotesResponse], error)
	UpdateSlide(context.Context, *connect.Request[v1.UpdateSlideRequest]) (*connect.Response[v1.UpdateSlideResponse], error)
	UploadSlide(context.Context, *connect.Request[v1.UploadSlideRequest]) (*connect.Response[v1.UploadSlideResponse], error)
	UploadSlideTemplate(context.Context, *connect.Request[v1.UploadSlideTemplateRequest]) (*connect.Response[v1.UploadSlideTemplateResponse], error)
}

// NewSlideServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSlideServiceHandler(svc SlideServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	slideServiceMethods := v1.File_runtime_v1_slide_proto.Services().ByName("SlideService").Methods()
	slideServiceInitSlideProjectHandler := connect.NewUnaryHandler(
		SlideServiceInitSlideProjectProcedure,
		svc.InitSlideProject,
		connect.WithSchema(slideServiceMethods.ByName("InitSlideProject")),
		connect.WithHandlerOptions(opts...),
	)
	slideServiceModifySlideHandler := connect.NewUnaryHandler(
		SlideServiceModifySlideProcedure,
		svc.ModifySlide,
		connect.WithSchema(slideServiceMethods.ByName("ModifySlide")),
		connect.WithHandlerOptions(opts...),
	)
	slideServicePresentSlideHandler := connect.NewUnaryHandler(
		SlideServicePresentSlideProcedure,
		svc.PresentSlide,
		connect.WithSchema(slideServiceMethods.ByName("PresentSlide")),
		connect.WithHandlerOptions(opts...),
	)
	slideServiceFetchSlideNotesHandler := connect.NewUnaryHandler(
		SlideServiceFetchSlideNotesProcedure,
		svc.FetchSlideNotes,
		connect.WithSchema(slideServiceMethods.ByName("FetchSlideNotes")),
		connect.WithHandlerOptions(opts...),
	)
	slideServiceUpdateSlideHandler := connect.NewUnaryHandler(
		SlideServiceUpdateSlideProcedure,
		svc.UpdateSlide,
		connect.WithSchema(slideServiceMethods.ByName("UpdateSlide")),
		connect.WithHandlerOptions(opts...),
	)
	slideServiceUploadSlideHandler := connect.NewUnaryHandler(
		SlideServiceUploadSlideProcedure,
		svc.UploadSlide,
		connect.WithSchema(slideServiceMethods.ByName("UploadSlide")),
		connect.WithHandlerOptions(opts...),
	)
	slideServiceUploadSlideTemplateHandler := connect.NewUnaryHandler(
		SlideServiceUploadSlideTemplateProcedure,
		svc.UploadSlideTemplate,
		connect.WithSchema(slideServiceMethods.ByName("UploadSlideTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.SlideService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SlideServiceInitSlideProjectProcedure:
			slideServiceInitSlideProjectHandler.ServeHTTP(w, r)
		case SlideServiceModifySlideProcedure:
			slideServiceModifySlideHandler.ServeHTTP(w, r)
		case SlideServicePresentSlideProcedure:
			slideServicePresentSlideHandler.ServeHTTP(w, r)
		case SlideServiceFetchSlideNotesProcedure:
			slideServiceFetchSlideNotesHandler.ServeHTTP(w, r)
		case SlideServiceUpdateSlideProcedure:
			slideServiceUpdateSlideHandler.ServeHTTP(w, r)
		case SlideServiceUploadSlideProcedure:
			slideServiceUploadSlideHandler.ServeHTTP(w, r)
		case SlideServiceUploadSlideTemplateProcedure:
			slideServiceUploadSlideTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSlideServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSlideServiceHandler struct{}

func (UnimplementedSlideServiceHandler) InitSlideProject(context.Context, *connect.Request[v1.InitSlideProjectRequest]) (*connect.Response[v1.InitSlideProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.InitSlideProject is not implemented"))
}

func (UnimplementedSlideServiceHandler) ModifySlide(context.Context, *connect.Request[v1.ModifySlideRequest]) (*connect.Response[v1.ModifySlideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.ModifySlide is not implemented"))
}

func (UnimplementedSlideServiceHandler) PresentSlide(context.Context, *connect.Request[v1.PresentSlideRequest]) (*connect.Response[v1.PresentSlideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.PresentSlide is not implemented"))
}

func (UnimplementedSlideServiceHandler) FetchSlideNotes(context.Context, *connect.Request[v1.FetchSlideNotesRequest]) (*connect.Response[v1.FetchSlideNotesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.FetchSlideNotes is not implemented"))
}

func (UnimplementedSlideServiceHandler) UpdateSlide(context.Context, *connect.Request[v1.UpdateSlideRequest]) (*connect.Response[v1.UpdateSlideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.UpdateSlide is not implemented"))
}

func (UnimplementedSlideServiceHandler) UploadSlide(context.Context, *connect.Request[v1.UploadSlideRequest]) (*connect.Response[v1.UploadSlideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.UploadSlide is not implemented"))
}

func (UnimplementedSlideServiceHandler) UploadSlideTemplate(context.Context, *connect.Request[v1.UploadSlideTemplateRequest]) (*connect.Response[v1.UploadSlideTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.SlideService.UploadSlideTemplate is not implemented"))
}
