// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/terminal.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TerminalServiceName is the fully-qualified name of the TerminalService service.
	TerminalServiceName = "runtime.v1.TerminalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TerminalServiceViewProcedure is the fully-qualified name of the TerminalService's View RPC.
	TerminalServiceViewProcedure = "/runtime.v1.TerminalService/View"
	// TerminalServiceWriteProcedure is the fully-qualified name of the TerminalService's Write RPC.
	TerminalServiceWriteProcedure = "/runtime.v1.TerminalService/Write"
	// TerminalServiceResetProcedure is the fully-qualified name of the TerminalService's Reset RPC.
	TerminalServiceResetProcedure = "/runtime.v1.TerminalService/Reset"
	// TerminalServiceResetAllProcedure is the fully-qualified name of the TerminalService's ResetAll
	// RPC.
	TerminalServiceResetAllProcedure = "/runtime.v1.TerminalService/ResetAll"
	// TerminalServiceKillTerminalProcessProcedure is the fully-qualified name of the TerminalService's
	// KillTerminalProcess RPC.
	TerminalServiceKillTerminalProcessProcedure = "/runtime.v1.TerminalService/KillTerminalProcess"
)

// TerminalServiceClient is a client for the runtime.v1.TerminalService service.
type TerminalServiceClient interface {
	View(context.Context, *connect.Request[v1.ViewRequest]) (*connect.Response[v1.ViewResponse], error)
	Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error)
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error)
	ResetAll(context.Context, *connect.Request[v1.ResetAllRequest]) (*connect.Response[v1.ResetAllResponse], error)
	KillTerminalProcess(context.Context, *connect.Request[v1.KillTerminalProcessRequest]) (*connect.Response[v1.KillTerminalProcessResponse], error)
}

// NewTerminalServiceClient constructs a client for the runtime.v1.TerminalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTerminalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TerminalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	terminalServiceMethods := v1.File_runtime_v1_terminal_proto.Services().ByName("TerminalService").Methods()
	return &terminalServiceClient{
		view: connect.NewClient[v1.ViewRequest, v1.ViewResponse](
			httpClient,
			baseURL+TerminalServiceViewProcedure,
			connect.WithSchema(terminalServiceMethods.ByName("View")),
			connect.WithClientOptions(opts...),
		),
		write: connect.NewClient[v1.WriteRequest, v1.WriteResponse](
			httpClient,
			baseURL+TerminalServiceWriteProcedure,
			connect.WithSchema(terminalServiceMethods.ByName("Write")),
			connect.WithClientOptions(opts...),
		),
		reset: connect.NewClient[v1.ResetRequest, v1.ResetResponse](
			httpClient,
			baseURL+TerminalServiceResetProcedure,
			connect.WithSchema(terminalServiceMethods.ByName("Reset")),
			connect.WithClientOptions(opts...),
		),
		resetAll: connect.NewClient[v1.ResetAllRequest, v1.ResetAllResponse](
			httpClient,
			baseURL+TerminalServiceResetAllProcedure,
			connect.WithSchema(terminalServiceMethods.ByName("ResetAll")),
			connect.WithClientOptions(opts...),
		),
		killTerminalProcess: connect.NewClient[v1.KillTerminalProcessRequest, v1.KillTerminalProcessResponse](
			httpClient,
			baseURL+TerminalServiceKillTerminalProcessProcedure,
			connect.WithSchema(terminalServiceMethods.ByName("KillTerminalProcess")),
			connect.WithClientOptions(opts...),
		),
	}
}

// terminalServiceClient implements TerminalServiceClient.
type terminalServiceClient struct {
	view                *connect.Client[v1.ViewRequest, v1.ViewResponse]
	write               *connect.Client[v1.WriteRequest, v1.WriteResponse]
	reset               *connect.Client[v1.ResetRequest, v1.ResetResponse]
	resetAll            *connect.Client[v1.ResetAllRequest, v1.ResetAllResponse]
	killTerminalProcess *connect.Client[v1.KillTerminalProcessRequest, v1.KillTerminalProcessResponse]
}

// View calls runtime.v1.TerminalService.View.
func (c *terminalServiceClient) View(ctx context.Context, req *connect.Request[v1.ViewRequest]) (*connect.Response[v1.ViewResponse], error) {
	return c.view.CallUnary(ctx, req)
}

// Write calls runtime.v1.TerminalService.Write.
func (c *terminalServiceClient) Write(ctx context.Context, req *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error) {
	return c.write.CallUnary(ctx, req)
}

// Reset calls runtime.v1.TerminalService.Reset.
func (c *terminalServiceClient) Reset(ctx context.Context, req *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error) {
	return c.reset.CallUnary(ctx, req)
}

// ResetAll calls runtime.v1.TerminalService.ResetAll.
func (c *terminalServiceClient) ResetAll(ctx context.Context, req *connect.Request[v1.ResetAllRequest]) (*connect.Response[v1.ResetAllResponse], error) {
	return c.resetAll.CallUnary(ctx, req)
}

// KillTerminalProcess calls runtime.v1.TerminalService.KillTerminalProcess.
func (c *terminalServiceClient) KillTerminalProcess(ctx context.Context, req *connect.Request[v1.KillTerminalProcessRequest]) (*connect.Response[v1.KillTerminalProcessResponse], error) {
	return c.killTerminalProcess.CallUnary(ctx, req)
}

// TerminalServiceHandler is an implementation of the runtime.v1.TerminalService service.
type TerminalServiceHandler interface {
	View(context.Context, *connect.Request[v1.ViewRequest]) (*connect.Response[v1.ViewResponse], error)
	Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error)
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error)
	ResetAll(context.Context, *connect.Request[v1.ResetAllRequest]) (*connect.Response[v1.ResetAllResponse], error)
	KillTerminalProcess(context.Context, *connect.Request[v1.KillTerminalProcessRequest]) (*connect.Response[v1.KillTerminalProcessResponse], error)
}

// NewTerminalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTerminalServiceHandler(svc TerminalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	terminalServiceMethods := v1.File_runtime_v1_terminal_proto.Services().ByName("TerminalService").Methods()
	terminalServiceViewHandler := connect.NewUnaryHandler(
		TerminalServiceViewProcedure,
		svc.View,
		connect.WithSchema(terminalServiceMethods.ByName("View")),
		connect.WithHandlerOptions(opts...),
	)
	terminalServiceWriteHandler := connect.NewUnaryHandler(
		TerminalServiceWriteProcedure,
		svc.Write,
		connect.WithSchema(terminalServiceMethods.ByName("Write")),
		connect.WithHandlerOptions(opts...),
	)
	terminalServiceResetHandler := connect.NewUnaryHandler(
		TerminalServiceResetProcedure,
		svc.Reset,
		connect.WithSchema(terminalServiceMethods.ByName("Reset")),
		connect.WithHandlerOptions(opts...),
	)
	terminalServiceResetAllHandler := connect.NewUnaryHandler(
		TerminalServiceResetAllProcedure,
		svc.ResetAll,
		connect.WithSchema(terminalServiceMethods.ByName("ResetAll")),
		connect.WithHandlerOptions(opts...),
	)
	terminalServiceKillTerminalProcessHandler := connect.NewUnaryHandler(
		TerminalServiceKillTerminalProcessProcedure,
		svc.KillTerminalProcess,
		connect.WithSchema(terminalServiceMethods.ByName("KillTerminalProcess")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.TerminalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TerminalServiceViewProcedure:
			terminalServiceViewHandler.ServeHTTP(w, r)
		case TerminalServiceWriteProcedure:
			terminalServiceWriteHandler.ServeHTTP(w, r)
		case TerminalServiceResetProcedure:
			terminalServiceResetHandler.ServeHTTP(w, r)
		case TerminalServiceResetAllProcedure:
			terminalServiceResetAllHandler.ServeHTTP(w, r)
		case TerminalServiceKillTerminalProcessProcedure:
			terminalServiceKillTerminalProcessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTerminalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTerminalServiceHandler struct{}

func (UnimplementedTerminalServiceHandler) View(context.Context, *connect.Request[v1.ViewRequest]) (*connect.Response[v1.ViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TerminalService.View is not implemented"))
}

func (UnimplementedTerminalServiceHandler) Write(context.Context, *connect.Request[v1.WriteRequest]) (*connect.Response[v1.WriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TerminalService.Write is not implemented"))
}

func (UnimplementedTerminalServiceHandler) Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TerminalService.Reset is not implemented"))
}

func (UnimplementedTerminalServiceHandler) ResetAll(context.Context, *connect.Request[v1.ResetAllRequest]) (*connect.Response[v1.ResetAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TerminalService.ResetAll is not implemented"))
}

func (UnimplementedTerminalServiceHandler) KillTerminalProcess(context.Context, *connect.Request[v1.KillTerminalProcessRequest]) (*connect.Response[v1.KillTerminalProcessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TerminalService.KillTerminalProcess is not implemented"))
}
