// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runtime/v1/text_editor.proto

package runtimev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TextEditorServiceName is the fully-qualified name of the TextEditorService service.
	TextEditorServiceName = "runtime.v1.TextEditorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TextEditorServiceRunTextEditorProcedure is the fully-qualified name of the TextEditorService's
	// RunTextEditor RPC.
	TextEditorServiceRunTextEditorProcedure = "/runtime.v1.TextEditorService/RunTextEditor"
)

// TextEditorServiceClient is a client for the runtime.v1.TextEditorService service.
type TextEditorServiceClient interface {
	RunTextEditor(context.Context, *connect.Request[v1.RunTextEditorRequest]) (*connect.Response[v1.RunTextEditorResponse], error)
}

// NewTextEditorServiceClient constructs a client for the runtime.v1.TextEditorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTextEditorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TextEditorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	textEditorServiceMethods := v1.File_runtime_v1_text_editor_proto.Services().ByName("TextEditorService").Methods()
	return &textEditorServiceClient{
		runTextEditor: connect.NewClient[v1.RunTextEditorRequest, v1.RunTextEditorResponse](
			httpClient,
			baseURL+TextEditorServiceRunTextEditorProcedure,
			connect.WithSchema(textEditorServiceMethods.ByName("RunTextEditor")),
			connect.WithClientOptions(opts...),
		),
	}
}

// textEditorServiceClient implements TextEditorServiceClient.
type textEditorServiceClient struct {
	runTextEditor *connect.Client[v1.RunTextEditorRequest, v1.RunTextEditorResponse]
}

// RunTextEditor calls runtime.v1.TextEditorService.RunTextEditor.
func (c *textEditorServiceClient) RunTextEditor(ctx context.Context, req *connect.Request[v1.RunTextEditorRequest]) (*connect.Response[v1.RunTextEditorResponse], error) {
	return c.runTextEditor.CallUnary(ctx, req)
}

// TextEditorServiceHandler is an implementation of the runtime.v1.TextEditorService service.
type TextEditorServiceHandler interface {
	RunTextEditor(context.Context, *connect.Request[v1.RunTextEditorRequest]) (*connect.Response[v1.RunTextEditorResponse], error)
}

// NewTextEditorServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTextEditorServiceHandler(svc TextEditorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	textEditorServiceMethods := v1.File_runtime_v1_text_editor_proto.Services().ByName("TextEditorService").Methods()
	textEditorServiceRunTextEditorHandler := connect.NewUnaryHandler(
		TextEditorServiceRunTextEditorProcedure,
		svc.RunTextEditor,
		connect.WithSchema(textEditorServiceMethods.ByName("RunTextEditor")),
		connect.WithHandlerOptions(opts...),
	)
	return "/runtime.v1.TextEditorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TextEditorServiceRunTextEditorProcedure:
			textEditorServiceRunTextEditorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTextEditorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTextEditorServiceHandler struct{}

func (UnimplementedTextEditorServiceHandler) RunTextEditor(context.Context, *connect.Request[v1.RunTextEditorRequest]) (*connect.Response[v1.RunTextEditorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("runtime.v1.TextEditorService.RunTextEditor is not implemented"))
}
