// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/browser.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteBrowserActionRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Action                      string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                                                  // GetXxx symbol: GetAction
	CleanScreenshotPresignedUrl string                 `protobuf:"bytes,2,opt,name=clean_screenshot_presigned_url,json=cleanScreenshotPresignedUrl,proto3" json:"clean_screenshot_presigned_url,omitempty"` // GetXxx symbol: GetCleanScreenshotPresignedUrl
	CloudflareAuthHeaders       string                 `protobuf:"bytes,3,opt,name=cloudflare_auth_headers,json=cloudflareAuthHeaders,proto3" json:"cloudflare_auth_headers,omitempty"`                     // GetXxx symbol: GetCloudflareAuthHeaders
	ScreenshotPresignedUrl      string                 `protobuf:"bytes,4,opt,name=screenshot_presigned_url,json=screenshotPresignedUrl,proto3" json:"screenshot_presigned_url,omitempty"`                  // GetXxx symbol: GetScreenshotPresignedUrl
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ExecuteBrowserActionRequest) Reset() {
	*x = ExecuteBrowserActionRequest{}
	mi := &file_runtime_v1_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBrowserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBrowserActionRequest) ProtoMessage() {}

func (x *ExecuteBrowserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBrowserActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBrowserActionRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteBrowserActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteBrowserActionRequest) GetCleanScreenshotPresignedUrl() string {
	if x != nil {
		return x.CleanScreenshotPresignedUrl
	}
	return ""
}

func (x *ExecuteBrowserActionRequest) GetCloudflareAuthHeaders() string {
	if x != nil {
		return x.CloudflareAuthHeaders
	}
	return ""
}

func (x *ExecuteBrowserActionRequest) GetScreenshotPresignedUrl() string {
	if x != nil {
		return x.ScreenshotPresignedUrl
	}
	return ""
}

type ExecuteBrowserActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`   // GetXxx symbol: GetError
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // GetXxx symbol: GetResult
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBrowserActionResponse) Reset() {
	*x = ExecuteBrowserActionResponse{}
	mi := &file_runtime_v1_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBrowserActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBrowserActionResponse) ProtoMessage() {}

func (x *ExecuteBrowserActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBrowserActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBrowserActionResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteBrowserActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteBrowserActionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteBrowserActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetBrowserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserStatusRequest) Reset() {
	*x = GetBrowserStatusRequest{}
	mi := &file_runtime_v1_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserStatusRequest) ProtoMessage() {}

func (x *GetBrowserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBrowserStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{2}
}

type GetBrowserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`   // GetXxx symbol: GetError
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // GetXxx symbol: GetStatus
	Tabs          string                 `protobuf:"bytes,3,opt,name=tabs,proto3" json:"tabs,omitempty"`     // GetXxx symbol: GetTabs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrowserStatusResponse) Reset() {
	*x = GetBrowserStatusResponse{}
	mi := &file_runtime_v1_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrowserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrowserStatusResponse) ProtoMessage() {}

func (x *GetBrowserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrowserStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBrowserStatusResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{3}
}

func (x *GetBrowserStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetBrowserStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBrowserStatusResponse) GetTabs() string {
	if x != nil {
		return x.Tabs
	}
	return ""
}

type ClearBrowserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBrowserDataRequest) Reset() {
	*x = ClearBrowserDataRequest{}
	mi := &file_runtime_v1_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBrowserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBrowserDataRequest) ProtoMessage() {}

func (x *ClearBrowserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBrowserDataRequest.ProtoReflect.Descriptor instead.
func (*ClearBrowserDataRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{4}
}

type ClearBrowserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"` // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBrowserDataResponse) Reset() {
	*x = ClearBrowserDataResponse{}
	mi := &file_runtime_v1_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBrowserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBrowserDataResponse) ProtoMessage() {}

func (x *ClearBrowserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBrowserDataResponse.ProtoReflect.Descriptor instead.
func (*ClearBrowserDataResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{5}
}

func (x *ClearBrowserDataResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type NotifyBrowserConfigUpdateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EnableManusBrowser string                 `protobuf:"bytes,1,opt,name=enable_manus_browser,json=enableManusBrowser,proto3" json:"enable_manus_browser,omitempty"` // GetXxx symbol: GetEnableManusBrowser
	GetUrl             string                 `protobuf:"bytes,2,opt,name=get_url,json=getUrl,proto3" json:"get_url,omitempty"`                                       // GetXxx symbol: GetGetUrl
	PutUrl             string                 `protobuf:"bytes,3,opt,name=put_url,json=putUrl,proto3" json:"put_url,omitempty"`                                       // GetXxx symbol: GetPutUrl
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NotifyBrowserConfigUpdateRequest) Reset() {
	*x = NotifyBrowserConfigUpdateRequest{}
	mi := &file_runtime_v1_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBrowserConfigUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBrowserConfigUpdateRequest) ProtoMessage() {}

func (x *NotifyBrowserConfigUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBrowserConfigUpdateRequest.ProtoReflect.Descriptor instead.
func (*NotifyBrowserConfigUpdateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyBrowserConfigUpdateRequest) GetEnableManusBrowser() string {
	if x != nil {
		return x.EnableManusBrowser
	}
	return ""
}

func (x *NotifyBrowserConfigUpdateRequest) GetGetUrl() string {
	if x != nil {
		return x.GetUrl
	}
	return ""
}

func (x *NotifyBrowserConfigUpdateRequest) GetPutUrl() string {
	if x != nil {
		return x.PutUrl
	}
	return ""
}

type NotifyBrowserConfigUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBrowserConfigUpdateResponse) Reset() {
	*x = NotifyBrowserConfigUpdateResponse{}
	mi := &file_runtime_v1_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBrowserConfigUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBrowserConfigUpdateResponse) ProtoMessage() {}

func (x *NotifyBrowserConfigUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBrowserConfigUpdateResponse.ProtoReflect.Descriptor instead.
func (*NotifyBrowserConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyBrowserConfigUpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RenewPresignedURLsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BrowserUserDataS3Url string                 `protobuf:"bytes,1,opt,name=browser_user_data_s3_url,json=browserUserDataS3Url,proto3" json:"browser_user_data_s3_url,omitempty"` // GetXxx symbol: GetBrowserUserDataS3Url
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RenewPresignedURLsRequest) Reset() {
	*x = RenewPresignedURLsRequest{}
	mi := &file_runtime_v1_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewPresignedURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewPresignedURLsRequest) ProtoMessage() {}

func (x *RenewPresignedURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewPresignedURLsRequest.ProtoReflect.Descriptor instead.
func (*RenewPresignedURLsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{8}
}

func (x *RenewPresignedURLsRequest) GetBrowserUserDataS3Url() string {
	if x != nil {
		return x.BrowserUserDataS3Url
	}
	return ""
}

type RenewPresignedURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewPresignedURLsResponse) Reset() {
	*x = RenewPresignedURLsResponse{}
	mi := &file_runtime_v1_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewPresignedURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewPresignedURLsResponse) ProtoMessage() {}

func (x *RenewPresignedURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewPresignedURLsResponse.ProtoReflect.Descriptor instead.
func (*RenewPresignedURLsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_browser_proto_rawDescGZIP(), []int{9}
}

var File_runtime_v1_browser_proto protoreflect.FileDescriptor

const file_runtime_v1_browser_proto_rawDesc = "" +
	"\n" +
	"\x18runtime/v1/browser.proto\x12\n" +
	"runtime.v1\"\xec\x01\n" +
	"\x1bExecuteBrowserActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12C\n" +
	"\x1eclean_screenshot_presigned_url\x18\x02 \x01(\tR\x1bcleanScreenshotPresignedUrl\x126\n" +
	"\x17cloudflare_auth_headers\x18\x03 \x01(\tR\x15cloudflareAuthHeaders\x128\n" +
	"\x18screenshot_presigned_url\x18\x04 \x01(\tR\x16screenshotPresignedUrl\"d\n" +
	"\x1cExecuteBrowserActionResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x19\n" +
	"\x17GetBrowserStatusRequest\"\\\n" +
	"\x18GetBrowserStatusResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04tabs\x18\x03 \x01(\tR\x04tabs\"\x19\n" +
	"\x17ClearBrowserDataRequest\"4\n" +
	"\x18ClearBrowserDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess\"\x86\x01\n" +
	" NotifyBrowserConfigUpdateRequest\x120\n" +
	"\x14enable_manus_browser\x18\x01 \x01(\tR\x12enableManusBrowser\x12\x17\n" +
	"\aget_url\x18\x02 \x01(\tR\x06getUrl\x12\x17\n" +
	"\aput_url\x18\x03 \x01(\tR\x06putUrl\";\n" +
	"!NotifyBrowserConfigUpdateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"S\n" +
	"\x19RenewPresignedURLsRequest\x126\n" +
	"\x18browser_user_data_s3_url\x18\x01 \x01(\tR\x14browserUserDataS3Url\"\x1c\n" +
	"\x1aRenewPresignedURLsResponse2\x98\x04\n" +
	"\x0eBrowserService\x12i\n" +
	"\x14ExecuteBrowserAction\x12'.runtime.v1.ExecuteBrowserActionRequest\x1a(.runtime.v1.ExecuteBrowserActionResponse\x12]\n" +
	"\x10GetBrowserStatus\x12#.runtime.v1.GetBrowserStatusRequest\x1a$.runtime.v1.GetBrowserStatusResponse\x12]\n" +
	"\x10ClearBrowserData\x12#.runtime.v1.ClearBrowserDataRequest\x1a$.runtime.v1.ClearBrowserDataResponse\x12x\n" +
	"\x19NotifyBrowserConfigUpdate\x12,.runtime.v1.NotifyBrowserConfigUpdateRequest\x1a-.runtime.v1.NotifyBrowserConfigUpdateResponse\x12c\n" +
	"\x12RenewPresignedURLs\x12%.runtime.v1.RenewPresignedURLsRequest\x1a&.runtime.v1.RenewPresignedURLsResponseB\xcb\x01\n" +
	"\x0ecom.runtime.v1B\fBrowserProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_browser_proto_rawDescOnce sync.Once
	file_runtime_v1_browser_proto_rawDescData []byte
)

func file_runtime_v1_browser_proto_rawDescGZIP() []byte {
	file_runtime_v1_browser_proto_rawDescOnce.Do(func() {
		file_runtime_v1_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_browser_proto_rawDesc), len(file_runtime_v1_browser_proto_rawDesc)))
	})
	return file_runtime_v1_browser_proto_rawDescData
}

var file_runtime_v1_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtime_v1_browser_proto_goTypes = []any{
	(*ExecuteBrowserActionRequest)(nil),       // 0: runtime.v1.ExecuteBrowserActionRequest
	(*ExecuteBrowserActionResponse)(nil),      // 1: runtime.v1.ExecuteBrowserActionResponse
	(*GetBrowserStatusRequest)(nil),           // 2: runtime.v1.GetBrowserStatusRequest
	(*GetBrowserStatusResponse)(nil),          // 3: runtime.v1.GetBrowserStatusResponse
	(*ClearBrowserDataRequest)(nil),           // 4: runtime.v1.ClearBrowserDataRequest
	(*ClearBrowserDataResponse)(nil),          // 5: runtime.v1.ClearBrowserDataResponse
	(*NotifyBrowserConfigUpdateRequest)(nil),  // 6: runtime.v1.NotifyBrowserConfigUpdateRequest
	(*NotifyBrowserConfigUpdateResponse)(nil), // 7: runtime.v1.NotifyBrowserConfigUpdateResponse
	(*RenewPresignedURLsRequest)(nil),         // 8: runtime.v1.RenewPresignedURLsRequest
	(*RenewPresignedURLsResponse)(nil),        // 9: runtime.v1.RenewPresignedURLsResponse
}
var file_runtime_v1_browser_proto_depIdxs = []int32{
	0, // 0: runtime.v1.BrowserService.ExecuteBrowserAction:input_type -> runtime.v1.ExecuteBrowserActionRequest
	2, // 1: runtime.v1.BrowserService.GetBrowserStatus:input_type -> runtime.v1.GetBrowserStatusRequest
	4, // 2: runtime.v1.BrowserService.ClearBrowserData:input_type -> runtime.v1.ClearBrowserDataRequest
	6, // 3: runtime.v1.BrowserService.NotifyBrowserConfigUpdate:input_type -> runtime.v1.NotifyBrowserConfigUpdateRequest
	8, // 4: runtime.v1.BrowserService.RenewPresignedURLs:input_type -> runtime.v1.RenewPresignedURLsRequest
	1, // 5: runtime.v1.BrowserService.ExecuteBrowserAction:output_type -> runtime.v1.ExecuteBrowserActionResponse
	3, // 6: runtime.v1.BrowserService.GetBrowserStatus:output_type -> runtime.v1.GetBrowserStatusResponse
	5, // 7: runtime.v1.BrowserService.ClearBrowserData:output_type -> runtime.v1.ClearBrowserDataResponse
	7, // 8: runtime.v1.BrowserService.NotifyBrowserConfigUpdate:output_type -> runtime.v1.NotifyBrowserConfigUpdateResponse
	9, // 9: runtime.v1.BrowserService.RenewPresignedURLs:output_type -> runtime.v1.RenewPresignedURLsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_browser_proto_init() }
func file_runtime_v1_browser_proto_init() {
	if File_runtime_v1_browser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_browser_proto_rawDesc), len(file_runtime_v1_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_browser_proto_goTypes,
		DependencyIndexes: file_runtime_v1_browser_proto_depIdxs,
		MessageInfos:      file_runtime_v1_browser_proto_msgTypes,
	}.Build()
	File_runtime_v1_browser_proto = out.File
	file_runtime_v1_browser_proto_goTypes = nil
	file_runtime_v1_browser_proto_depIdxs = nil
}
