// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/config.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPath     string                 `protobuf:"bytes,1,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"` // GetXxx symbol: GetMountPath
	WsUrl         string                 `protobuf:"bytes,2,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`             // GetXxx symbol: GetWsUrl
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *MountRequest) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *MountRequest) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`     // GetXxx symbol: GetData
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *MountResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *MountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetEnvRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EnabledBuiltInMcp string                 `protobuf:"bytes,1,opt,name=enabled_built_in_mcp,json=enabledBuiltInMcp,proto3" json:"enabled_built_in_mcp,omitempty"` // GetXxx symbol: GetEnabledBuiltInMcp
	Secrets           string                 `protobuf:"bytes,2,opt,name=secrets,proto3" json:"secrets,omitempty"`                                                  // GetXxx symbol: GetSecrets
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetEnvRequest) Reset() {
	*x = SetEnvRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnvRequest) ProtoMessage() {}

func (x *SetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnvRequest.ProtoReflect.Descriptor instead.
func (*SetEnvRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *SetEnvRequest) GetEnabledBuiltInMcp() string {
	if x != nil {
		return x.EnabledBuiltInMcp
	}
	return ""
}

func (x *SetEnvRequest) GetSecrets() string {
	if x != nil {
		return x.Secrets
	}
	return ""
}

type SetEnvResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Configs         string                 `protobuf:"bytes,1,opt,name=configs,proto3" json:"configs,omitempty"`                                          // GetXxx symbol: GetConfigs
	GithubAuth      string                 `protobuf:"bytes,2,opt,name=github_auth,json=githubAuth,proto3" json:"github_auth,omitempty"`                  // GetXxx symbol: GetGithubAuth
	GoogleDriveAuth string                 `protobuf:"bytes,3,opt,name=google_drive_auth,json=googleDriveAuth,proto3" json:"google_drive_auth,omitempty"` // GetXxx symbol: GetGoogleDriveAuth
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                            // GetXxx symbol: GetStatus
	TotalVariables  string                 `protobuf:"bytes,5,opt,name=total_variables,json=totalVariables,proto3" json:"total_variables,omitempty"`      // GetXxx symbol: GetTotalVariables
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetEnvResponse) Reset() {
	*x = SetEnvResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnvResponse) ProtoMessage() {}

func (x *SetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnvResponse.ProtoReflect.Descriptor instead.
func (*SetEnvResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *SetEnvResponse) GetConfigs() string {
	if x != nil {
		return x.Configs
	}
	return ""
}

func (x *SetEnvResponse) GetGithubAuth() string {
	if x != nil {
		return x.GithubAuth
	}
	return ""
}

func (x *SetEnvResponse) GetGoogleDriveAuth() string {
	if x != nil {
		return x.GoogleDriveAuth
	}
	return ""
}

func (x *SetEnvResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetEnvResponse) GetTotalVariables() string {
	if x != nil {
		return x.TotalVariables
	}
	return ""
}

type GetGitHubAuthStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAuthStatusRequest) Reset() {
	*x = GetGitHubAuthStatusRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAuthStatusRequest) ProtoMessage() {}

func (x *GetGitHubAuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAuthStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGitHubAuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{4}
}

type GetGitHubAuthStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubAuth    string                 `protobuf:"bytes,1,opt,name=github_auth,json=githubAuth,proto3" json:"github_auth,omitempty"` // GetXxx symbol: GetGithubAuth
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGitHubAuthStatusResponse) Reset() {
	*x = GetGitHubAuthStatusResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGitHubAuthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGitHubAuthStatusResponse) ProtoMessage() {}

func (x *GetGitHubAuthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGitHubAuthStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGitHubAuthStatusResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *GetGitHubAuthStatusResponse) GetGithubAuth() string {
	if x != nil {
		return x.GithubAuth
	}
	return ""
}

func (x *GetGitHubAuthStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NekoPreAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NekoPreAuthRequest) Reset() {
	*x = NekoPreAuthRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NekoPreAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NekoPreAuthRequest) ProtoMessage() {}

func (x *NekoPreAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NekoPreAuthRequest.ProtoReflect.Descriptor instead.
func (*NekoPreAuthRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{6}
}

type NekoPreAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                          // GetXxx symbol: GetUsername
	WebrtcToken   string                 `protobuf:"bytes,2,opt,name=webrtc_token,json=webrtcToken,proto3" json:"webrtc_token,omitempty"` // GetXxx symbol: GetWebrtcToken
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NekoPreAuthResponse) Reset() {
	*x = NekoPreAuthResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NekoPreAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NekoPreAuthResponse) ProtoMessage() {}

func (x *NekoPreAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NekoPreAuthResponse.ProtoReflect.Descriptor instead.
func (*NekoPreAuthResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *NekoPreAuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NekoPreAuthResponse) GetWebrtcToken() string {
	if x != nil {
		return x.WebrtcToken
	}
	return ""
}

type VNCPreAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VNCPreAuthRequest) Reset() {
	*x = VNCPreAuthRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VNCPreAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VNCPreAuthRequest) ProtoMessage() {}

func (x *VNCPreAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VNCPreAuthRequest.ProtoReflect.Descriptor instead.
func (*VNCPreAuthRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{8}
}

type VNCPreAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreAuthToken  string                 `protobuf:"bytes,1,opt,name=pre_auth_token,json=preAuthToken,proto3" json:"pre_auth_token,omitempty"` // GetXxx symbol: GetPreAuthToken
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VNCPreAuthResponse) Reset() {
	*x = VNCPreAuthResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VNCPreAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VNCPreAuthResponse) ProtoMessage() {}

func (x *VNCPreAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VNCPreAuthResponse.ProtoReflect.Descriptor instead.
func (*VNCPreAuthResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *VNCPreAuthResponse) GetPreAuthToken() string {
	if x != nil {
		return x.PreAuthToken
	}
	return ""
}

type RefreshTurnTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NekoIceServersJson string                 `protobuf:"bytes,1,opt,name=neko_ice_servers_json,json=nekoIceServersJson,proto3" json:"neko_ice_servers_json,omitempty"` // GetXxx symbol: GetNekoIceServersJson
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshTurnTokenRequest) Reset() {
	*x = RefreshTurnTokenRequest{}
	mi := &file_runtime_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTurnTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTurnTokenRequest) ProtoMessage() {}

func (x *RefreshTurnTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTurnTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTurnTokenRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTurnTokenRequest) GetNekoIceServersJson() string {
	if x != nil {
		return x.NekoIceServersJson
	}
	return ""
}

type RefreshTurnTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTurnTokenResponse) Reset() {
	*x = RefreshTurnTokenResponse{}
	mi := &file_runtime_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTurnTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTurnTokenResponse) ProtoMessage() {}

func (x *RefreshTurnTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTurnTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTurnTokenResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTurnTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshTurnTokenResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_runtime_v1_config_proto protoreflect.FileDescriptor

const file_runtime_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x17runtime/v1/config.proto\x12\n" +
	"runtime.v1\"D\n" +
	"\fMountRequest\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x01 \x01(\tR\tmountPath\x12\x15\n" +
	"\x06ws_url\x18\x02 \x01(\tR\x05wsUrl\";\n" +
	"\rMountResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"Z\n" +
	"\rSetEnvRequest\x12/\n" +
	"\x14enabled_built_in_mcp\x18\x01 \x01(\tR\x11enabledBuiltInMcp\x12\x18\n" +
	"\asecrets\x18\x02 \x01(\tR\asecrets\"\xb8\x01\n" +
	"\x0eSetEnvResponse\x12\x18\n" +
	"\aconfigs\x18\x01 \x01(\tR\aconfigs\x12\x1f\n" +
	"\vgithub_auth\x18\x02 \x01(\tR\n" +
	"githubAuth\x12*\n" +
	"\x11google_drive_auth\x18\x03 \x01(\tR\x0fgoogleDriveAuth\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0ftotal_variables\x18\x05 \x01(\tR\x0etotalVariables\"\x1c\n" +
	"\x1aGetGitHubAuthStatusRequest\"V\n" +
	"\x1bGetGitHubAuthStatusResponse\x12\x1f\n" +
	"\vgithub_auth\x18\x01 \x01(\tR\n" +
	"githubAuth\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x14\n" +
	"\x12NekoPreAuthRequest\"T\n" +
	"\x13NekoPreAuthResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fwebrtc_token\x18\x02 \x01(\tR\vwebrtcToken\"\x13\n" +
	"\x11VNCPreAuthRequest\":\n" +
	"\x12VNCPreAuthResponse\x12$\n" +
	"\x0epre_auth_token\x18\x01 \x01(\tR\fpreAuthToken\"L\n" +
	"\x17RefreshTurnTokenRequest\x121\n" +
	"\x15neko_ice_servers_json\x18\x01 \x01(\tR\x12nekoIceServersJson\"L\n" +
	"\x18RefreshTurnTokenResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xf2\x03\n" +
	"\rConfigService\x12<\n" +
	"\x05Mount\x12\x18.runtime.v1.MountRequest\x1a\x19.runtime.v1.MountResponse\x12?\n" +
	"\x06SetEnv\x12\x19.runtime.v1.SetEnvRequest\x1a\x1a.runtime.v1.SetEnvResponse\x12f\n" +
	"\x13GetGitHubAuthStatus\x12&.runtime.v1.GetGitHubAuthStatusRequest\x1a'.runtime.v1.GetGitHubAuthStatusResponse\x12N\n" +
	"\vNekoPreAuth\x12\x1e.runtime.v1.NekoPreAuthRequest\x1a\x1f.runtime.v1.NekoPreAuthResponse\x12K\n" +
	"\n" +
	"VNCPreAuth\x12\x1d.runtime.v1.VNCPreAuthRequest\x1a\x1e.runtime.v1.VNCPreAuthResponse\x12]\n" +
	"\x10RefreshTurnToken\x12#.runtime.v1.RefreshTurnTokenRequest\x1a$.runtime.v1.RefreshTurnTokenResponseB\xca\x01\n" +
	"\x0ecom.runtime.v1B\vConfigProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_config_proto_rawDescOnce sync.Once
	file_runtime_v1_config_proto_rawDescData []byte
)

func file_runtime_v1_config_proto_rawDescGZIP() []byte {
	file_runtime_v1_config_proto_rawDescOnce.Do(func() {
		file_runtime_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_config_proto_rawDesc), len(file_runtime_v1_config_proto_rawDesc)))
	})
	return file_runtime_v1_config_proto_rawDescData
}

var file_runtime_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_runtime_v1_config_proto_goTypes = []any{
	(*MountRequest)(nil),                // 0: runtime.v1.MountRequest
	(*MountResponse)(nil),               // 1: runtime.v1.MountResponse
	(*SetEnvRequest)(nil),               // 2: runtime.v1.SetEnvRequest
	(*SetEnvResponse)(nil),              // 3: runtime.v1.SetEnvResponse
	(*GetGitHubAuthStatusRequest)(nil),  // 4: runtime.v1.GetGitHubAuthStatusRequest
	(*GetGitHubAuthStatusResponse)(nil), // 5: runtime.v1.GetGitHubAuthStatusResponse
	(*NekoPreAuthRequest)(nil),          // 6: runtime.v1.NekoPreAuthRequest
	(*NekoPreAuthResponse)(nil),         // 7: runtime.v1.NekoPreAuthResponse
	(*VNCPreAuthRequest)(nil),           // 8: runtime.v1.VNCPreAuthRequest
	(*VNCPreAuthResponse)(nil),          // 9: runtime.v1.VNCPreAuthResponse
	(*RefreshTurnTokenRequest)(nil),     // 10: runtime.v1.RefreshTurnTokenRequest
	(*RefreshTurnTokenResponse)(nil),    // 11: runtime.v1.RefreshTurnTokenResponse
}
var file_runtime_v1_config_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.ConfigService.Mount:input_type -> runtime.v1.MountRequest
	2,  // 1: runtime.v1.ConfigService.SetEnv:input_type -> runtime.v1.SetEnvRequest
	4,  // 2: runtime.v1.ConfigService.GetGitHubAuthStatus:input_type -> runtime.v1.GetGitHubAuthStatusRequest
	6,  // 3: runtime.v1.ConfigService.NekoPreAuth:input_type -> runtime.v1.NekoPreAuthRequest
	8,  // 4: runtime.v1.ConfigService.VNCPreAuth:input_type -> runtime.v1.VNCPreAuthRequest
	10, // 5: runtime.v1.ConfigService.RefreshTurnToken:input_type -> runtime.v1.RefreshTurnTokenRequest
	1,  // 6: runtime.v1.ConfigService.Mount:output_type -> runtime.v1.MountResponse
	3,  // 7: runtime.v1.ConfigService.SetEnv:output_type -> runtime.v1.SetEnvResponse
	5,  // 8: runtime.v1.ConfigService.GetGitHubAuthStatus:output_type -> runtime.v1.GetGitHubAuthStatusResponse
	7,  // 9: runtime.v1.ConfigService.NekoPreAuth:output_type -> runtime.v1.NekoPreAuthResponse
	9,  // 10: runtime.v1.ConfigService.VNCPreAuth:output_type -> runtime.v1.VNCPreAuthResponse
	11, // 11: runtime.v1.ConfigService.RefreshTurnToken:output_type -> runtime.v1.RefreshTurnTokenResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_config_proto_init() }
func file_runtime_v1_config_proto_init() {
	if File_runtime_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_config_proto_rawDesc), len(file_runtime_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_config_proto_goTypes,
		DependencyIndexes: file_runtime_v1_config_proto_depIdxs,
		MessageInfos:      file_runtime_v1_config_proto_msgTypes,
	}.Build()
	File_runtime_v1_config_proto = out.File
	file_runtime_v1_config_proto_goTypes = nil
	file_runtime_v1_config_proto_depIdxs = nil
}
