// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/deploy.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWebdevProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`          // GetXxx symbol: GetAppName
	Directory     string                 `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`                     // GetXxx symbol: GetDirectory
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // GetXxx symbol: GetTemplateId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebdevProjectRequest) Reset() {
	*x = CreateWebdevProjectRequest{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebdevProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebdevProjectRequest) ProtoMessage() {}

func (x *CreateWebdevProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebdevProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateWebdevProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWebdevProjectRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateWebdevProjectRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *CreateWebdevProjectRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type CreateWebdevProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                                   // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                               // GetXxx symbol: GetMessage
	ProjectPath   string                 `protobuf:"bytes,3,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`    // GetXxx symbol: GetProjectPath
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                 // GetXxx symbol: GetStatus
	TemplateUsed  string                 `protobuf:"bytes,5,opt,name=template_used,json=templateUsed,proto3" json:"template_used,omitempty"` // GetXxx symbol: GetTemplateUsed
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                               // GetXxx symbol: GetVersion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebdevProjectResponse) Reset() {
	*x = CreateWebdevProjectResponse{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebdevProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebdevProjectResponse) ProtoMessage() {}

func (x *CreateWebdevProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebdevProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateWebdevProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWebdevProjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateWebdevProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateWebdevProjectResponse) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *CreateWebdevProjectResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateWebdevProjectResponse) GetTemplateUsed() string {
	if x != nil {
		return x.TemplateUsed
	}
	return ""
}

func (x *CreateWebdevProjectResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ZipAndUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`                        // GetXxx symbol: GetDirectory
	ProjectType   string                 `protobuf:"bytes,2,opt,name=project_type,json=projectType,proto3" json:"project_type,omitempty"` // GetXxx symbol: GetProjectType
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // GetXxx symbol: GetSessionId
	UploadUrl     string                 `protobuf:"bytes,4,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`       // GetXxx symbol: GetUploadUrl
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZipAndUploadRequest) Reset() {
	*x = ZipAndUploadRequest{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZipAndUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZipAndUploadRequest) ProtoMessage() {}

func (x *ZipAndUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZipAndUploadRequest.ProtoReflect.Descriptor instead.
func (*ZipAndUploadRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *ZipAndUploadRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *ZipAndUploadRequest) GetProjectType() string {
	if x != nil {
		return x.ProjectType
	}
	return ""
}

func (x *ZipAndUploadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ZipAndUploadRequest) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type ZipAndUploadResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BranchName           string                 `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`                                 // GetXxx symbol: GetBranchName
	CommitHash           string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`                                 // GetXxx symbol: GetCommitHash
	Error                string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                                             // GetXxx symbol: GetError
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                                         // GetXxx symbol: GetMessage
	PythonNativePackages string                 `protobuf:"bytes,5,opt,name=python_native_packages,json=pythonNativePackages,proto3" json:"python_native_packages,omitempty"` // GetXxx symbol: GetPythonNativePackages
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                           // GetXxx symbol: GetStatus
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ZipAndUploadResponse) Reset() {
	*x = ZipAndUploadResponse{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZipAndUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZipAndUploadResponse) ProtoMessage() {}

func (x *ZipAndUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZipAndUploadResponse.ProtoReflect.Descriptor instead.
func (*ZipAndUploadResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *ZipAndUploadResponse) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *ZipAndUploadResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *ZipAndUploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ZipAndUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ZipAndUploadResponse) GetPythonNativePackages() string {
	if x != nil {
		return x.PythonNativePackages
	}
	return ""
}

func (x *ZipAndUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SwitchVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`                           // GetXxx symbol: GetDirectory
	TargetBranch  string                 `protobuf:"bytes,2,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"` // GetXxx symbol: GetTargetBranch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchVersionRequest) Reset() {
	*x = SwitchVersionRequest{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchVersionRequest) ProtoMessage() {}

func (x *SwitchVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchVersionRequest.ProtoReflect.Descriptor instead.
func (*SwitchVersionRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchVersionRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *SwitchVersionRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

type SwitchVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentBranch string                 `protobuf:"bytes,1,opt,name=current_branch,json=currentBranch,proto3" json:"current_branch,omitempty"` // GetXxx symbol: GetCurrentBranch
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                      // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                  // GetXxx symbol: GetMessage
	StashId       string                 `protobuf:"bytes,4,opt,name=stash_id,json=stashId,proto3" json:"stash_id,omitempty"`                   // GetXxx symbol: GetStashId
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                    // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchVersionResponse) Reset() {
	*x = SwitchVersionResponse{}
	mi := &file_runtime_v1_deploy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchVersionResponse) ProtoMessage() {}

func (x *SwitchVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_deploy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchVersionResponse.ProtoReflect.Descriptor instead.
func (*SwitchVersionResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_deploy_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchVersionResponse) GetCurrentBranch() string {
	if x != nil {
		return x.CurrentBranch
	}
	return ""
}

func (x *SwitchVersionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SwitchVersionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchVersionResponse) GetStashId() string {
	if x != nil {
		return x.StashId
	}
	return ""
}

func (x *SwitchVersionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_runtime_v1_deploy_proto protoreflect.FileDescriptor

const file_runtime_v1_deploy_proto_rawDesc = "" +
	"\n" +
	"\x17runtime/v1/deploy.proto\x12\n" +
	"runtime.v1\"v\n" +
	"\x1aCreateWebdevProjectRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1c\n" +
	"\tdirectory\x18\x02 \x01(\tR\tdirectory\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\"\xc7\x01\n" +
	"\x1bCreateWebdevProjectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fproject_path\x18\x03 \x01(\tR\vprojectPath\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rtemplate_used\x18\x05 \x01(\tR\ftemplateUsed\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\x94\x01\n" +
	"\x13ZipAndUploadRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12!\n" +
	"\fproject_type\x18\x02 \x01(\tR\vprojectType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x04 \x01(\tR\tuploadUrl\"\xd6\x01\n" +
	"\x14ZipAndUploadResponse\x12\x1f\n" +
	"\vbranch_name\x18\x01 \x01(\tR\n" +
	"branchName\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x124\n" +
	"\x16python_native_packages\x18\x05 \x01(\tR\x14pythonNativePackages\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"Y\n" +
	"\x14SwitchVersionRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12#\n" +
	"\rtarget_branch\x18\x02 \x01(\tR\ftargetBranch\"\xa1\x01\n" +
	"\x15SwitchVersionResponse\x12%\n" +
	"\x0ecurrent_branch\x18\x01 \x01(\tR\rcurrentBranch\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x19\n" +
	"\bstash_id\x18\x04 \x01(\tR\astashId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xa0\x02\n" +
	"\rDeployService\x12f\n" +
	"\x13CreateWebdevProject\x12&.runtime.v1.CreateWebdevProjectRequest\x1a'.runtime.v1.CreateWebdevProjectResponse\x12Q\n" +
	"\fZipAndUpload\x12\x1f.runtime.v1.ZipAndUploadRequest\x1a .runtime.v1.ZipAndUploadResponse\x12T\n" +
	"\rSwitchVersion\x12 .runtime.v1.SwitchVersionRequest\x1a!.runtime.v1.SwitchVersionResponseB\xca\x01\n" +
	"\x0ecom.runtime.v1B\vDeployProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_deploy_proto_rawDescOnce sync.Once
	file_runtime_v1_deploy_proto_rawDescData []byte
)

func file_runtime_v1_deploy_proto_rawDescGZIP() []byte {
	file_runtime_v1_deploy_proto_rawDescOnce.Do(func() {
		file_runtime_v1_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_deploy_proto_rawDesc), len(file_runtime_v1_deploy_proto_rawDesc)))
	})
	return file_runtime_v1_deploy_proto_rawDescData
}

var file_runtime_v1_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runtime_v1_deploy_proto_goTypes = []any{
	(*CreateWebdevProjectRequest)(nil),  // 0: runtime.v1.CreateWebdevProjectRequest
	(*CreateWebdevProjectResponse)(nil), // 1: runtime.v1.CreateWebdevProjectResponse
	(*ZipAndUploadRequest)(nil),         // 2: runtime.v1.ZipAndUploadRequest
	(*ZipAndUploadResponse)(nil),        // 3: runtime.v1.ZipAndUploadResponse
	(*SwitchVersionRequest)(nil),        // 4: runtime.v1.SwitchVersionRequest
	(*SwitchVersionResponse)(nil),       // 5: runtime.v1.SwitchVersionResponse
}
var file_runtime_v1_deploy_proto_depIdxs = []int32{
	0, // 0: runtime.v1.DeployService.CreateWebdevProject:input_type -> runtime.v1.CreateWebdevProjectRequest
	2, // 1: runtime.v1.DeployService.ZipAndUpload:input_type -> runtime.v1.ZipAndUploadRequest
	4, // 2: runtime.v1.DeployService.SwitchVersion:input_type -> runtime.v1.SwitchVersionRequest
	1, // 3: runtime.v1.DeployService.CreateWebdevProject:output_type -> runtime.v1.CreateWebdevProjectResponse
	3, // 4: runtime.v1.DeployService.ZipAndUpload:output_type -> runtime.v1.ZipAndUploadResponse
	5, // 5: runtime.v1.DeployService.SwitchVersion:output_type -> runtime.v1.SwitchVersionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_deploy_proto_init() }
func file_runtime_v1_deploy_proto_init() {
	if File_runtime_v1_deploy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_deploy_proto_rawDesc), len(file_runtime_v1_deploy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_deploy_proto_goTypes,
		DependencyIndexes: file_runtime_v1_deploy_proto_depIdxs,
		MessageInfos:      file_runtime_v1_deploy_proto_msgTypes,
	}.Build()
	File_runtime_v1_deploy_proto = out.File
	file_runtime_v1_deploy_proto_goTypes = nil
	file_runtime_v1_deploy_proto_depIdxs = nil
}
