// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/email.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadGmailAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // GetXxx symbol: GetAccessToken
	Attachments   string                 `protobuf:"bytes,2,opt,name=attachments,proto3" json:"attachments,omitempty"`                    // GetXxx symbol: GetAttachments
	MaxWorkers    string                 `protobuf:"bytes,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`    // GetXxx symbol: GetMaxWorkers
	OutputDir     string                 `protobuf:"bytes,4,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`       // GetXxx symbol: GetOutputDir
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadGmailAttachmentsRequest) Reset() {
	*x = DownloadGmailAttachmentsRequest{}
	mi := &file_runtime_v1_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadGmailAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadGmailAttachmentsRequest) ProtoMessage() {}

func (x *DownloadGmailAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadGmailAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*DownloadGmailAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadGmailAttachmentsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DownloadGmailAttachmentsRequest) GetAttachments() string {
	if x != nil {
		return x.Attachments
	}
	return ""
}

func (x *DownloadGmailAttachmentsRequest) GetMaxWorkers() string {
	if x != nil {
		return x.MaxWorkers
	}
	return ""
}

func (x *DownloadGmailAttachmentsRequest) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

type DownloadGmailAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       string                 `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`                               // GetXxx symbol: GetDetails
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                   // GetXxx symbol: GetError
	FailedCount   string                 `protobuf:"bytes,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // GetXxx symbol: GetFailedCount
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                               // GetXxx symbol: GetMessage
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                 // GetXxx symbol: GetStatus
	SuccessCount  string                 `protobuf:"bytes,6,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // GetXxx symbol: GetSuccessCount
	Total         string                 `protobuf:"bytes,7,opt,name=total,proto3" json:"total,omitempty"`                                   // GetXxx symbol: GetTotal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadGmailAttachmentsResponse) Reset() {
	*x = DownloadGmailAttachmentsResponse{}
	mi := &file_runtime_v1_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadGmailAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadGmailAttachmentsResponse) ProtoMessage() {}

func (x *DownloadGmailAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadGmailAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*DownloadGmailAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadGmailAttachmentsResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetFailedCount() string {
	if x != nil {
		return x.FailedCount
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetSuccessCount() string {
	if x != nil {
		return x.SuccessCount
	}
	return ""
}

func (x *DownloadGmailAttachmentsResponse) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type DownloadOutlookAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`    // GetXxx symbol: GetMessageId
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // GetXxx symbol: GetTargetPath
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // GetXxx symbol: GetToken
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadOutlookAttachmentsRequest) Reset() {
	*x = DownloadOutlookAttachmentsRequest{}
	mi := &file_runtime_v1_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadOutlookAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadOutlookAttachmentsRequest) ProtoMessage() {}

func (x *DownloadOutlookAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadOutlookAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*DownloadOutlookAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadOutlookAttachmentsRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DownloadOutlookAttachmentsRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *DownloadOutlookAttachmentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DownloadOutlookAttachmentsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Details         string                 `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`                                        // GetXxx symbol: GetDetails
	DownloadedFiles string                 `protobuf:"bytes,2,opt,name=downloaded_files,json=downloadedFiles,proto3" json:"downloaded_files,omitempty"` // GetXxx symbol: GetDownloadedFiles
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                            // GetXxx symbol: GetError
	FailedCount     string                 `protobuf:"bytes,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`             // GetXxx symbol: GetFailedCount
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                        // GetXxx symbol: GetMessage
	MessageId       string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                   // GetXxx symbol: GetMessageId
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                                          // GetXxx symbol: GetStatus
	SuccessCount    string                 `protobuf:"bytes,8,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`          // GetXxx symbol: GetSuccessCount
	Total           string                 `protobuf:"bytes,9,opt,name=total,proto3" json:"total,omitempty"`                                            // GetXxx symbol: GetTotal
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadOutlookAttachmentsResponse) Reset() {
	*x = DownloadOutlookAttachmentsResponse{}
	mi := &file_runtime_v1_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadOutlookAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadOutlookAttachmentsResponse) ProtoMessage() {}

func (x *DownloadOutlookAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadOutlookAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*DownloadOutlookAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadOutlookAttachmentsResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetDownloadedFiles() string {
	if x != nil {
		return x.DownloadedFiles
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetFailedCount() string {
	if x != nil {
		return x.FailedCount
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetSuccessCount() string {
	if x != nil {
		return x.SuccessCount
	}
	return ""
}

func (x *DownloadOutlookAttachmentsResponse) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type SendOrSaveGmailDraftRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`                   // GetXxx symbol: GetAccessToken
	Attachments      string                 `protobuf:"bytes,2,opt,name=attachments,proto3" json:"attachments,omitempty"`                                      // GetXxx symbol: GetAttachments
	Bcc              string                 `protobuf:"bytes,3,opt,name=bcc,proto3" json:"bcc,omitempty"`                                                      // GetXxx symbol: GetBcc
	Cc               string                 `protobuf:"bytes,4,opt,name=cc,proto3" json:"cc,omitempty"`                                                        // GetXxx symbol: GetCc
	FromEmail        string                 `protobuf:"bytes,5,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`                         // GetXxx symbol: GetFromEmail
	FromName         string                 `protobuf:"bytes,6,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`                            // GetXxx symbol: GetFromName
	ReplyTo          string                 `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`                               // GetXxx symbol: GetReplyTo
	SaveDraft        string                 `protobuf:"bytes,8,opt,name=save_draft,json=saveDraft,proto3" json:"save_draft,omitempty"`                         // GetXxx symbol: GetSaveDraft
	Subject          string                 `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`                                              // GetXxx symbol: GetSubject
	Text             string                 `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`                                                   // GetXxx symbol: GetText
	ThreadId         string                 `protobuf:"bytes,11,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`                           // GetXxx symbol: GetThreadId
	To               string                 `protobuf:"bytes,12,opt,name=to,proto3" json:"to,omitempty"`                                                       // GetXxx symbol: GetTo
	UploadChunkBytes string                 `protobuf:"bytes,13,opt,name=upload_chunk_bytes,json=uploadChunkBytes,proto3" json:"upload_chunk_bytes,omitempty"` // GetXxx symbol: GetUploadChunkBytes
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendOrSaveGmailDraftRequest) Reset() {
	*x = SendOrSaveGmailDraftRequest{}
	mi := &file_runtime_v1_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrSaveGmailDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrSaveGmailDraftRequest) ProtoMessage() {}

func (x *SendOrSaveGmailDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrSaveGmailDraftRequest.ProtoReflect.Descriptor instead.
func (*SendOrSaveGmailDraftRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{4}
}

func (x *SendOrSaveGmailDraftRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetAttachments() string {
	if x != nil {
		return x.Attachments
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetBcc() string {
	if x != nil {
		return x.Bcc
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetCc() string {
	if x != nil {
		return x.Cc
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetSaveDraft() string {
	if x != nil {
		return x.SaveDraft
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendOrSaveGmailDraftRequest) GetUploadChunkBytes() string {
	if x != nil {
		return x.UploadChunkBytes
	}
	return ""
}

type SendOrSaveGmailDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DraftId       string                 `protobuf:"bytes,1,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`             // GetXxx symbol: GetDraftId
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                // GetXxx symbol: GetError
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`                                      // GetXxx symbol: GetId
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`       // GetXxx symbol: GetMessageId
	RawResponse   string                 `protobuf:"bytes,5,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"` // GetXxx symbol: GetRawResponse
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                              // GetXxx symbol: GetStatus
	ThreadId      string                 `protobuf:"bytes,7,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`          // GetXxx symbol: GetThreadId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrSaveGmailDraftResponse) Reset() {
	*x = SendOrSaveGmailDraftResponse{}
	mi := &file_runtime_v1_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrSaveGmailDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrSaveGmailDraftResponse) ProtoMessage() {}

func (x *SendOrSaveGmailDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrSaveGmailDraftResponse.ProtoReflect.Descriptor instead.
func (*SendOrSaveGmailDraftResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{5}
}

func (x *SendOrSaveGmailDraftResponse) GetDraftId() string {
	if x != nil {
		return x.DraftId
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendOrSaveGmailDraftResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type SendOrSaveOutlookDraftRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Attachments     string                 `protobuf:"bytes,1,opt,name=attachments,proto3" json:"attachments,omitempty"`                                    // GetXxx symbol: GetAttachments
	Bcc             string                 `protobuf:"bytes,2,opt,name=bcc,proto3" json:"bcc,omitempty"`                                                    // GetXxx symbol: GetBcc
	Body            string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                                  // GetXxx symbol: GetBody
	BodyType        string                 `protobuf:"bytes,4,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`                          // GetXxx symbol: GetBodyType
	Cc              string                 `protobuf:"bytes,5,opt,name=cc,proto3" json:"cc,omitempty"`                                                      // GetXxx symbol: GetCc
	Importance      string                 `protobuf:"bytes,6,opt,name=importance,proto3" json:"importance,omitempty"`                                      // GetXxx symbol: GetImportance
	SaveToDraft     string                 `protobuf:"bytes,7,opt,name=save_to_draft,json=saveToDraft,proto3" json:"save_to_draft,omitempty"`               // GetXxx symbol: GetSaveToDraft
	SaveToSentItems string                 `protobuf:"bytes,8,opt,name=save_to_sent_items,json=saveToSentItems,proto3" json:"save_to_sent_items,omitempty"` // GetXxx symbol: GetSaveToSentItems
	Subject         string                 `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`                                            // GetXxx symbol: GetSubject
	To              string                 `protobuf:"bytes,10,opt,name=to,proto3" json:"to,omitempty"`                                                     // GetXxx symbol: GetTo
	Token           string                 `protobuf:"bytes,11,opt,name=token,proto3" json:"token,omitempty"`                                               // GetXxx symbol: GetToken
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendOrSaveOutlookDraftRequest) Reset() {
	*x = SendOrSaveOutlookDraftRequest{}
	mi := &file_runtime_v1_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrSaveOutlookDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrSaveOutlookDraftRequest) ProtoMessage() {}

func (x *SendOrSaveOutlookDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrSaveOutlookDraftRequest.ProtoReflect.Descriptor instead.
func (*SendOrSaveOutlookDraftRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{6}
}

func (x *SendOrSaveOutlookDraftRequest) GetAttachments() string {
	if x != nil {
		return x.Attachments
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetBcc() string {
	if x != nil {
		return x.Bcc
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetCc() string {
	if x != nil {
		return x.Cc
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetImportance() string {
	if x != nil {
		return x.Importance
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetSaveToDraft() string {
	if x != nil {
		return x.SaveToDraft
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetSaveToSentItems() string {
	if x != nil {
		return x.SaveToSentItems
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendOrSaveOutlookDraftRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SendOrSaveOutlookDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                          // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // GetXxx symbol: GetMessage
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // GetXxx symbol: GetMessageId
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                        // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrSaveOutlookDraftResponse) Reset() {
	*x = SendOrSaveOutlookDraftResponse{}
	mi := &file_runtime_v1_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrSaveOutlookDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrSaveOutlookDraftResponse) ProtoMessage() {}

func (x *SendOrSaveOutlookDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrSaveOutlookDraftResponse.ProtoReflect.Descriptor instead.
func (*SendOrSaveOutlookDraftResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_email_proto_rawDescGZIP(), []int{7}
}

func (x *SendOrSaveOutlookDraftResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SendOrSaveOutlookDraftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendOrSaveOutlookDraftResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendOrSaveOutlookDraftResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_runtime_v1_email_proto protoreflect.FileDescriptor

const file_runtime_v1_email_proto_rawDesc = "" +
	"\n" +
	"\x16runtime/v1/email.proto\x12\n" +
	"runtime.v1\"\xa6\x01\n" +
	"\x1fDownloadGmailAttachmentsRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12 \n" +
	"\vattachments\x18\x02 \x01(\tR\vattachments\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\tR\n" +
	"maxWorkers\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x04 \x01(\tR\toutputDir\"\xe2\x01\n" +
	" DownloadGmailAttachmentsResponse\x12\x18\n" +
	"\adetails\x18\x01 \x01(\tR\adetails\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\tR\vfailedCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rsuccess_count\x18\x06 \x01(\tR\fsuccessCount\x12\x14\n" +
	"\x05total\x18\a \x01(\tR\x05total\"y\n" +
	"!DownloadOutlookAttachmentsRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xae\x02\n" +
	"\"DownloadOutlookAttachmentsResponse\x12\x18\n" +
	"\adetails\x18\x01 \x01(\tR\adetails\x12)\n" +
	"\x10downloaded_files\x18\x02 \x01(\tR\x0fdownloadedFiles\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\tR\vfailedCount\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rsuccess_count\x18\b \x01(\tR\fsuccessCount\x12\x14\n" +
	"\x05total\x18\t \x01(\tR\x05total\"\x83\x03\n" +
	"\x1bSendOrSaveGmailDraftRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12 \n" +
	"\vattachments\x18\x02 \x01(\tR\vattachments\x12\x10\n" +
	"\x03bcc\x18\x03 \x01(\tR\x03bcc\x12\x0e\n" +
	"\x02cc\x18\x04 \x01(\tR\x02cc\x12\x1d\n" +
	"\n" +
	"from_email\x18\x05 \x01(\tR\tfromEmail\x12\x1b\n" +
	"\tfrom_name\x18\x06 \x01(\tR\bfromName\x12\x19\n" +
	"\breply_to\x18\a \x01(\tR\areplyTo\x12\x1d\n" +
	"\n" +
	"save_draft\x18\b \x01(\tR\tsaveDraft\x12\x18\n" +
	"\asubject\x18\t \x01(\tR\asubject\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x1b\n" +
	"\tthread_id\x18\v \x01(\tR\bthreadId\x12\x0e\n" +
	"\x02to\x18\f \x01(\tR\x02to\x12,\n" +
	"\x12upload_chunk_bytes\x18\r \x01(\tR\x10uploadChunkBytes\"\xd6\x01\n" +
	"\x1cSendOrSaveGmailDraftResponse\x12\x19\n" +
	"\bdraft_id\x18\x01 \x01(\tR\adraftId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12!\n" +
	"\fraw_response\x18\x05 \x01(\tR\vrawResponse\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1b\n" +
	"\tthread_id\x18\a \x01(\tR\bthreadId\"\xc5\x02\n" +
	"\x1dSendOrSaveOutlookDraftRequest\x12 \n" +
	"\vattachments\x18\x01 \x01(\tR\vattachments\x12\x10\n" +
	"\x03bcc\x18\x02 \x01(\tR\x03bcc\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1b\n" +
	"\tbody_type\x18\x04 \x01(\tR\bbodyType\x12\x0e\n" +
	"\x02cc\x18\x05 \x01(\tR\x02cc\x12\x1e\n" +
	"\n" +
	"importance\x18\x06 \x01(\tR\n" +
	"importance\x12\"\n" +
	"\rsave_to_draft\x18\a \x01(\tR\vsaveToDraft\x12+\n" +
	"\x12save_to_sent_items\x18\b \x01(\tR\x0fsaveToSentItems\x12\x18\n" +
	"\asubject\x18\t \x01(\tR\asubject\x12\x0e\n" +
	"\x02to\x18\n" +
	" \x01(\tR\x02to\x12\x14\n" +
	"\x05token\x18\v \x01(\tR\x05token\"\x87\x01\n" +
	"\x1eSendOrSaveOutlookDraftResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xde\x03\n" +
	"\fEmailService\x12u\n" +
	"\x18DownloadGmailAttachments\x12+.runtime.v1.DownloadGmailAttachmentsRequest\x1a,.runtime.v1.DownloadGmailAttachmentsResponse\x12{\n" +
	"\x1aDownloadOutlookAttachments\x12-.runtime.v1.DownloadOutlookAttachmentsRequest\x1a..runtime.v1.DownloadOutlookAttachmentsResponse\x12i\n" +
	"\x14SendOrSaveGmailDraft\x12'.runtime.v1.SendOrSaveGmailDraftRequest\x1a(.runtime.v1.SendOrSaveGmailDraftResponse\x12o\n" +
	"\x16SendOrSaveOutlookDraft\x12).runtime.v1.SendOrSaveOutlookDraftRequest\x1a*.runtime.v1.SendOrSaveOutlookDraftResponseB\xc9\x01\n" +
	"\x0ecom.runtime.v1B\n" +
	"EmailProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_email_proto_rawDescOnce sync.Once
	file_runtime_v1_email_proto_rawDescData []byte
)

func file_runtime_v1_email_proto_rawDescGZIP() []byte {
	file_runtime_v1_email_proto_rawDescOnce.Do(func() {
		file_runtime_v1_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_email_proto_rawDesc), len(file_runtime_v1_email_proto_rawDesc)))
	})
	return file_runtime_v1_email_proto_rawDescData
}

var file_runtime_v1_email_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runtime_v1_email_proto_goTypes = []any{
	(*DownloadGmailAttachmentsRequest)(nil),    // 0: runtime.v1.DownloadGmailAttachmentsRequest
	(*DownloadGmailAttachmentsResponse)(nil),   // 1: runtime.v1.DownloadGmailAttachmentsResponse
	(*DownloadOutlookAttachmentsRequest)(nil),  // 2: runtime.v1.DownloadOutlookAttachmentsRequest
	(*DownloadOutlookAttachmentsResponse)(nil), // 3: runtime.v1.DownloadOutlookAttachmentsResponse
	(*SendOrSaveGmailDraftRequest)(nil),        // 4: runtime.v1.SendOrSaveGmailDraftRequest
	(*SendOrSaveGmailDraftResponse)(nil),       // 5: runtime.v1.SendOrSaveGmailDraftResponse
	(*SendOrSaveOutlookDraftRequest)(nil),      // 6: runtime.v1.SendOrSaveOutlookDraftRequest
	(*SendOrSaveOutlookDraftResponse)(nil),     // 7: runtime.v1.SendOrSaveOutlookDraftResponse
}
var file_runtime_v1_email_proto_depIdxs = []int32{
	0, // 0: runtime.v1.EmailService.DownloadGmailAttachments:input_type -> runtime.v1.DownloadGmailAttachmentsRequest
	2, // 1: runtime.v1.EmailService.DownloadOutlookAttachments:input_type -> runtime.v1.DownloadOutlookAttachmentsRequest
	4, // 2: runtime.v1.EmailService.SendOrSaveGmailDraft:input_type -> runtime.v1.SendOrSaveGmailDraftRequest
	6, // 3: runtime.v1.EmailService.SendOrSaveOutlookDraft:input_type -> runtime.v1.SendOrSaveOutlookDraftRequest
	1, // 4: runtime.v1.EmailService.DownloadGmailAttachments:output_type -> runtime.v1.DownloadGmailAttachmentsResponse
	3, // 5: runtime.v1.EmailService.DownloadOutlookAttachments:output_type -> runtime.v1.DownloadOutlookAttachmentsResponse
	5, // 6: runtime.v1.EmailService.SendOrSaveGmailDraft:output_type -> runtime.v1.SendOrSaveGmailDraftResponse
	7, // 7: runtime.v1.EmailService.SendOrSaveOutlookDraft:output_type -> runtime.v1.SendOrSaveOutlookDraftResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_email_proto_init() }
func file_runtime_v1_email_proto_init() {
	if File_runtime_v1_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_email_proto_rawDesc), len(file_runtime_v1_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_email_proto_goTypes,
		DependencyIndexes: file_runtime_v1_email_proto_depIdxs,
		MessageInfos:      file_runtime_v1_email_proto_msgTypes,
	}.Build()
	File_runtime_v1_email_proto = out.File
	file_runtime_v1_email_proto_goTypes = nil
	file_runtime_v1_email_proto_depIdxs = nil
}
