// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/file.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // GetXxx symbol: GetPath
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // GetXxx symbol: GetContentType
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                  // GetXxx symbol: GetData
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // GetXxx symbol: GetFileName
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadFileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DownloadFileResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DownloadFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type BatchReadFilesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilePaths       string                 `protobuf:"bytes,1,opt,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"`                     // GetXxx symbol: GetFilePaths
	MaxContextChars string                 `protobuf:"bytes,2,opt,name=max_context_chars,json=maxContextChars,proto3" json:"max_context_chars,omitempty"` // GetXxx symbol: GetMaxContextChars
	MaxFiles        string                 `protobuf:"bytes,3,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`                        // GetXxx symbol: GetMaxFiles
	NoTruncate      string                 `protobuf:"bytes,4,opt,name=no_truncate,json=noTruncate,proto3" json:"no_truncate,omitempty"`                  // GetXxx symbol: GetNoTruncate
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchReadFilesRequest) Reset() {
	*x = BatchReadFilesRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReadFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReadFilesRequest) ProtoMessage() {}

func (x *BatchReadFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReadFilesRequest.ProtoReflect.Descriptor instead.
func (*BatchReadFilesRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *BatchReadFilesRequest) GetFilePaths() string {
	if x != nil {
		return x.FilePaths
	}
	return ""
}

func (x *BatchReadFilesRequest) GetMaxContextChars() string {
	if x != nil {
		return x.MaxContextChars
	}
	return ""
}

func (x *BatchReadFilesRequest) GetMaxFiles() string {
	if x != nil {
		return x.MaxFiles
	}
	return ""
}

func (x *BatchReadFilesRequest) GetNoTruncate() string {
	if x != nil {
		return x.NoTruncate
	}
	return ""
}

type BatchReadFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`                                   // GetXxx symbol: GetFiles
	FilesRead     string                 `protobuf:"bytes,2,opt,name=files_read,json=filesRead,proto3" json:"files_read,omitempty"`          // GetXxx symbol: GetFilesRead
	FilesSkipped  string                 `protobuf:"bytes,3,opt,name=files_skipped,json=filesSkipped,proto3" json:"files_skipped,omitempty"` // GetXxx symbol: GetFilesSkipped
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                 // GetXxx symbol: GetStatus
	TotalChars    string                 `protobuf:"bytes,5,opt,name=total_chars,json=totalChars,proto3" json:"total_chars,omitempty"`       // GetXxx symbol: GetTotalChars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReadFilesResponse) Reset() {
	*x = BatchReadFilesResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReadFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReadFilesResponse) ProtoMessage() {}

func (x *BatchReadFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReadFilesResponse.ProtoReflect.Descriptor instead.
func (*BatchReadFilesResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *BatchReadFilesResponse) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *BatchReadFilesResponse) GetFilesRead() string {
	if x != nil {
		return x.FilesRead
	}
	return ""
}

func (x *BatchReadFilesResponse) GetFilesSkipped() string {
	if x != nil {
		return x.FilesSkipped
	}
	return ""
}

func (x *BatchReadFilesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchReadFilesResponse) GetTotalChars() string {
	if x != nil {
		return x.TotalChars
	}
	return ""
}

type CheckFilesExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filepaths     string                 `protobuf:"bytes,1,opt,name=filepaths,proto3" json:"filepaths,omitempty"` // GetXxx symbol: GetFilepaths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFilesExistRequest) Reset() {
	*x = CheckFilesExistRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistRequest) ProtoMessage() {}

func (x *CheckFilesExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistRequest.ProtoReflect.Descriptor instead.
func (*CheckFilesExistRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFilesExistRequest) GetFilepaths() string {
	if x != nil {
		return x.Filepaths
	}
	return ""
}

type CheckFilesExistResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotFilePaths    string                 `protobuf:"bytes,1,opt,name=not_file_paths,json=notFilePaths,proto3" json:"not_file_paths,omitempty"`        // GetXxx symbol: GetNotFilePaths
	Success         string                 `protobuf:"bytes,2,opt,name=success,proto3" json:"success,omitempty"`                                        // GetXxx symbol: GetSuccess
	UnexistingPaths string                 `protobuf:"bytes,3,opt,name=unexisting_paths,json=unexistingPaths,proto3" json:"unexisting_paths,omitempty"` // GetXxx symbol: GetUnexistingPaths
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckFilesExistResponse) Reset() {
	*x = CheckFilesExistResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistResponse) ProtoMessage() {}

func (x *CheckFilesExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistResponse.ProtoReflect.Descriptor instead.
func (*CheckFilesExistResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFilesExistResponse) GetNotFilePaths() string {
	if x != nil {
		return x.NotFilePaths
	}
	return ""
}

func (x *CheckFilesExistResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *CheckFilesExistResponse) GetUnexistingPaths() string {
	if x != nil {
		return x.UnexistingPaths
	}
	return ""
}

type CheckFilesExistAbsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filepaths     string                 `protobuf:"bytes,1,opt,name=filepaths,proto3" json:"filepaths,omitempty"` // GetXxx symbol: GetFilepaths
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFilesExistAbsRequest) Reset() {
	*x = CheckFilesExistAbsRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistAbsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistAbsRequest) ProtoMessage() {}

func (x *CheckFilesExistAbsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistAbsRequest.ProtoReflect.Descriptor instead.
func (*CheckFilesExistAbsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *CheckFilesExistAbsRequest) GetFilepaths() string {
	if x != nil {
		return x.Filepaths
	}
	return ""
}

type CheckFilesExistAbsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExistingFiles   string                 `protobuf:"bytes,1,opt,name=existing_files,json=existingFiles,proto3" json:"existing_files,omitempty"`       // GetXxx symbol: GetExistingFiles
	NotFilePaths    string                 `protobuf:"bytes,2,opt,name=not_file_paths,json=notFilePaths,proto3" json:"not_file_paths,omitempty"`        // GetXxx symbol: GetNotFilePaths
	Success         string                 `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"`                                        // GetXxx symbol: GetSuccess
	UnexistingPaths string                 `protobuf:"bytes,4,opt,name=unexisting_paths,json=unexistingPaths,proto3" json:"unexisting_paths,omitempty"` // GetXxx symbol: GetUnexistingPaths
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckFilesExistAbsResponse) Reset() {
	*x = CheckFilesExistAbsResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFilesExistAbsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFilesExistAbsResponse) ProtoMessage() {}

func (x *CheckFilesExistAbsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFilesExistAbsResponse.ProtoReflect.Descriptor instead.
func (*CheckFilesExistAbsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{7}
}

func (x *CheckFilesExistAbsResponse) GetExistingFiles() string {
	if x != nil {
		return x.ExistingFiles
	}
	return ""
}

func (x *CheckFilesExistAbsResponse) GetNotFilePaths() string {
	if x != nil {
		return x.NotFilePaths
	}
	return ""
}

func (x *CheckFilesExistAbsResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *CheckFilesExistAbsResponse) GetUnexistingPaths() string {
	if x != nil {
		return x.UnexistingPaths
	}
	return ""
}

type MultipartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                // GetXxx symbol: GetFilePath
	PartSize      string                 `protobuf:"bytes,2,opt,name=part_size,json=partSize,proto3" json:"part_size,omitempty"`                // GetXxx symbol: GetPartSize
	PresignedUrls string                 `protobuf:"bytes,3,opt,name=presigned_urls,json=presignedUrls,proto3" json:"presigned_urls,omitempty"` // GetXxx symbol: GetPresignedUrls
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipartUploadRequest) Reset() {
	*x = MultipartUploadRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadRequest) ProtoMessage() {}

func (x *MultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*MultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *MultipartUploadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *MultipartUploadRequest) GetPartSize() string {
	if x != nil {
		return x.PartSize
	}
	return ""
}

func (x *MultipartUploadRequest) GetPresignedUrls() string {
	if x != nil {
		return x.PresignedUrls
	}
	return ""
}

type MultipartUploadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FailedParts     string                 `protobuf:"bytes,1,opt,name=failed_parts,json=failedParts,proto3" json:"failed_parts,omitempty"`             // GetXxx symbol: GetFailedParts
	FileName        string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                      // GetXxx symbol: GetFileName
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                        // GetXxx symbol: GetMessage
	PartsResults    string                 `protobuf:"bytes,4,opt,name=parts_results,json=partsResults,proto3" json:"parts_results,omitempty"`          // GetXxx symbol: GetPartsResults
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                          // GetXxx symbol: GetStatus
	SuccessfulParts string                 `protobuf:"bytes,6,opt,name=successful_parts,json=successfulParts,proto3" json:"successful_parts,omitempty"` // GetXxx symbol: GetSuccessfulParts
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MultipartUploadResponse) Reset() {
	*x = MultipartUploadResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadResponse) ProtoMessage() {}

func (x *MultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*MultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{9}
}

func (x *MultipartUploadResponse) GetFailedParts() string {
	if x != nil {
		return x.FailedParts
	}
	return ""
}

func (x *MultipartUploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MultipartUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MultipartUploadResponse) GetPartsResults() string {
	if x != nil {
		return x.PartsResults
	}
	return ""
}

func (x *MultipartUploadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MultipartUploadResponse) GetSuccessfulParts() string {
	if x != nil {
		return x.SuccessfulParts
	}
	return ""
}

type UploadFileToS3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // GetXxx symbol: GetFilePath
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`             // GetXxx symbol: GetFileType
	PresignedUrl  string                 `protobuf:"bytes,3,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"` // GetXxx symbol: GetPresignedUrl
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileToS3Request) Reset() {
	*x = UploadFileToS3Request{}
	mi := &file_runtime_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileToS3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileToS3Request) ProtoMessage() {}

func (x *UploadFileToS3Request) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileToS3Request.ProtoReflect.Descriptor instead.
func (*UploadFileToS3Request) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileToS3Request) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadFileToS3Request) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadFileToS3Request) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type UploadFileToS3Response struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ContentType         string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                           // GetXxx symbol: GetContentType
	EstimatedParts      string                 `protobuf:"bytes,2,opt,name=estimated_parts,json=estimatedParts,proto3" json:"estimated_parts,omitempty"`                  // GetXxx symbol: GetEstimatedParts
	FileName            string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                                    // GetXxx symbol: GetFileName
	FilePath            string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                    // GetXxx symbol: GetFilePath
	FileSize            string                 `protobuf:"bytes,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                                    // GetXxx symbol: GetFileSize
	Message             string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                                      // GetXxx symbol: GetMessage
	RecommendedPartSize string                 `protobuf:"bytes,7,opt,name=recommended_part_size,json=recommendedPartSize,proto3" json:"recommended_part_size,omitempty"` // GetXxx symbol: GetRecommendedPartSize
	RequiresMultipart   string                 `protobuf:"bytes,8,opt,name=requires_multipart,json=requiresMultipart,proto3" json:"requires_multipart,omitempty"`         // GetXxx symbol: GetRequiresMultipart
	Status              string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                                        // GetXxx symbol: GetStatus
	UploadResult        string                 `protobuf:"bytes,10,opt,name=upload_result,json=uploadResult,proto3" json:"upload_result,omitempty"`                       // GetXxx symbol: GetUploadResult
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UploadFileToS3Response) Reset() {
	*x = UploadFileToS3Response{}
	mi := &file_runtime_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileToS3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileToS3Response) ProtoMessage() {}

func (x *UploadFileToS3Response) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileToS3Response.ProtoReflect.Descriptor instead.
func (*UploadFileToS3Response) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileToS3Response) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileToS3Response) GetEstimatedParts() string {
	if x != nil {
		return x.EstimatedParts
	}
	return ""
}

func (x *UploadFileToS3Response) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileToS3Response) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadFileToS3Response) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *UploadFileToS3Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFileToS3Response) GetRecommendedPartSize() string {
	if x != nil {
		return x.RecommendedPartSize
	}
	return ""
}

func (x *UploadFileToS3Response) GetRequiresMultipart() string {
	if x != nil {
		return x.RequiresMultipart
	}
	return ""
}

func (x *UploadFileToS3Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadFileToS3Response) GetUploadResult() string {
	if x != nil {
		return x.UploadResult
	}
	return ""
}

type UploadFilesToS3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"` // GetXxx symbol: GetFiles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFilesToS3Request) Reset() {
	*x = UploadFilesToS3Request{}
	mi := &file_runtime_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFilesToS3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFilesToS3Request) ProtoMessage() {}

func (x *UploadFilesToS3Request) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFilesToS3Request.ProtoReflect.Descriptor instead.
func (*UploadFilesToS3Request) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{12}
}

func (x *UploadFilesToS3Request) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

type UploadFilesToS3Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`     // GetXxx symbol: GetFiles
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFilesToS3Response) Reset() {
	*x = UploadFilesToS3Response{}
	mi := &file_runtime_v1_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFilesToS3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFilesToS3Response) ProtoMessage() {}

func (x *UploadFilesToS3Response) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFilesToS3Response.ProtoReflect.Descriptor instead.
func (*UploadFilesToS3Response) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{13}
}

func (x *UploadFilesToS3Response) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *UploadFilesToS3Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadFilesToS3Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UploadSlideTemplateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Url         string                 `protobuf:"bytes,1,opt,name=s3_url,json=s3Url,proto3" json:"s3_url,omitempty"` // GetXxx symbol: GetS3Url
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideTemplateImageRequest) Reset() {
	*x = UploadSlideTemplateImageRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideTemplateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideTemplateImageRequest) ProtoMessage() {}

func (x *UploadSlideTemplateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideTemplateImageRequest.ProtoReflect.Descriptor instead.
func (*UploadSlideTemplateImageRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{14}
}

func (x *UploadSlideTemplateImageRequest) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

type UploadSlideTemplateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`     // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Success       string                 `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"` // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideTemplateImageResponse) Reset() {
	*x = UploadSlideTemplateImageResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideTemplateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideTemplateImageResponse) ProtoMessage() {}

func (x *UploadSlideTemplateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideTemplateImageResponse.ProtoReflect.Descriptor instead.
func (*UploadSlideTemplateImageResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{15}
}

func (x *UploadSlideTemplateImageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadSlideTemplateImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadSlideTemplateImageResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type StoreParallelTasksResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputSchema  string                 `protobuf:"bytes,1,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"` // GetXxx symbol: GetOutputSchema
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                     // GetXxx symbol: GetPath
	Tasks         string                 `protobuf:"bytes,3,opt,name=tasks,proto3" json:"tasks,omitempty"`                                   // GetXxx symbol: GetTasks
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                                   // GetXxx symbol: GetTitle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreParallelTasksResultRequest) Reset() {
	*x = StoreParallelTasksResultRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreParallelTasksResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreParallelTasksResultRequest) ProtoMessage() {}

func (x *StoreParallelTasksResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreParallelTasksResultRequest.ProtoReflect.Descriptor instead.
func (*StoreParallelTasksResultRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{16}
}

func (x *StoreParallelTasksResultRequest) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *StoreParallelTasksResultRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreParallelTasksResultRequest) GetTasks() string {
	if x != nil {
		return x.Tasks
	}
	return ""
}

func (x *StoreParallelTasksResultRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type StoreParallelTasksResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreParallelTasksResultResponse) Reset() {
	*x = StoreParallelTasksResultResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreParallelTasksResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreParallelTasksResultResponse) ProtoMessage() {}

func (x *StoreParallelTasksResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreParallelTasksResultResponse.ProtoReflect.Descriptor instead.
func (*StoreParallelTasksResultResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{17}
}

func (x *StoreParallelTasksResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StoreParallelTasksResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DownloadAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`   // GetXxx symbol: GetFiles
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"` // GetXxx symbol: GetFolder
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`     // GetXxx symbol: GetPath
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadAttachmentsRequest) Reset() {
	*x = DownloadAttachmentsRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAttachmentsRequest) ProtoMessage() {}

func (x *DownloadAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*DownloadAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadAttachmentsRequest) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

func (x *DownloadAttachmentsRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *DownloadAttachmentsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadAttachmentsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FailCount       string                 `protobuf:"bytes,1,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`                     // GetXxx symbol: GetFailCount
	Results         string                 `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`                                          // GetXxx symbol: GetResults
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                            // GetXxx symbol: GetStatus
	SuccessAbsPaths string                 `protobuf:"bytes,4,opt,name=success_abs_paths,json=successAbsPaths,proto3" json:"success_abs_paths,omitempty"` // GetXxx symbol: GetSuccessAbsPaths
	SuccessCount    string                 `protobuf:"bytes,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`            // GetXxx symbol: GetSuccessCount
	Total           string                 `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`                                              // GetXxx symbol: GetTotal
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadAttachmentsResponse) Reset() {
	*x = DownloadAttachmentsResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAttachmentsResponse) ProtoMessage() {}

func (x *DownloadAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*DownloadAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadAttachmentsResponse) GetFailCount() string {
	if x != nil {
		return x.FailCount
	}
	return ""
}

func (x *DownloadAttachmentsResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

func (x *DownloadAttachmentsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadAttachmentsResponse) GetSuccessAbsPaths() string {
	if x != nil {
		return x.SuccessAbsPaths
	}
	return ""
}

func (x *DownloadAttachmentsResponse) GetSuccessCount() string {
	if x != nil {
		return x.SuccessCount
	}
	return ""
}

func (x *DownloadAttachmentsResponse) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type DownloadUserEditedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         string                 `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"` // GetXxx symbol: GetFiles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadUserEditedRequest) Reset() {
	*x = DownloadUserEditedRequest{}
	mi := &file_runtime_v1_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUserEditedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUserEditedRequest) ProtoMessage() {}

func (x *DownloadUserEditedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUserEditedRequest.ProtoReflect.Descriptor instead.
func (*DownloadUserEditedRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{20}
}

func (x *DownloadUserEditedRequest) GetFiles() string {
	if x != nil {
		return x.Files
	}
	return ""
}

type DownloadUserEditedResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FailCount       string                 `protobuf:"bytes,1,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`                     // GetXxx symbol: GetFailCount
	Results         string                 `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`                                          // GetXxx symbol: GetResults
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                            // GetXxx symbol: GetStatus
	SuccessAbsPaths string                 `protobuf:"bytes,4,opt,name=success_abs_paths,json=successAbsPaths,proto3" json:"success_abs_paths,omitempty"` // GetXxx symbol: GetSuccessAbsPaths
	SuccessCount    string                 `protobuf:"bytes,5,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`            // GetXxx symbol: GetSuccessCount
	Total           string                 `protobuf:"bytes,6,opt,name=total,proto3" json:"total,omitempty"`                                              // GetXxx symbol: GetTotal
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadUserEditedResponse) Reset() {
	*x = DownloadUserEditedResponse{}
	mi := &file_runtime_v1_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUserEditedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUserEditedResponse) ProtoMessage() {}

func (x *DownloadUserEditedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUserEditedResponse.ProtoReflect.Descriptor instead.
func (*DownloadUserEditedResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_file_proto_rawDescGZIP(), []int{21}
}

func (x *DownloadUserEditedResponse) GetFailCount() string {
	if x != nil {
		return x.FailCount
	}
	return ""
}

func (x *DownloadUserEditedResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

func (x *DownloadUserEditedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadUserEditedResponse) GetSuccessAbsPaths() string {
	if x != nil {
		return x.SuccessAbsPaths
	}
	return ""
}

func (x *DownloadUserEditedResponse) GetSuccessCount() string {
	if x != nil {
		return x.SuccessCount
	}
	return ""
}

func (x *DownloadUserEditedResponse) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

var File_runtime_v1_file_proto protoreflect.FileDescriptor

const file_runtime_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x15runtime/v1/file.proto\x12\n" +
	"runtime.v1\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"j\n" +
	"\x14DownloadFileResponse\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"\xa0\x01\n" +
	"\x15BatchReadFilesRequest\x12\x1d\n" +
	"\n" +
	"file_paths\x18\x01 \x01(\tR\tfilePaths\x12*\n" +
	"\x11max_context_chars\x18\x02 \x01(\tR\x0fmaxContextChars\x12\x1b\n" +
	"\tmax_files\x18\x03 \x01(\tR\bmaxFiles\x12\x1f\n" +
	"\vno_truncate\x18\x04 \x01(\tR\n" +
	"noTruncate\"\xab\x01\n" +
	"\x16BatchReadFilesResponse\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\x12\x1d\n" +
	"\n" +
	"files_read\x18\x02 \x01(\tR\tfilesRead\x12#\n" +
	"\rfiles_skipped\x18\x03 \x01(\tR\ffilesSkipped\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_chars\x18\x05 \x01(\tR\n" +
	"totalChars\"6\n" +
	"\x16CheckFilesExistRequest\x12\x1c\n" +
	"\tfilepaths\x18\x01 \x01(\tR\tfilepaths\"\x84\x01\n" +
	"\x17CheckFilesExistResponse\x12$\n" +
	"\x0enot_file_paths\x18\x01 \x01(\tR\fnotFilePaths\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\tR\asuccess\x12)\n" +
	"\x10unexisting_paths\x18\x03 \x01(\tR\x0funexistingPaths\"9\n" +
	"\x19CheckFilesExistAbsRequest\x12\x1c\n" +
	"\tfilepaths\x18\x01 \x01(\tR\tfilepaths\"\xae\x01\n" +
	"\x1aCheckFilesExistAbsResponse\x12%\n" +
	"\x0eexisting_files\x18\x01 \x01(\tR\rexistingFiles\x12$\n" +
	"\x0enot_file_paths\x18\x02 \x01(\tR\fnotFilePaths\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\tR\asuccess\x12)\n" +
	"\x10unexisting_paths\x18\x04 \x01(\tR\x0funexistingPaths\"y\n" +
	"\x16MultipartUploadRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tpart_size\x18\x02 \x01(\tR\bpartSize\x12%\n" +
	"\x0epresigned_urls\x18\x03 \x01(\tR\rpresignedUrls\"\xdb\x01\n" +
	"\x17MultipartUploadResponse\x12!\n" +
	"\ffailed_parts\x18\x01 \x01(\tR\vfailedParts\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rparts_results\x18\x04 \x01(\tR\fpartsResults\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12)\n" +
	"\x10successful_parts\x18\x06 \x01(\tR\x0fsuccessfulParts\"v\n" +
	"\x15UploadFileToS3Request\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12#\n" +
	"\rpresigned_url\x18\x03 \x01(\tR\fpresignedUrl\"\xf5\x02\n" +
	"\x16UploadFileToS3Response\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12'\n" +
	"\x0festimated_parts\x18\x02 \x01(\tR\x0eestimatedParts\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\tR\bfileSize\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x122\n" +
	"\x15recommended_part_size\x18\a \x01(\tR\x13recommendedPartSize\x12-\n" +
	"\x12requires_multipart\x18\b \x01(\tR\x11requiresMultipart\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12#\n" +
	"\rupload_result\x18\n" +
	" \x01(\tR\fuploadResult\".\n" +
	"\x16UploadFilesToS3Request\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\"a\n" +
	"\x17UploadFilesToS3Response\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"8\n" +
	"\x1fUploadSlideTemplateImageRequest\x12\x15\n" +
	"\x06s3_url\x18\x01 \x01(\tR\x05s3Url\"l\n" +
	" UploadSlideTemplateImageResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\tR\asuccess\"\x86\x01\n" +
	"\x1fStoreParallelTasksResultRequest\x12#\n" +
	"\routput_schema\x18\x01 \x01(\tR\foutputSchema\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05tasks\x18\x03 \x01(\tR\x05tasks\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"T\n" +
	" StoreParallelTasksResultResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"^\n" +
	"\x1aDownloadAttachmentsRequest\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xd5\x01\n" +
	"\x1bDownloadAttachmentsResponse\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x01 \x01(\tR\tfailCount\x12\x18\n" +
	"\aresults\x18\x02 \x01(\tR\aresults\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x11success_abs_paths\x18\x04 \x01(\tR\x0fsuccessAbsPaths\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\tR\fsuccessCount\x12\x14\n" +
	"\x05total\x18\x06 \x01(\tR\x05total\"1\n" +
	"\x19DownloadUserEditedRequest\x12\x14\n" +
	"\x05files\x18\x01 \x01(\tR\x05files\"\xd4\x01\n" +
	"\x1aDownloadUserEditedResponse\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x01 \x01(\tR\tfailCount\x12\x18\n" +
	"\aresults\x18\x02 \x01(\tR\aresults\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x11success_abs_paths\x18\x04 \x01(\tR\x0fsuccessAbsPaths\x12#\n" +
	"\rsuccess_count\x18\x05 \x01(\tR\fsuccessCount\x12\x14\n" +
	"\x05total\x18\x06 \x01(\tR\x05total2\xc6\b\n" +
	"\vFileService\x12Q\n" +
	"\fDownloadFile\x12\x1f.runtime.v1.DownloadFileRequest\x1a .runtime.v1.DownloadFileResponse\x12W\n" +
	"\x0eBatchReadFiles\x12!.runtime.v1.BatchReadFilesRequest\x1a\".runtime.v1.BatchReadFilesResponse\x12Z\n" +
	"\x0fCheckFilesExist\x12\".runtime.v1.CheckFilesExistRequest\x1a#.runtime.v1.CheckFilesExistResponse\x12c\n" +
	"\x12CheckFilesExistAbs\x12%.runtime.v1.CheckFilesExistAbsRequest\x1a&.runtime.v1.CheckFilesExistAbsResponse\x12Z\n" +
	"\x0fMultipartUpload\x12\".runtime.v1.MultipartUploadRequest\x1a#.runtime.v1.MultipartUploadResponse\x12W\n" +
	"\x0eUploadFileToS3\x12!.runtime.v1.UploadFileToS3Request\x1a\".runtime.v1.UploadFileToS3Response\x12Z\n" +
	"\x0fUploadFilesToS3\x12\".runtime.v1.UploadFilesToS3Request\x1a#.runtime.v1.UploadFilesToS3Response\x12u\n" +
	"\x18UploadSlideTemplateImage\x12+.runtime.v1.UploadSlideTemplateImageRequest\x1a,.runtime.v1.UploadSlideTemplateImageResponse\x12u\n" +
	"\x18StoreParallelTasksResult\x12+.runtime.v1.StoreParallelTasksResultRequest\x1a,.runtime.v1.StoreParallelTasksResultResponse\x12f\n" +
	"\x13DownloadAttachments\x12&.runtime.v1.DownloadAttachmentsRequest\x1a'.runtime.v1.DownloadAttachmentsResponse\x12c\n" +
	"\x12DownloadUserEdited\x12%.runtime.v1.DownloadUserEditedRequest\x1a&.runtime.v1.DownloadUserEditedResponseB\xc8\x01\n" +
	"\x0ecom.runtime.v1B\tFileProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_file_proto_rawDescOnce sync.Once
	file_runtime_v1_file_proto_rawDescData []byte
)

func file_runtime_v1_file_proto_rawDescGZIP() []byte {
	file_runtime_v1_file_proto_rawDescOnce.Do(func() {
		file_runtime_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_file_proto_rawDesc), len(file_runtime_v1_file_proto_rawDesc)))
	})
	return file_runtime_v1_file_proto_rawDescData
}

var file_runtime_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_runtime_v1_file_proto_goTypes = []any{
	(*DownloadFileRequest)(nil),              // 0: runtime.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil),             // 1: runtime.v1.DownloadFileResponse
	(*BatchReadFilesRequest)(nil),            // 2: runtime.v1.BatchReadFilesRequest
	(*BatchReadFilesResponse)(nil),           // 3: runtime.v1.BatchReadFilesResponse
	(*CheckFilesExistRequest)(nil),           // 4: runtime.v1.CheckFilesExistRequest
	(*CheckFilesExistResponse)(nil),          // 5: runtime.v1.CheckFilesExistResponse
	(*CheckFilesExistAbsRequest)(nil),        // 6: runtime.v1.CheckFilesExistAbsRequest
	(*CheckFilesExistAbsResponse)(nil),       // 7: runtime.v1.CheckFilesExistAbsResponse
	(*MultipartUploadRequest)(nil),           // 8: runtime.v1.MultipartUploadRequest
	(*MultipartUploadResponse)(nil),          // 9: runtime.v1.MultipartUploadResponse
	(*UploadFileToS3Request)(nil),            // 10: runtime.v1.UploadFileToS3Request
	(*UploadFileToS3Response)(nil),           // 11: runtime.v1.UploadFileToS3Response
	(*UploadFilesToS3Request)(nil),           // 12: runtime.v1.UploadFilesToS3Request
	(*UploadFilesToS3Response)(nil),          // 13: runtime.v1.UploadFilesToS3Response
	(*UploadSlideTemplateImageRequest)(nil),  // 14: runtime.v1.UploadSlideTemplateImageRequest
	(*UploadSlideTemplateImageResponse)(nil), // 15: runtime.v1.UploadSlideTemplateImageResponse
	(*StoreParallelTasksResultRequest)(nil),  // 16: runtime.v1.StoreParallelTasksResultRequest
	(*StoreParallelTasksResultResponse)(nil), // 17: runtime.v1.StoreParallelTasksResultResponse
	(*DownloadAttachmentsRequest)(nil),       // 18: runtime.v1.DownloadAttachmentsRequest
	(*DownloadAttachmentsResponse)(nil),      // 19: runtime.v1.DownloadAttachmentsResponse
	(*DownloadUserEditedRequest)(nil),        // 20: runtime.v1.DownloadUserEditedRequest
	(*DownloadUserEditedResponse)(nil),       // 21: runtime.v1.DownloadUserEditedResponse
}
var file_runtime_v1_file_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.FileService.DownloadFile:input_type -> runtime.v1.DownloadFileRequest
	2,  // 1: runtime.v1.FileService.BatchReadFiles:input_type -> runtime.v1.BatchReadFilesRequest
	4,  // 2: runtime.v1.FileService.CheckFilesExist:input_type -> runtime.v1.CheckFilesExistRequest
	6,  // 3: runtime.v1.FileService.CheckFilesExistAbs:input_type -> runtime.v1.CheckFilesExistAbsRequest
	8,  // 4: runtime.v1.FileService.MultipartUpload:input_type -> runtime.v1.MultipartUploadRequest
	10, // 5: runtime.v1.FileService.UploadFileToS3:input_type -> runtime.v1.UploadFileToS3Request
	12, // 6: runtime.v1.FileService.UploadFilesToS3:input_type -> runtime.v1.UploadFilesToS3Request
	14, // 7: runtime.v1.FileService.UploadSlideTemplateImage:input_type -> runtime.v1.UploadSlideTemplateImageRequest
	16, // 8: runtime.v1.FileService.StoreParallelTasksResult:input_type -> runtime.v1.StoreParallelTasksResultRequest
	18, // 9: runtime.v1.FileService.DownloadAttachments:input_type -> runtime.v1.DownloadAttachmentsRequest
	20, // 10: runtime.v1.FileService.DownloadUserEdited:input_type -> runtime.v1.DownloadUserEditedRequest
	1,  // 11: runtime.v1.FileService.DownloadFile:output_type -> runtime.v1.DownloadFileResponse
	3,  // 12: runtime.v1.FileService.BatchReadFiles:output_type -> runtime.v1.BatchReadFilesResponse
	5,  // 13: runtime.v1.FileService.CheckFilesExist:output_type -> runtime.v1.CheckFilesExistResponse
	7,  // 14: runtime.v1.FileService.CheckFilesExistAbs:output_type -> runtime.v1.CheckFilesExistAbsResponse
	9,  // 15: runtime.v1.FileService.MultipartUpload:output_type -> runtime.v1.MultipartUploadResponse
	11, // 16: runtime.v1.FileService.UploadFileToS3:output_type -> runtime.v1.UploadFileToS3Response
	13, // 17: runtime.v1.FileService.UploadFilesToS3:output_type -> runtime.v1.UploadFilesToS3Response
	15, // 18: runtime.v1.FileService.UploadSlideTemplateImage:output_type -> runtime.v1.UploadSlideTemplateImageResponse
	17, // 19: runtime.v1.FileService.StoreParallelTasksResult:output_type -> runtime.v1.StoreParallelTasksResultResponse
	19, // 20: runtime.v1.FileService.DownloadAttachments:output_type -> runtime.v1.DownloadAttachmentsResponse
	21, // 21: runtime.v1.FileService.DownloadUserEdited:output_type -> runtime.v1.DownloadUserEditedResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_file_proto_init() }
func file_runtime_v1_file_proto_init() {
	if File_runtime_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_file_proto_rawDesc), len(file_runtime_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_file_proto_goTypes,
		DependencyIndexes: file_runtime_v1_file_proto_depIdxs,
		MessageInfos:      file_runtime_v1_file_proto_msgTypes,
	}.Build()
	File_runtime_v1_file_proto = out.File
	file_runtime_v1_file_proto_goTypes = nil
	file_runtime_v1_file_proto_depIdxs = nil
}
