// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/image.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveBackgroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        string                 `protobuf:"bytes,1,opt,name=images,proto3" json:"images,omitempty"` // GetXxx symbol: GetImages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBackgroundRequest) Reset() {
	*x = RemoveBackgroundRequest{}
	mi := &file_runtime_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBackgroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackgroundRequest) ProtoMessage() {}

func (x *RemoveBackgroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackgroundRequest.ProtoReflect.Descriptor instead.
func (*RemoveBackgroundRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveBackgroundRequest) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type RemoveBackgroundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Results       string                 `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"` // GetXxx symbol: GetResults
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBackgroundResponse) Reset() {
	*x = RemoveBackgroundResponse{}
	mi := &file_runtime_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBackgroundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackgroundResponse) ProtoMessage() {}

func (x *RemoveBackgroundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackgroundResponse.ProtoReflect.Descriptor instead.
func (*RemoveBackgroundResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveBackgroundResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveBackgroundResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

func (x *RemoveBackgroundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UploadSearchImageRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ImageInfoList         string                 `protobuf:"bytes,1,opt,name=image_info_list,json=imageInfoList,proto3" json:"image_info_list,omitempty"`                         // GetXxx symbol: GetImageInfoList
	NeedUploadImage       string                 `protobuf:"bytes,2,opt,name=need_upload_image,json=needUploadImage,proto3" json:"need_upload_image,omitempty"`                   // GetXxx symbol: GetNeedUploadImage
	ThumbnailImageName    string                 `protobuf:"bytes,3,opt,name=thumbnail_image_name,json=thumbnailImageName,proto3" json:"thumbnail_image_name,omitempty"`          // GetXxx symbol: GetThumbnailImageName
	ThumbnailPresignedUrl string                 `protobuf:"bytes,4,opt,name=thumbnail_presigned_url,json=thumbnailPresignedUrl,proto3" json:"thumbnail_presigned_url,omitempty"` // GetXxx symbol: GetThumbnailPresignedUrl
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UploadSearchImageRequest) Reset() {
	*x = UploadSearchImageRequest{}
	mi := &file_runtime_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSearchImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSearchImageRequest) ProtoMessage() {}

func (x *UploadSearchImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSearchImageRequest.ProtoReflect.Descriptor instead.
func (*UploadSearchImageRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_image_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSearchImageRequest) GetImageInfoList() string {
	if x != nil {
		return x.ImageInfoList
	}
	return ""
}

func (x *UploadSearchImageRequest) GetNeedUploadImage() string {
	if x != nil {
		return x.NeedUploadImage
	}
	return ""
}

func (x *UploadSearchImageRequest) GetThumbnailImageName() string {
	if x != nil {
		return x.ThumbnailImageName
	}
	return ""
}

func (x *UploadSearchImageRequest) GetThumbnailPresignedUrl() string {
	if x != nil {
		return x.ThumbnailPresignedUrl
	}
	return ""
}

type UploadSearchImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Results       string                 `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"` // GetXxx symbol: GetResults
	Success       string                 `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"` // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSearchImageResponse) Reset() {
	*x = UploadSearchImageResponse{}
	mi := &file_runtime_v1_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSearchImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSearchImageResponse) ProtoMessage() {}

func (x *UploadSearchImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSearchImageResponse.ProtoReflect.Descriptor instead.
func (*UploadSearchImageResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSearchImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadSearchImageResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

func (x *UploadSearchImageResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_runtime_v1_image_proto protoreflect.FileDescriptor

const file_runtime_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x16runtime/v1/image.proto\x12\n" +
	"runtime.v1\"1\n" +
	"\x17RemoveBackgroundRequest\x12\x16\n" +
	"\x06images\x18\x01 \x01(\tR\x06images\"f\n" +
	"\x18RemoveBackgroundResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aresults\x18\x02 \x01(\tR\aresults\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xd8\x01\n" +
	"\x18UploadSearchImageRequest\x12&\n" +
	"\x0fimage_info_list\x18\x01 \x01(\tR\rimageInfoList\x12*\n" +
	"\x11need_upload_image\x18\x02 \x01(\tR\x0fneedUploadImage\x120\n" +
	"\x14thumbnail_image_name\x18\x03 \x01(\tR\x12thumbnailImageName\x126\n" +
	"\x17thumbnail_presigned_url\x18\x04 \x01(\tR\x15thumbnailPresignedUrl\"i\n" +
	"\x19UploadSearchImageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aresults\x18\x02 \x01(\tR\aresults\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\tR\asuccess2\xcf\x01\n" +
	"\fImageService\x12]\n" +
	"\x10RemoveBackground\x12#.runtime.v1.RemoveBackgroundRequest\x1a$.runtime.v1.RemoveBackgroundResponse\x12`\n" +
	"\x11UploadSearchImage\x12$.runtime.v1.UploadSearchImageRequest\x1a%.runtime.v1.UploadSearchImageResponseB\xc9\x01\n" +
	"\x0ecom.runtime.v1B\n" +
	"ImageProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_image_proto_rawDescOnce sync.Once
	file_runtime_v1_image_proto_rawDescData []byte
)

func file_runtime_v1_image_proto_rawDescGZIP() []byte {
	file_runtime_v1_image_proto_rawDescOnce.Do(func() {
		file_runtime_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_image_proto_rawDesc), len(file_runtime_v1_image_proto_rawDesc)))
	})
	return file_runtime_v1_image_proto_rawDescData
}

var file_runtime_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_runtime_v1_image_proto_goTypes = []any{
	(*RemoveBackgroundRequest)(nil),   // 0: runtime.v1.RemoveBackgroundRequest
	(*RemoveBackgroundResponse)(nil),  // 1: runtime.v1.RemoveBackgroundResponse
	(*UploadSearchImageRequest)(nil),  // 2: runtime.v1.UploadSearchImageRequest
	(*UploadSearchImageResponse)(nil), // 3: runtime.v1.UploadSearchImageResponse
}
var file_runtime_v1_image_proto_depIdxs = []int32{
	0, // 0: runtime.v1.ImageService.RemoveBackground:input_type -> runtime.v1.RemoveBackgroundRequest
	2, // 1: runtime.v1.ImageService.UploadSearchImage:input_type -> runtime.v1.UploadSearchImageRequest
	1, // 2: runtime.v1.ImageService.RemoveBackground:output_type -> runtime.v1.RemoveBackgroundResponse
	3, // 3: runtime.v1.ImageService.UploadSearchImage:output_type -> runtime.v1.UploadSearchImageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_image_proto_init() }
func file_runtime_v1_image_proto_init() {
	if File_runtime_v1_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_image_proto_rawDesc), len(file_runtime_v1_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_image_proto_goTypes,
		DependencyIndexes: file_runtime_v1_image_proto_depIdxs,
		MessageInfos:      file_runtime_v1_image_proto_msgTypes,
	}.Build()
	File_runtime_v1_image_proto = out.File
	file_runtime_v1_image_proto_goTypes = nil
	file_runtime_v1_image_proto_depIdxs = nil
}
