// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitSandboxRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BrowserUserDataS3Url  string                 `protobuf:"bytes,1,opt,name=browser_user_data_s3_url,json=browserUserDataS3Url,proto3" json:"browser_user_data_s3_url,omitempty"`  // GetXxx symbol: GetBrowserUserDataS3Url
	EnableBrowserDataSync string                 `protobuf:"bytes,2,opt,name=enable_browser_data_sync,json=enableBrowserDataSync,proto3" json:"enable_browser_data_sync,omitempty"` // GetXxx symbol: GetEnableBrowserDataSync
	EnableGwsAudit        string                 `protobuf:"bytes,3,opt,name=enable_gws_audit,json=enableGwsAudit,proto3" json:"enable_gws_audit,omitempty"`                        // GetXxx symbol: GetEnableGwsAudit
	NekoIceServersJson    string                 `protobuf:"bytes,4,opt,name=neko_ice_servers_json,json=nekoIceServersJson,proto3" json:"neko_ice_servers_json,omitempty"`          // GetXxx symbol: GetNekoIceServersJson
	SandboxId             string                 `protobuf:"bytes,5,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`                                         // GetXxx symbol: GetSandboxId
	Secrets               string                 `protobuf:"bytes,6,opt,name=secrets,proto3" json:"secrets,omitempty"`                                                              // GetXxx symbol: GetSecrets
	SessionId             string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                         // GetXxx symbol: GetSessionId
	UtcTimestamp          string                 `protobuf:"bytes,8,opt,name=utc_timestamp,json=utcTimestamp,proto3" json:"utc_timestamp,omitempty"`                                // GetXxx symbol: GetUtcTimestamp
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitSandboxRequest) Reset() {
	*x = InitSandboxRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSandboxRequest) ProtoMessage() {}

func (x *InitSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSandboxRequest.ProtoReflect.Descriptor instead.
func (*InitSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *InitSandboxRequest) GetBrowserUserDataS3Url() string {
	if x != nil {
		return x.BrowserUserDataS3Url
	}
	return ""
}

func (x *InitSandboxRequest) GetEnableBrowserDataSync() string {
	if x != nil {
		return x.EnableBrowserDataSync
	}
	return ""
}

func (x *InitSandboxRequest) GetEnableGwsAudit() string {
	if x != nil {
		return x.EnableGwsAudit
	}
	return ""
}

func (x *InitSandboxRequest) GetNekoIceServersJson() string {
	if x != nil {
		return x.NekoIceServersJson
	}
	return ""
}

func (x *InitSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *InitSandboxRequest) GetSecrets() string {
	if x != nil {
		return x.Secrets
	}
	return ""
}

func (x *InitSandboxRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitSandboxRequest) GetUtcTimestamp() string {
	if x != nil {
		return x.UtcTimestamp
	}
	return ""
}

type InitSandboxResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedFiles string                 `protobuf:"bytes,1,opt,name=processed_files,json=processedFiles,proto3" json:"processed_files,omitempty"` // GetXxx symbol: GetProcessedFiles
	SecretsDir     string                 `protobuf:"bytes,2,opt,name=secrets_dir,json=secretsDir,proto3" json:"secrets_dir,omitempty"`             // GetXxx symbol: GetSecretsDir
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // GetXxx symbol: GetStatus
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitSandboxResponse) Reset() {
	*x = InitSandboxResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSandboxResponse) ProtoMessage() {}

func (x *InitSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSandboxResponse.ProtoReflect.Descriptor instead.
func (*InitSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *InitSandboxResponse) GetProcessedFiles() string {
	if x != nil {
		return x.ProcessedFiles
	}
	return ""
}

func (x *InitSandboxResponse) GetSecretsDir() string {
	if x != nil {
		return x.SecretsDir
	}
	return ""
}

func (x *InitSandboxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // GetXxx symbol: GetStatus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // GetXxx symbol: GetVersion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HasFuseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasFuseRequest) Reset() {
	*x = HasFuseRequest{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasFuseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasFuseRequest) ProtoMessage() {}

func (x *HasFuseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasFuseRequest.ProtoReflect.Descriptor instead.
func (*HasFuseRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

type HasFuseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevFuse       string                 `protobuf:"bytes,1,opt,name=dev_fuse,json=devFuse,proto3" json:"dev_fuse,omitempty"`    // GetXxx symbol: GetDevFuse
	HasFuse       string                 `protobuf:"bytes,2,opt,name=has_fuse,json=hasFuse,proto3" json:"has_fuse,omitempty"`    // GetXxx symbol: GetHasFuse
	MountBin      string                 `protobuf:"bytes,3,opt,name=mount_bin,json=mountBin,proto3" json:"mount_bin,omitempty"` // GetXxx symbol: GetMountBin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasFuseResponse) Reset() {
	*x = HasFuseResponse{}
	mi := &file_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasFuseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasFuseResponse) ProtoMessage() {}

func (x *HasFuseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasFuseResponse.ProtoReflect.Descriptor instead.
func (*HasFuseResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *HasFuseResponse) GetDevFuse() string {
	if x != nil {
		return x.DevFuse
	}
	return ""
}

func (x *HasFuseResponse) GetHasFuse() string {
	if x != nil {
		return x.HasFuse
	}
	return ""
}

func (x *HasFuseResponse) GetMountBin() string {
	if x != nil {
		return x.MountBin
	}
	return ""
}

var File_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x18runtime/v1/runtime.proto\x12\n" +
	"runtime.v1\"\xdf\x02\n" +
	"\x12InitSandboxRequest\x126\n" +
	"\x18browser_user_data_s3_url\x18\x01 \x01(\tR\x14browserUserDataS3Url\x127\n" +
	"\x18enable_browser_data_sync\x18\x02 \x01(\tR\x15enableBrowserDataSync\x12(\n" +
	"\x10enable_gws_audit\x18\x03 \x01(\tR\x0eenableGwsAudit\x121\n" +
	"\x15neko_ice_servers_json\x18\x04 \x01(\tR\x12nekoIceServersJson\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x05 \x01(\tR\tsandboxId\x12\x18\n" +
	"\asecrets\x18\x06 \x01(\tR\asecrets\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\x12#\n" +
	"\rutc_timestamp\x18\b \x01(\tR\futcTimestamp\"w\n" +
	"\x13InitSandboxResponse\x12'\n" +
	"\x0fprocessed_files\x18\x01 \x01(\tR\x0eprocessedFiles\x12\x1f\n" +
	"\vsecrets_dir\x18\x02 \x01(\tR\n" +
	"secretsDir\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x12\n" +
	"\x10GetHealthRequest\"+\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x10\n" +
	"\x0eHasFuseRequest\"d\n" +
	"\x0fHasFuseResponse\x12\x19\n" +
	"\bdev_fuse\x18\x01 \x01(\tR\adevFuse\x12\x19\n" +
	"\bhas_fuse\x18\x02 \x01(\tR\ahasFuse\x12\x1b\n" +
	"\tmount_bin\x18\x03 \x01(\tR\bmountBin2\xbb\x02\n" +
	"\x0eRuntimeService\x12N\n" +
	"\vInitSandbox\x12\x1e.runtime.v1.InitSandboxRequest\x1a\x1f.runtime.v1.InitSandboxResponse\x12H\n" +
	"\tGetHealth\x12\x1c.runtime.v1.GetHealthRequest\x1a\x1d.runtime.v1.GetHealthResponse\x12K\n" +
	"\n" +
	"GetVersion\x12\x1d.runtime.v1.GetVersionRequest\x1a\x1e.runtime.v1.GetVersionResponse\x12B\n" +
	"\aHasFuse\x12\x1a.runtime.v1.HasFuseRequest\x1a\x1b.runtime.v1.HasFuseResponseB\xcb\x01\n" +
	"\x0ecom.runtime.v1B\fRuntimeProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_runtime_v1_runtime_proto_rawDescData []byte
)

func file_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_runtime_proto_rawDesc), len(file_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_runtime_v1_runtime_proto_rawDescData
}

var file_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runtime_v1_runtime_proto_goTypes = []any{
	(*InitSandboxRequest)(nil),  // 0: runtime.v1.InitSandboxRequest
	(*InitSandboxResponse)(nil), // 1: runtime.v1.InitSandboxResponse
	(*GetHealthRequest)(nil),    // 2: runtime.v1.GetHealthRequest
	(*GetHealthResponse)(nil),   // 3: runtime.v1.GetHealthResponse
	(*GetVersionRequest)(nil),   // 4: runtime.v1.GetVersionRequest
	(*GetVersionResponse)(nil),  // 5: runtime.v1.GetVersionResponse
	(*HasFuseRequest)(nil),      // 6: runtime.v1.HasFuseRequest
	(*HasFuseResponse)(nil),     // 7: runtime.v1.HasFuseResponse
}
var file_runtime_v1_runtime_proto_depIdxs = []int32{
	0, // 0: runtime.v1.RuntimeService.InitSandbox:input_type -> runtime.v1.InitSandboxRequest
	2, // 1: runtime.v1.RuntimeService.GetHealth:input_type -> runtime.v1.GetHealthRequest
	4, // 2: runtime.v1.RuntimeService.GetVersion:input_type -> runtime.v1.GetVersionRequest
	6, // 3: runtime.v1.RuntimeService.HasFuse:input_type -> runtime.v1.HasFuseRequest
	1, // 4: runtime.v1.RuntimeService.InitSandbox:output_type -> runtime.v1.InitSandboxResponse
	3, // 5: runtime.v1.RuntimeService.GetHealth:output_type -> runtime.v1.GetHealthResponse
	5, // 6: runtime.v1.RuntimeService.GetVersion:output_type -> runtime.v1.GetVersionResponse
	7, // 7: runtime.v1.RuntimeService.HasFuse:output_type -> runtime.v1.HasFuseResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_runtime_proto_init() }
func file_runtime_v1_runtime_proto_init() {
	if File_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_runtime_proto_rawDesc), len(file_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_runtime_v1_runtime_proto = out.File
	file_runtime_v1_runtime_proto_goTypes = nil
	file_runtime_v1_runtime_proto_depIdxs = nil
}
