// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/skill.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillName     string                 `protobuf:"bytes,1,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"` // GetXxx symbol: GetSkillName
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageSkillRequest) Reset() {
	*x = PackageSkillRequest{}
	mi := &file_runtime_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageSkillRequest) ProtoMessage() {}

func (x *PackageSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageSkillRequest.ProtoReflect.Descriptor instead.
func (*PackageSkillRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_skill_proto_rawDescGZIP(), []int{0}
}

func (x *PackageSkillRequest) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

type PackageSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageSkillResponse) Reset() {
	*x = PackageSkillResponse{}
	mi := &file_runtime_v1_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageSkillResponse) ProtoMessage() {}

func (x *PackageSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageSkillResponse.ProtoReflect.Descriptor instead.
func (*PackageSkillResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_skill_proto_rawDescGZIP(), []int{1}
}

func (x *PackageSkillResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SyncSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillsInfo    string                 `protobuf:"bytes,1,opt,name=skills_info,json=skillsInfo,proto3" json:"skills_info,omitempty"` // GetXxx symbol: GetSkillsInfo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSkillsRequest) Reset() {
	*x = SyncSkillsRequest{}
	mi := &file_runtime_v1_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSkillsRequest) ProtoMessage() {}

func (x *SyncSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSkillsRequest.ProtoReflect.Descriptor instead.
func (*SyncSkillsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_skill_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSkillsRequest) GetSkillsInfo() string {
	if x != nil {
		return x.SkillsInfo
	}
	return ""
}

type SyncSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSkillsResponse) Reset() {
	*x = SyncSkillsResponse{}
	mi := &file_runtime_v1_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSkillsResponse) ProtoMessage() {}

func (x *SyncSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSkillsResponse.ProtoReflect.Descriptor instead.
func (*SyncSkillsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_skill_proto_rawDescGZIP(), []int{3}
}

func (x *SyncSkillsResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_runtime_v1_skill_proto protoreflect.FileDescriptor

const file_runtime_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x16runtime/v1/skill.proto\x12\n" +
	"runtime.v1\"4\n" +
	"\x13PackageSkillRequest\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x01 \x01(\tR\tskillName\"*\n" +
	"\x14PackageSkillResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"4\n" +
	"\x11SyncSkillsRequest\x12\x1f\n" +
	"\vskills_info\x18\x01 \x01(\tR\n" +
	"skillsInfo\"(\n" +
	"\x12SyncSkillsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\xae\x01\n" +
	"\fSkillService\x12Q\n" +
	"\fPackageSkill\x12\x1f.runtime.v1.PackageSkillRequest\x1a .runtime.v1.PackageSkillResponse\x12K\n" +
	"\n" +
	"SyncSkills\x12\x1d.runtime.v1.SyncSkillsRequest\x1a\x1e.runtime.v1.SyncSkillsResponseB\xc9\x01\n" +
	"\x0ecom.runtime.v1B\n" +
	"SkillProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_skill_proto_rawDescOnce sync.Once
	file_runtime_v1_skill_proto_rawDescData []byte
)

func file_runtime_v1_skill_proto_rawDescGZIP() []byte {
	file_runtime_v1_skill_proto_rawDescOnce.Do(func() {
		file_runtime_v1_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_skill_proto_rawDesc), len(file_runtime_v1_skill_proto_rawDesc)))
	})
	return file_runtime_v1_skill_proto_rawDescData
}

var file_runtime_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_runtime_v1_skill_proto_goTypes = []any{
	(*PackageSkillRequest)(nil),  // 0: runtime.v1.PackageSkillRequest
	(*PackageSkillResponse)(nil), // 1: runtime.v1.PackageSkillResponse
	(*SyncSkillsRequest)(nil),    // 2: runtime.v1.SyncSkillsRequest
	(*SyncSkillsResponse)(nil),   // 3: runtime.v1.SyncSkillsResponse
}
var file_runtime_v1_skill_proto_depIdxs = []int32{
	0, // 0: runtime.v1.SkillService.PackageSkill:input_type -> runtime.v1.PackageSkillRequest
	2, // 1: runtime.v1.SkillService.SyncSkills:input_type -> runtime.v1.SyncSkillsRequest
	1, // 2: runtime.v1.SkillService.PackageSkill:output_type -> runtime.v1.PackageSkillResponse
	3, // 3: runtime.v1.SkillService.SyncSkills:output_type -> runtime.v1.SyncSkillsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_skill_proto_init() }
func file_runtime_v1_skill_proto_init() {
	if File_runtime_v1_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_skill_proto_rawDesc), len(file_runtime_v1_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_skill_proto_goTypes,
		DependencyIndexes: file_runtime_v1_skill_proto_depIdxs,
		MessageInfos:      file_runtime_v1_skill_proto_msgTypes,
	}.Build()
	File_runtime_v1_skill_proto = out.File
	file_runtime_v1_skill_proto_goTypes = nil
	file_runtime_v1_skill_proto_depIdxs = nil
}
