// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/slide.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitSlideProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`                  // GetXxx symbol: GetDirectory
	MainTitle     string                 `protobuf:"bytes,2,opt,name=main_title,json=mainTitle,proto3" json:"main_title,omitempty"` // GetXxx symbol: GetMainTitle
	Outline       string                 `protobuf:"bytes,3,opt,name=outline,proto3" json:"outline,omitempty"`                      // GetXxx symbol: GetOutline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSlideProjectRequest) Reset() {
	*x = InitSlideProjectRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSlideProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSlideProjectRequest) ProtoMessage() {}

func (x *InitSlideProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSlideProjectRequest.ProtoReflect.Descriptor instead.
func (*InitSlideProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{0}
}

func (x *InitSlideProjectRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *InitSlideProjectRequest) GetMainTitle() string {
	if x != nil {
		return x.MainTitle
	}
	return ""
}

func (x *InitSlideProjectRequest) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

type InitSlideProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`     // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Success       string                 `protobuf:"bytes,3,opt,name=success,proto3" json:"success,omitempty"` // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSlideProjectResponse) Reset() {
	*x = InitSlideProjectResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSlideProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSlideProjectResponse) ProtoMessage() {}

func (x *InitSlideProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSlideProjectResponse.ProtoReflect.Descriptor instead.
func (*InitSlideProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{1}
}

func (x *InitSlideProjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitSlideProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitSlideProjectResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type ModifySlideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`                     // GetXxx symbol: GetOperation
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"` // GetXxx symbol: GetProjectDir
	SlideData     string                 `protobuf:"bytes,3,opt,name=slide_data,json=slideData,proto3" json:"slide_data,omitempty"`    // GetXxx symbol: GetSlideData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifySlideRequest) Reset() {
	*x = ModifySlideRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySlideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySlideRequest) ProtoMessage() {}

func (x *ModifySlideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySlideRequest.ProtoReflect.Descriptor instead.
func (*ModifySlideRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{2}
}

func (x *ModifySlideRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ModifySlideRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *ModifySlideRequest) GetSlideData() string {
	if x != nil {
		return x.SlideData
	}
	return ""
}

type ModifySlideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`     // GetXxx symbol: GetError
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // GetXxx symbol: GetMessage
	Outline       string                 `protobuf:"bytes,3,opt,name=outline,proto3" json:"outline,omitempty"` // GetXxx symbol: GetOutline
	Results       string                 `protobuf:"bytes,4,opt,name=results,proto3" json:"results,omitempty"` // GetXxx symbol: GetResults
	Success       string                 `protobuf:"bytes,5,opt,name=success,proto3" json:"success,omitempty"` // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifySlideResponse) Reset() {
	*x = ModifySlideResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifySlideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifySlideResponse) ProtoMessage() {}

func (x *ModifySlideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifySlideResponse.ProtoReflect.Descriptor instead.
func (*ModifySlideResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{3}
}

func (x *ModifySlideResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ModifySlideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ModifySlideResponse) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *ModifySlideResponse) GetResults() string {
	if x != nil {
		return x.Results
	}
	return ""
}

func (x *ModifySlideResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type PresentSlideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`                                // GetXxx symbol: GetDirectory
	NotesFilePath string                 `protobuf:"bytes,2,opt,name=notes_file_path,json=notesFilePath,proto3" json:"notes_file_path,omitempty"` // GetXxx symbol: GetNotesFilePath
	Outline       string                 `protobuf:"bytes,3,opt,name=outline,proto3" json:"outline,omitempty"`                                    // GetXxx symbol: GetOutline
	S3Url         string                 `protobuf:"bytes,4,opt,name=s3_url,json=s3Url,proto3" json:"s3_url,omitempty"`                           // GetXxx symbol: GetS3Url
	SlideIds      string                 `protobuf:"bytes,5,opt,name=slide_ids,json=slideIds,proto3" json:"slide_ids,omitempty"`                  // GetXxx symbol: GetSlideIds
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`                                        // GetXxx symbol: GetTitle
	VersionId     string                 `protobuf:"bytes,7,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`               // GetXxx symbol: GetVersionId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentSlideRequest) Reset() {
	*x = PresentSlideRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentSlideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentSlideRequest) ProtoMessage() {}

func (x *PresentSlideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentSlideRequest.ProtoReflect.Descriptor instead.
func (*PresentSlideRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{4}
}

func (x *PresentSlideRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *PresentSlideRequest) GetNotesFilePath() string {
	if x != nil {
		return x.NotesFilePath
	}
	return ""
}

func (x *PresentSlideRequest) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *PresentSlideRequest) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

func (x *PresentSlideRequest) GetSlideIds() string {
	if x != nil {
		return x.SlideIds
	}
	return ""
}

func (x *PresentSlideRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PresentSlideRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type PresentSlideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                       // GetXxx symbol: GetError
	JsonData      string                 `protobuf:"bytes,2,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"` // GetXxx symbol: GetJsonData
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                   // GetXxx symbol: GetMessage
	Success       string                 `protobuf:"bytes,4,opt,name=success,proto3" json:"success,omitempty"`                   // GetXxx symbol: GetSuccess
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresentSlideResponse) Reset() {
	*x = PresentSlideResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresentSlideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresentSlideResponse) ProtoMessage() {}

func (x *PresentSlideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresentSlideResponse.ProtoReflect.Descriptor instead.
func (*PresentSlideResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{5}
}

func (x *PresentSlideResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PresentSlideResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *PresentSlideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PresentSlideResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type FetchSlideNotesRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NotesFilePath        string                 `protobuf:"bytes,1,opt,name=notes_file_path,json=notesFilePath,proto3" json:"notes_file_path,omitempty"`                        // GetXxx symbol: GetNotesFilePath
	Outline              string                 `protobuf:"bytes,2,opt,name=outline,proto3" json:"outline,omitempty"`                                                           // GetXxx symbol: GetOutline
	ProjectDir           string                 `protobuf:"bytes,3,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`                                   // GetXxx symbol: GetProjectDir
	SlideContentFilePath string                 `protobuf:"bytes,4,opt,name=slide_content_file_path,json=slideContentFilePath,proto3" json:"slide_content_file_path,omitempty"` // GetXxx symbol: GetSlideContentFilePath
	SlideIndexes         string                 `protobuf:"bytes,5,opt,name=slide_indexes,json=slideIndexes,proto3" json:"slide_indexes,omitempty"`                             // GetXxx symbol: GetSlideIndexes
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FetchSlideNotesRequest) Reset() {
	*x = FetchSlideNotesRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSlideNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSlideNotesRequest) ProtoMessage() {}

func (x *FetchSlideNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSlideNotesRequest.ProtoReflect.Descriptor instead.
func (*FetchSlideNotesRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{6}
}

func (x *FetchSlideNotesRequest) GetNotesFilePath() string {
	if x != nil {
		return x.NotesFilePath
	}
	return ""
}

func (x *FetchSlideNotesRequest) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *FetchSlideNotesRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *FetchSlideNotesRequest) GetSlideContentFilePath() string {
	if x != nil {
		return x.SlideContentFilePath
	}
	return ""
}

func (x *FetchSlideNotesRequest) GetSlideIndexes() string {
	if x != nil {
		return x.SlideIndexes
	}
	return ""
}

type FetchSlideNotesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Error                string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                                                             // GetXxx symbol: GetError
	ExistingNotes        string                 `protobuf:"bytes,2,opt,name=existing_notes,json=existingNotes,proto3" json:"existing_notes,omitempty"`                        // GetXxx symbol: GetExistingNotes
	SlideContentMarkdown string                 `protobuf:"bytes,3,opt,name=slide_content_markdown,json=slideContentMarkdown,proto3" json:"slide_content_markdown,omitempty"` // GetXxx symbol: GetSlideContentMarkdown
	Slides               string                 `protobuf:"bytes,4,opt,name=slides,proto3" json:"slides,omitempty"`                                                           // GetXxx symbol: GetSlides
	Success              string                 `protobuf:"bytes,5,opt,name=success,proto3" json:"success,omitempty"`                                                         // GetXxx symbol: GetSuccess
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FetchSlideNotesResponse) Reset() {
	*x = FetchSlideNotesResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSlideNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSlideNotesResponse) ProtoMessage() {}

func (x *FetchSlideNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSlideNotesResponse.ProtoReflect.Descriptor instead.
func (*FetchSlideNotesResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{7}
}

func (x *FetchSlideNotesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchSlideNotesResponse) GetExistingNotes() string {
	if x != nil {
		return x.ExistingNotes
	}
	return ""
}

func (x *FetchSlideNotesResponse) GetSlideContentMarkdown() string {
	if x != nil {
		return x.SlideContentMarkdown
	}
	return ""
}

func (x *FetchSlideNotesResponse) GetSlides() string {
	if x != nil {
		return x.Slides
	}
	return ""
}

func (x *FetchSlideNotesResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type UpdateSlideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSlideRequest) Reset() {
	*x = UpdateSlideRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSlideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlideRequest) ProtoMessage() {}

func (x *UpdateSlideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlideRequest.ProtoReflect.Descriptor instead.
func (*UpdateSlideRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{8}
}

type UpdateSlideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSlideResponse) Reset() {
	*x = UpdateSlideResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSlideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSlideResponse) ProtoMessage() {}

func (x *UpdateSlideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSlideResponse.ProtoReflect.Descriptor instead.
func (*UpdateSlideResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{9}
}

type UploadSlideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideRequest) Reset() {
	*x = UploadSlideRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideRequest) ProtoMessage() {}

func (x *UploadSlideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideRequest.ProtoReflect.Descriptor instead.
func (*UploadSlideRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{10}
}

type UploadSlideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideResponse) Reset() {
	*x = UploadSlideResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideResponse) ProtoMessage() {}

func (x *UploadSlideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideResponse.ProtoReflect.Descriptor instead.
func (*UploadSlideResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{11}
}

type UploadSlideTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideTemplateRequest) Reset() {
	*x = UploadSlideTemplateRequest{}
	mi := &file_runtime_v1_slide_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideTemplateRequest) ProtoMessage() {}

func (x *UploadSlideTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideTemplateRequest.ProtoReflect.Descriptor instead.
func (*UploadSlideTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{12}
}

type UploadSlideTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSlideTemplateResponse) Reset() {
	*x = UploadSlideTemplateResponse{}
	mi := &file_runtime_v1_slide_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSlideTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSlideTemplateResponse) ProtoMessage() {}

func (x *UploadSlideTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_slide_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSlideTemplateResponse.ProtoReflect.Descriptor instead.
func (*UploadSlideTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_slide_proto_rawDescGZIP(), []int{13}
}

var File_runtime_v1_slide_proto protoreflect.FileDescriptor

const file_runtime_v1_slide_proto_rawDesc = "" +
	"\n" +
	"\x16runtime/v1/slide.proto\x12\n" +
	"runtime.v1\"p\n" +
	"\x17InitSlideProjectRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x1d\n" +
	"\n" +
	"main_title\x18\x02 \x01(\tR\tmainTitle\x12\x18\n" +
	"\aoutline\x18\x03 \x01(\tR\aoutline\"d\n" +
	"\x18InitSlideProjectResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\tR\asuccess\"r\n" +
	"\x12ModifySlideRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x1d\n" +
	"\n" +
	"slide_data\x18\x03 \x01(\tR\tslideData\"\x93\x01\n" +
	"\x13ModifySlideResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aoutline\x18\x03 \x01(\tR\aoutline\x12\x18\n" +
	"\aresults\x18\x04 \x01(\tR\aresults\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\tR\asuccess\"\xde\x01\n" +
	"\x13PresentSlideRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12&\n" +
	"\x0fnotes_file_path\x18\x02 \x01(\tR\rnotesFilePath\x12\x18\n" +
	"\aoutline\x18\x03 \x01(\tR\aoutline\x12\x15\n" +
	"\x06s3_url\x18\x04 \x01(\tR\x05s3Url\x12\x1b\n" +
	"\tslide_ids\x18\x05 \x01(\tR\bslideIds\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"version_id\x18\a \x01(\tR\tversionId\"}\n" +
	"\x14PresentSlideResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1b\n" +
	"\tjson_data\x18\x02 \x01(\tR\bjsonData\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\tR\asuccess\"\xd7\x01\n" +
	"\x16FetchSlideNotesRequest\x12&\n" +
	"\x0fnotes_file_path\x18\x01 \x01(\tR\rnotesFilePath\x12\x18\n" +
	"\aoutline\x18\x02 \x01(\tR\aoutline\x12\x1f\n" +
	"\vproject_dir\x18\x03 \x01(\tR\n" +
	"projectDir\x125\n" +
	"\x17slide_content_file_path\x18\x04 \x01(\tR\x14slideContentFilePath\x12#\n" +
	"\rslide_indexes\x18\x05 \x01(\tR\fslideIndexes\"\xbe\x01\n" +
	"\x17FetchSlideNotesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12%\n" +
	"\x0eexisting_notes\x18\x02 \x01(\tR\rexistingNotes\x124\n" +
	"\x16slide_content_markdown\x18\x03 \x01(\tR\x14slideContentMarkdown\x12\x16\n" +
	"\x06slides\x18\x04 \x01(\tR\x06slides\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\tR\asuccess\"\x14\n" +
	"\x12UpdateSlideRequest\"\x15\n" +
	"\x13UpdateSlideResponse\"\x14\n" +
	"\x12UploadSlideRequest\"\x15\n" +
	"\x13UploadSlideResponse\"\x1c\n" +
	"\x1aUploadSlideTemplateRequest\"\x1d\n" +
	"\x1bUploadSlideTemplateResponse2\xf4\x04\n" +
	"\fSlideService\x12]\n" +
	"\x10InitSlideProject\x12#.runtime.v1.InitSlideProjectRequest\x1a$.runtime.v1.InitSlideProjectResponse\x12N\n" +
	"\vModifySlide\x12\x1e.runtime.v1.ModifySlideRequest\x1a\x1f.runtime.v1.ModifySlideResponse\x12Q\n" +
	"\fPresentSlide\x12\x1f.runtime.v1.PresentSlideRequest\x1a .runtime.v1.PresentSlideResponse\x12Z\n" +
	"\x0fFetchSlideNotes\x12\".runtime.v1.FetchSlideNotesRequest\x1a#.runtime.v1.FetchSlideNotesResponse\x12N\n" +
	"\vUpdateSlide\x12\x1e.runtime.v1.UpdateSlideRequest\x1a\x1f.runtime.v1.UpdateSlideResponse\x12N\n" +
	"\vUploadSlide\x12\x1e.runtime.v1.UploadSlideRequest\x1a\x1f.runtime.v1.UploadSlideResponse\x12f\n" +
	"\x13UploadSlideTemplate\x12&.runtime.v1.UploadSlideTemplateRequest\x1a'.runtime.v1.UploadSlideTemplateResponseB\xc9\x01\n" +
	"\x0ecom.runtime.v1B\n" +
	"SlideProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_slide_proto_rawDescOnce sync.Once
	file_runtime_v1_slide_proto_rawDescData []byte
)

func file_runtime_v1_slide_proto_rawDescGZIP() []byte {
	file_runtime_v1_slide_proto_rawDescOnce.Do(func() {
		file_runtime_v1_slide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_slide_proto_rawDesc), len(file_runtime_v1_slide_proto_rawDesc)))
	})
	return file_runtime_v1_slide_proto_rawDescData
}

var file_runtime_v1_slide_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_runtime_v1_slide_proto_goTypes = []any{
	(*InitSlideProjectRequest)(nil),     // 0: runtime.v1.InitSlideProjectRequest
	(*InitSlideProjectResponse)(nil),    // 1: runtime.v1.InitSlideProjectResponse
	(*ModifySlideRequest)(nil),          // 2: runtime.v1.ModifySlideRequest
	(*ModifySlideResponse)(nil),         // 3: runtime.v1.ModifySlideResponse
	(*PresentSlideRequest)(nil),         // 4: runtime.v1.PresentSlideRequest
	(*PresentSlideResponse)(nil),        // 5: runtime.v1.PresentSlideResponse
	(*FetchSlideNotesRequest)(nil),      // 6: runtime.v1.FetchSlideNotesRequest
	(*FetchSlideNotesResponse)(nil),     // 7: runtime.v1.FetchSlideNotesResponse
	(*UpdateSlideRequest)(nil),          // 8: runtime.v1.UpdateSlideRequest
	(*UpdateSlideResponse)(nil),         // 9: runtime.v1.UpdateSlideResponse
	(*UploadSlideRequest)(nil),          // 10: runtime.v1.UploadSlideRequest
	(*UploadSlideResponse)(nil),         // 11: runtime.v1.UploadSlideResponse
	(*UploadSlideTemplateRequest)(nil),  // 12: runtime.v1.UploadSlideTemplateRequest
	(*UploadSlideTemplateResponse)(nil), // 13: runtime.v1.UploadSlideTemplateResponse
}
var file_runtime_v1_slide_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.SlideService.InitSlideProject:input_type -> runtime.v1.InitSlideProjectRequest
	2,  // 1: runtime.v1.SlideService.ModifySlide:input_type -> runtime.v1.ModifySlideRequest
	4,  // 2: runtime.v1.SlideService.PresentSlide:input_type -> runtime.v1.PresentSlideRequest
	6,  // 3: runtime.v1.SlideService.FetchSlideNotes:input_type -> runtime.v1.FetchSlideNotesRequest
	8,  // 4: runtime.v1.SlideService.UpdateSlide:input_type -> runtime.v1.UpdateSlideRequest
	10, // 5: runtime.v1.SlideService.UploadSlide:input_type -> runtime.v1.UploadSlideRequest
	12, // 6: runtime.v1.SlideService.UploadSlideTemplate:input_type -> runtime.v1.UploadSlideTemplateRequest
	1,  // 7: runtime.v1.SlideService.InitSlideProject:output_type -> runtime.v1.InitSlideProjectResponse
	3,  // 8: runtime.v1.SlideService.ModifySlide:output_type -> runtime.v1.ModifySlideResponse
	5,  // 9: runtime.v1.SlideService.PresentSlide:output_type -> runtime.v1.PresentSlideResponse
	7,  // 10: runtime.v1.SlideService.FetchSlideNotes:output_type -> runtime.v1.FetchSlideNotesResponse
	9,  // 11: runtime.v1.SlideService.UpdateSlide:output_type -> runtime.v1.UpdateSlideResponse
	11, // 12: runtime.v1.SlideService.UploadSlide:output_type -> runtime.v1.UploadSlideResponse
	13, // 13: runtime.v1.SlideService.UploadSlideTemplate:output_type -> runtime.v1.UploadSlideTemplateResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_slide_proto_init() }
func file_runtime_v1_slide_proto_init() {
	if File_runtime_v1_slide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_slide_proto_rawDesc), len(file_runtime_v1_slide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_slide_proto_goTypes,
		DependencyIndexes: file_runtime_v1_slide_proto_depIdxs,
		MessageInfos:      file_runtime_v1_slide_proto_msgTypes,
	}.Build()
	File_runtime_v1_slide_proto = out.File
	file_runtime_v1_slide_proto_goTypes = nil
	file_runtime_v1_slide_proto_depIdxs = nil
}
