// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/terminal.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KillTerminalProcessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetDeviceId string                 `protobuf:"bytes,1,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"` // GetXxx symbol: GetTargetDeviceId
	TargetEnv      string                 `protobuf:"bytes,2,opt,name=target_env,json=targetEnv,proto3" json:"target_env,omitempty"`                  // GetXxx symbol: GetTargetEnv
	TerminalId     string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`               // GetXxx symbol: GetTerminalId
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KillTerminalProcessRequest) Reset() {
	*x = KillTerminalProcessRequest{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillTerminalProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTerminalProcessRequest) ProtoMessage() {}

func (x *KillTerminalProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTerminalProcessRequest.ProtoReflect.Descriptor instead.
func (*KillTerminalProcessRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *KillTerminalProcessRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *KillTerminalProcessRequest) GetTargetEnv() string {
	if x != nil {
		return x.TargetEnv
	}
	return ""
}

func (x *KillTerminalProcessRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type KillTerminalProcessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Output         string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                       // GetXxx symbol: GetOutput
	Result         string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                       // GetXxx symbol: GetResult
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                       // GetXxx symbol: GetStatus
	TerminalId     string                 `protobuf:"bytes,4,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`             // GetXxx symbol: GetTerminalId
	TerminalStatus string                 `protobuf:"bytes,5,opt,name=terminal_status,json=terminalStatus,proto3" json:"terminal_status,omitempty"` // GetXxx symbol: GetTerminalStatus
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KillTerminalProcessResponse) Reset() {
	*x = KillTerminalProcessResponse{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillTerminalProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTerminalProcessResponse) ProtoMessage() {}

func (x *KillTerminalProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTerminalProcessResponse.ProtoReflect.Descriptor instead.
func (*KillTerminalProcessResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *KillTerminalProcessResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *KillTerminalProcessResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *KillTerminalProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KillTerminalProcessResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *KillTerminalProcessResponse) GetTerminalStatus() string {
	if x != nil {
		return x.TerminalStatus
	}
	return ""
}

type ViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRequest) Reset() {
	*x = ViewRequest{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRequest) ProtoMessage() {}

func (x *ViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRequest.ProtoReflect.Descriptor instead.
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{2}
}

type ViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{3}
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{4}
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{5}
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{6}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{7}
}

type ResetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllRequest) Reset() {
	*x = ResetAllRequest{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllRequest) ProtoMessage() {}

func (x *ResetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllRequest.ProtoReflect.Descriptor instead.
func (*ResetAllRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{8}
}

type ResetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllResponse) Reset() {
	*x = ResetAllResponse{}
	mi := &file_runtime_v1_terminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllResponse) ProtoMessage() {}

func (x *ResetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_terminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllResponse.ProtoReflect.Descriptor instead.
func (*ResetAllResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_terminal_proto_rawDescGZIP(), []int{9}
}

var File_runtime_v1_terminal_proto protoreflect.FileDescriptor

const file_runtime_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"\x19runtime/v1/terminal.proto\x12\n" +
	"runtime.v1\"\x86\x01\n" +
	"\x1aKillTerminalProcessRequest\x12(\n" +
	"\x10target_device_id\x18\x01 \x01(\tR\x0etargetDeviceId\x12\x1d\n" +
	"\n" +
	"target_env\x18\x02 \x01(\tR\ttargetEnv\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\"\xaf\x01\n" +
	"\x1bKillTerminalProcessResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vterminal_id\x18\x04 \x01(\tR\n" +
	"terminalId\x12'\n" +
	"\x0fterminal_status\x18\x05 \x01(\tR\x0eterminalStatus\"\r\n" +
	"\vViewRequest\"\x0e\n" +
	"\fViewResponse\"\x0e\n" +
	"\fWriteRequest\"\x0f\n" +
	"\rWriteResponse\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse\"\x11\n" +
	"\x0fResetAllRequest\"\x12\n" +
	"\x10ResetAllResponse2\xf7\x02\n" +
	"\x0fTerminalService\x129\n" +
	"\x04View\x12\x17.runtime.v1.ViewRequest\x1a\x18.runtime.v1.ViewResponse\x12<\n" +
	"\x05Write\x12\x18.runtime.v1.WriteRequest\x1a\x19.runtime.v1.WriteResponse\x12<\n" +
	"\x05Reset\x12\x18.runtime.v1.ResetRequest\x1a\x19.runtime.v1.ResetResponse\x12E\n" +
	"\bResetAll\x12\x1b.runtime.v1.ResetAllRequest\x1a\x1c.runtime.v1.ResetAllResponse\x12f\n" +
	"\x13KillTerminalProcess\x12&.runtime.v1.KillTerminalProcessRequest\x1a'.runtime.v1.KillTerminalProcessResponseB\xcc\x01\n" +
	"\x0ecom.runtime.v1B\rTerminalProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_terminal_proto_rawDescOnce sync.Once
	file_runtime_v1_terminal_proto_rawDescData []byte
)

func file_runtime_v1_terminal_proto_rawDescGZIP() []byte {
	file_runtime_v1_terminal_proto_rawDescOnce.Do(func() {
		file_runtime_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_terminal_proto_rawDesc), len(file_runtime_v1_terminal_proto_rawDesc)))
	})
	return file_runtime_v1_terminal_proto_rawDescData
}

var file_runtime_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtime_v1_terminal_proto_goTypes = []any{
	(*KillTerminalProcessRequest)(nil),  // 0: runtime.v1.KillTerminalProcessRequest
	(*KillTerminalProcessResponse)(nil), // 1: runtime.v1.KillTerminalProcessResponse
	(*ViewRequest)(nil),                 // 2: runtime.v1.ViewRequest
	(*ViewResponse)(nil),                // 3: runtime.v1.ViewResponse
	(*WriteRequest)(nil),                // 4: runtime.v1.WriteRequest
	(*WriteResponse)(nil),               // 5: runtime.v1.WriteResponse
	(*ResetRequest)(nil),                // 6: runtime.v1.ResetRequest
	(*ResetResponse)(nil),               // 7: runtime.v1.ResetResponse
	(*ResetAllRequest)(nil),             // 8: runtime.v1.ResetAllRequest
	(*ResetAllResponse)(nil),            // 9: runtime.v1.ResetAllResponse
}
var file_runtime_v1_terminal_proto_depIdxs = []int32{
	2, // 0: runtime.v1.TerminalService.View:input_type -> runtime.v1.ViewRequest
	4, // 1: runtime.v1.TerminalService.Write:input_type -> runtime.v1.WriteRequest
	6, // 2: runtime.v1.TerminalService.Reset:input_type -> runtime.v1.ResetRequest
	8, // 3: runtime.v1.TerminalService.ResetAll:input_type -> runtime.v1.ResetAllRequest
	0, // 4: runtime.v1.TerminalService.KillTerminalProcess:input_type -> runtime.v1.KillTerminalProcessRequest
	3, // 5: runtime.v1.TerminalService.View:output_type -> runtime.v1.ViewResponse
	5, // 6: runtime.v1.TerminalService.Write:output_type -> runtime.v1.WriteResponse
	7, // 7: runtime.v1.TerminalService.Reset:output_type -> runtime.v1.ResetResponse
	9, // 8: runtime.v1.TerminalService.ResetAll:output_type -> runtime.v1.ResetAllResponse
	1, // 9: runtime.v1.TerminalService.KillTerminalProcess:output_type -> runtime.v1.KillTerminalProcessResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_terminal_proto_init() }
func file_runtime_v1_terminal_proto_init() {
	if File_runtime_v1_terminal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_terminal_proto_rawDesc), len(file_runtime_v1_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_terminal_proto_goTypes,
		DependencyIndexes: file_runtime_v1_terminal_proto_depIdxs,
		MessageInfos:      file_runtime_v1_terminal_proto_msgTypes,
	}.Build()
	File_runtime_v1_terminal_proto = out.File
	file_runtime_v1_terminal_proto_goTypes = nil
	file_runtime_v1_terminal_proto_depIdxs = nil
}
