// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/text_editor.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunTextEditorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTextEditorRequest) Reset() {
	*x = RunTextEditorRequest{}
	mi := &file_runtime_v1_text_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTextEditorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTextEditorRequest) ProtoMessage() {}

func (x *RunTextEditorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_text_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTextEditorRequest.ProtoReflect.Descriptor instead.
func (*RunTextEditorRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_text_editor_proto_rawDescGZIP(), []int{0}
}

type RunTextEditorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTextEditorResponse) Reset() {
	*x = RunTextEditorResponse{}
	mi := &file_runtime_v1_text_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTextEditorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTextEditorResponse) ProtoMessage() {}

func (x *RunTextEditorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_text_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTextEditorResponse.ProtoReflect.Descriptor instead.
func (*RunTextEditorResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_text_editor_proto_rawDescGZIP(), []int{1}
}

var File_runtime_v1_text_editor_proto protoreflect.FileDescriptor

const file_runtime_v1_text_editor_proto_rawDesc = "" +
	"\n" +
	"\x1cruntime/v1/text_editor.proto\x12\n" +
	"runtime.v1\"\x16\n" +
	"\x14RunTextEditorRequest\"\x17\n" +
	"\x15RunTextEditorResponse2i\n" +
	"\x11TextEditorService\x12T\n" +
	"\rRunTextEditor\x12 .runtime.v1.RunTextEditorRequest\x1a!.runtime.v1.RunTextEditorResponseB\xce\x01\n" +
	"\x0ecom.runtime.v1B\x0fTextEditorProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_text_editor_proto_rawDescOnce sync.Once
	file_runtime_v1_text_editor_proto_rawDescData []byte
)

func file_runtime_v1_text_editor_proto_rawDescGZIP() []byte {
	file_runtime_v1_text_editor_proto_rawDescOnce.Do(func() {
		file_runtime_v1_text_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_text_editor_proto_rawDesc), len(file_runtime_v1_text_editor_proto_rawDesc)))
	})
	return file_runtime_v1_text_editor_proto_rawDescData
}

var file_runtime_v1_text_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runtime_v1_text_editor_proto_goTypes = []any{
	(*RunTextEditorRequest)(nil),  // 0: runtime.v1.RunTextEditorRequest
	(*RunTextEditorResponse)(nil), // 1: runtime.v1.RunTextEditorResponse
}
var file_runtime_v1_text_editor_proto_depIdxs = []int32{
	0, // 0: runtime.v1.TextEditorService.RunTextEditor:input_type -> runtime.v1.RunTextEditorRequest
	1, // 1: runtime.v1.TextEditorService.RunTextEditor:output_type -> runtime.v1.RunTextEditorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_text_editor_proto_init() }
func file_runtime_v1_text_editor_proto_init() {
	if File_runtime_v1_text_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_text_editor_proto_rawDesc), len(file_runtime_v1_text_editor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_text_editor_proto_goTypes,
		DependencyIndexes: file_runtime_v1_text_editor_proto_depIdxs,
		MessageInfos:      file_runtime_v1_text_editor_proto_msgTypes,
	}.Build()
	File_runtime_v1_text_editor_proto = out.File
	file_runtime_v1_text_editor_proto_goTypes = nil
	file_runtime_v1_text_editor_proto_depIdxs = nil
}
