// SPDX-License-Identifier: <unknown>
// Reverse-engineered from Manus sandbox-runtime v8.0.2 RAM dump 2026-05-14
// Source: github.com/manus-ai/manus-sandbox/sbx-go-svc/sdk/go/runtime/v1
// Method: Extracted protobuf field-tags + SDK getter symbols from RAM segment

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: runtime/v1/webdev.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitProjectRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Capabilities           string                 `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                                        // GetXxx symbol: GetCapabilities
	CheckpointZipUploadUrl string                 `protobuf:"bytes,2,opt,name=checkpoint_zip_upload_url,json=checkpointZipUploadUrl,proto3" json:"checkpoint_zip_upload_url,omitempty"`  // GetXxx symbol: GetCheckpointZipUploadUrl
	CheckpointZipUrl       string                 `protobuf:"bytes,3,opt,name=checkpoint_zip_url,json=checkpointZipUrl,proto3" json:"checkpoint_zip_url,omitempty"`                      // GetXxx symbol: GetCheckpointZipUrl
	EnvVars                string                 `protobuf:"bytes,4,opt,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`                                                   // GetXxx symbol: GetEnvVars
	Experiments            string                 `protobuf:"bytes,5,opt,name=experiments,proto3" json:"experiments,omitempty"`                                                          // GetXxx symbol: GetExperiments
	Platform               string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`                                                                // GetXxx symbol: GetPlatform
	ProjectConfig          string                 `protobuf:"bytes,7,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                                 // GetXxx symbol: GetProjectConfig
	ProjectName            string                 `protobuf:"bytes,8,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                                       // GetXxx symbol: GetProjectName
	ProjectTitle           string                 `protobuf:"bytes,9,opt,name=project_title,json=projectTitle,proto3" json:"project_title,omitempty"`                                    // GetXxx symbol: GetProjectTitle
	ProjectType            string                 `protobuf:"bytes,10,opt,name=project_type,json=projectType,proto3" json:"project_type,omitempty"`                                      // GetXxx symbol: GetProjectType
	SourceCheckpointZipUrl string                 `protobuf:"bytes,11,opt,name=source_checkpoint_zip_url,json=sourceCheckpointZipUrl,proto3" json:"source_checkpoint_zip_url,omitempty"` // GetXxx symbol: GetSourceCheckpointZipUrl
	SourceGitRepo          string                 `protobuf:"bytes,12,opt,name=source_git_repo,json=sourceGitRepo,proto3" json:"source_git_repo,omitempty"`                              // GetXxx symbol: GetSourceGitRepo
	TemplateId             string                 `protobuf:"bytes,13,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`                                         // GetXxx symbol: GetTemplateId
	TemplatePrompt         string                 `protobuf:"bytes,14,opt,name=template_prompt,json=templatePrompt,proto3" json:"template_prompt,omitempty"`                             // GetXxx symbol: GetTemplatePrompt
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InitProjectRequest) Reset() {
	*x = InitProjectRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProjectRequest) ProtoMessage() {}

func (x *InitProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProjectRequest.ProtoReflect.Descriptor instead.
func (*InitProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{0}
}

func (x *InitProjectRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

func (x *InitProjectRequest) GetCheckpointZipUploadUrl() string {
	if x != nil {
		return x.CheckpointZipUploadUrl
	}
	return ""
}

func (x *InitProjectRequest) GetCheckpointZipUrl() string {
	if x != nil {
		return x.CheckpointZipUrl
	}
	return ""
}

func (x *InitProjectRequest) GetEnvVars() string {
	if x != nil {
		return x.EnvVars
	}
	return ""
}

func (x *InitProjectRequest) GetExperiments() string {
	if x != nil {
		return x.Experiments
	}
	return ""
}

func (x *InitProjectRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *InitProjectRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *InitProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *InitProjectRequest) GetProjectTitle() string {
	if x != nil {
		return x.ProjectTitle
	}
	return ""
}

func (x *InitProjectRequest) GetProjectType() string {
	if x != nil {
		return x.ProjectType
	}
	return ""
}

func (x *InitProjectRequest) GetSourceCheckpointZipUrl() string {
	if x != nil {
		return x.SourceCheckpointZipUrl
	}
	return ""
}

func (x *InitProjectRequest) GetSourceGitRepo() string {
	if x != nil {
		return x.SourceGitRepo
	}
	return ""
}

func (x *InitProjectRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *InitProjectRequest) GetTemplatePrompt() string {
	if x != nil {
		return x.TemplatePrompt
	}
	return ""
}

type InitProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitProjectResponse) Reset() {
	*x = InitProjectResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProjectResponse) ProtoMessage() {}

func (x *InitProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProjectResponse.ProtoReflect.Descriptor instead.
func (*InitProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{1}
}

func (x *InitProjectResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UpdateConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BuildCommand       string                 `protobuf:"bytes,1,opt,name=build_command,json=buildCommand,proto3" json:"build_command,omitempty"`                     // GetXxx symbol: GetBuildCommand
	Capabilities       string                 `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                         // GetXxx symbol: GetCapabilities
	DevCommand         string                 `protobuf:"bytes,3,opt,name=dev_command,json=devCommand,proto3" json:"dev_command,omitempty"`                           // GetXxx symbol: GetDevCommand
	EnvVars            string                 `protobuf:"bytes,4,opt,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`                                    // GetXxx symbol: GetEnvVars
	GitRemote          string                 `protobuf:"bytes,5,opt,name=git_remote,json=gitRemote,proto3" json:"git_remote,omitempty"`                              // GetXxx symbol: GetGitRemote
	Port               string                 `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`                                                         // GetXxx symbol: GetPort
	PresignedUploadUrl string                 `protobuf:"bytes,7,opt,name=presigned_upload_url,json=presignedUploadUrl,proto3" json:"presigned_upload_url,omitempty"` // GetXxx symbol: GetPresignedUploadUrl
	ProjectConfig      string                 `protobuf:"bytes,8,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                  // GetXxx symbol: GetProjectConfig
	ProjectName        string                 `protobuf:"bytes,9,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                        // GetXxx symbol: GetProjectName
	Secrets            string                 `protobuf:"bytes,10,opt,name=secrets,proto3" json:"secrets,omitempty"`                                                  // GetXxx symbol: GetSecrets
	TemplateOverrides  string                 `protobuf:"bytes,11,opt,name=template_overrides,json=templateOverrides,proto3" json:"template_overrides,omitempty"`     // GetXxx symbol: GetTemplateOverrides
	TestCommand        string                 `protobuf:"bytes,12,opt,name=test_command,json=testCommand,proto3" json:"test_command,omitempty"`                       // GetXxx symbol: GetTestCommand
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigRequest) GetBuildCommand() string {
	if x != nil {
		return x.BuildCommand
	}
	return ""
}

func (x *UpdateConfigRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

func (x *UpdateConfigRequest) GetDevCommand() string {
	if x != nil {
		return x.DevCommand
	}
	return ""
}

func (x *UpdateConfigRequest) GetEnvVars() string {
	if x != nil {
		return x.EnvVars
	}
	return ""
}

func (x *UpdateConfigRequest) GetGitRemote() string {
	if x != nil {
		return x.GitRemote
	}
	return ""
}

func (x *UpdateConfigRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *UpdateConfigRequest) GetPresignedUploadUrl() string {
	if x != nil {
		return x.PresignedUploadUrl
	}
	return ""
}

func (x *UpdateConfigRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *UpdateConfigRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UpdateConfigRequest) GetSecrets() string {
	if x != nil {
		return x.Secrets
	}
	return ""
}

func (x *UpdateConfigRequest) GetTemplateOverrides() string {
	if x != nil {
		return x.TemplateOverrides
	}
	return ""
}

func (x *UpdateConfigRequest) GetTestCommand() string {
	if x != nil {
		return x.TestCommand
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GitSyncCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectConfig string                 `protobuf:"bytes,1,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"` // GetXxx symbol: GetProjectConfig
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`       // GetXxx symbol: GetProjectName
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSyncCheckRequest) Reset() {
	*x = GitSyncCheckRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSyncCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSyncCheckRequest) ProtoMessage() {}

func (x *GitSyncCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSyncCheckRequest.ProtoReflect.Descriptor instead.
func (*GitSyncCheckRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{4}
}

func (x *GitSyncCheckRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *GitSyncCheckRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type GitSyncCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSyncCheckResponse) Reset() {
	*x = GitSyncCheckResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSyncCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSyncCheckResponse) ProtoMessage() {}

func (x *GitSyncCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSyncCheckResponse.ProtoReflect.Descriptor instead.
func (*GitSyncCheckResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{5}
}

func (x *GitSyncCheckResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RestartProjectRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PresignedUploadUrl string                 `protobuf:"bytes,1,opt,name=presigned_upload_url,json=presignedUploadUrl,proto3" json:"presigned_upload_url,omitempty"` // GetXxx symbol: GetPresignedUploadUrl
	ProjectConfig      string                 `protobuf:"bytes,2,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                  // GetXxx symbol: GetProjectConfig
	ProjectName        string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                        // GetXxx symbol: GetProjectName
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RestartProjectRequest) Reset() {
	*x = RestartProjectRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProjectRequest) ProtoMessage() {}

func (x *RestartProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProjectRequest.ProtoReflect.Descriptor instead.
func (*RestartProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{6}
}

func (x *RestartProjectRequest) GetPresignedUploadUrl() string {
	if x != nil {
		return x.PresignedUploadUrl
	}
	return ""
}

func (x *RestartProjectRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *RestartProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type RestartProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartProjectResponse) Reset() {
	*x = RestartProjectResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProjectResponse) ProtoMessage() {}

func (x *RestartProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProjectResponse.ProtoReflect.Descriptor instead.
func (*RestartProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{7}
}

func (x *RestartProjectResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RestoreProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  string                 `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                        // GetXxx symbol: GetCapabilities
	Experiments   string                 `protobuf:"bytes,2,opt,name=experiments,proto3" json:"experiments,omitempty"`                          // GetXxx symbol: GetExperiments
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`                                // GetXxx symbol: GetPlatform
	ProjectConfig string                 `protobuf:"bytes,4,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"` // GetXxx symbol: GetProjectConfig
	ProjectName   string                 `protobuf:"bytes,5,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`       // GetXxx symbol: GetProjectName
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreProjectRequest) Reset() {
	*x = RestoreProjectRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProjectRequest) ProtoMessage() {}

func (x *RestoreProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProjectRequest.ProtoReflect.Descriptor instead.
func (*RestoreProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreProjectRequest) GetCapabilities() string {
	if x != nil {
		return x.Capabilities
	}
	return ""
}

func (x *RestoreProjectRequest) GetExperiments() string {
	if x != nil {
		return x.Experiments
	}
	return ""
}

func (x *RestoreProjectRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RestoreProjectRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *RestoreProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type RestoreProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreProjectResponse) Reset() {
	*x = RestoreProjectResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProjectResponse) ProtoMessage() {}

func (x *RestoreProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProjectResponse.ProtoReflect.Descriptor instead.
func (*RestoreProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreProjectResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RollbackProjectRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CheckpointZipUploadUrl string                 `protobuf:"bytes,1,opt,name=checkpoint_zip_upload_url,json=checkpointZipUploadUrl,proto3" json:"checkpoint_zip_upload_url,omitempty"` // GetXxx symbol: GetCheckpointZipUploadUrl
	CheckpointZipUrl       string                 `protobuf:"bytes,2,opt,name=checkpoint_zip_url,json=checkpointZipUrl,proto3" json:"checkpoint_zip_url,omitempty"`                     // GetXxx symbol: GetCheckpointZipUrl
	ProjectConfig          string                 `protobuf:"bytes,3,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                                // GetXxx symbol: GetProjectConfig
	ProjectName            string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                                      // GetXxx symbol: GetProjectName
	VersionId              string                 `protobuf:"bytes,5,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`                                            // GetXxx symbol: GetVersionId
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RollbackProjectRequest) Reset() {
	*x = RollbackProjectRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackProjectRequest) ProtoMessage() {}

func (x *RollbackProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackProjectRequest.ProtoReflect.Descriptor instead.
func (*RollbackProjectRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{10}
}

func (x *RollbackProjectRequest) GetCheckpointZipUploadUrl() string {
	if x != nil {
		return x.CheckpointZipUploadUrl
	}
	return ""
}

func (x *RollbackProjectRequest) GetCheckpointZipUrl() string {
	if x != nil {
		return x.CheckpointZipUrl
	}
	return ""
}

func (x *RollbackProjectRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *RollbackProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RollbackProjectRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type RollbackProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackProjectResponse) Reset() {
	*x = RollbackProjectResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackProjectResponse) ProtoMessage() {}

func (x *RollbackProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackProjectResponse.ProtoReflect.Descriptor instead.
func (*RollbackProjectResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{11}
}

func (x *RollbackProjectResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ApplyWebpageEditsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EditsByFilePath string                 `protobuf:"bytes,1,opt,name=edits_by_file_path,json=editsByFilePath,proto3" json:"edits_by_file_path,omitempty"` // GetXxx symbol: GetEditsByFilePath
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyWebpageEditsRequest) Reset() {
	*x = ApplyWebpageEditsRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWebpageEditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWebpageEditsRequest) ProtoMessage() {}

func (x *ApplyWebpageEditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWebpageEditsRequest.ProtoReflect.Descriptor instead.
func (*ApplyWebpageEditsRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyWebpageEditsRequest) GetEditsByFilePath() string {
	if x != nil {
		return x.EditsByFilePath
	}
	return ""
}

type ApplyWebpageEditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWebpageEditsResponse) Reset() {
	*x = ApplyWebpageEditsResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWebpageEditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWebpageEditsResponse) ProtoMessage() {}

func (x *ApplyWebpageEditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWebpageEditsResponse.ProtoReflect.Descriptor instead.
func (*ApplyWebpageEditsResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyWebpageEditsResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DatabaseOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`                              // GetXxx symbol: GetOperation
	ProjectConfig string                 `protobuf:"bytes,2,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"` // GetXxx symbol: GetProjectConfig
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`       // GetXxx symbol: GetProjectName
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`                                      // GetXxx symbol: GetQuery
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseOperationRequest) Reset() {
	*x = DatabaseOperationRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseOperationRequest) ProtoMessage() {}

func (x *DatabaseOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseOperationRequest.ProtoReflect.Descriptor instead.
func (*DatabaseOperationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{14}
}

func (x *DatabaseOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DatabaseOperationRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *DatabaseOperationRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DatabaseOperationRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type DatabaseOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseOperationResponse) Reset() {
	*x = DatabaseOperationResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseOperationResponse) ProtoMessage() {}

func (x *DatabaseOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseOperationResponse.ProtoReflect.Descriptor instead.
func (*DatabaseOperationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{15}
}

func (x *DatabaseOperationResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RefreshGitHubTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserGitRepo   string                 `protobuf:"bytes,1,opt,name=user_git_repo,json=userGitRepo,proto3" json:"user_git_repo,omitempty"` // GetXxx symbol: GetUserGitRepo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshGitHubTokenRequest) Reset() {
	*x = RefreshGitHubTokenRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGitHubTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGitHubTokenRequest) ProtoMessage() {}

func (x *RefreshGitHubTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGitHubTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshGitHubTokenRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{16}
}

func (x *RefreshGitHubTokenRequest) GetUserGitRepo() string {
	if x != nil {
		return x.UserGitRepo
	}
	return ""
}

type RefreshGitHubTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshGitHubTokenResponse) Reset() {
	*x = RefreshGitHubTokenResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGitHubTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGitHubTokenResponse) ProtoMessage() {}

func (x *RefreshGitHubTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGitHubTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshGitHubTokenResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshGitHubTokenResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RefreshS3TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Config      string                 `protobuf:"bytes,1,opt,name=s3_config,json=s3Config,proto3" json:"s3_config,omitempty"` // GetXxx symbol: GetS3Config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshS3TokenRequest) Reset() {
	*x = RefreshS3TokenRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshS3TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshS3TokenRequest) ProtoMessage() {}

func (x *RefreshS3TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshS3TokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshS3TokenRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshS3TokenRequest) GetS3Config() string {
	if x != nil {
		return x.S3Config
	}
	return ""
}

type RefreshS3TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshS3TokenResponse) Reset() {
	*x = RefreshS3TokenResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshS3TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshS3TokenResponse) ProtoMessage() {}

func (x *RefreshS3TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshS3TokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshS3TokenResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{19}
}

func (x *RefreshS3TokenResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetProjectStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PresignedUploadUrl string                 `protobuf:"bytes,1,opt,name=presigned_upload_url,json=presignedUploadUrl,proto3" json:"presigned_upload_url,omitempty"` // GetXxx symbol: GetPresignedUploadUrl
	ProjectConfig      string                 `protobuf:"bytes,2,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                  // GetXxx symbol: GetProjectConfig
	ProjectName        string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                        // GetXxx symbol: GetProjectName
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProjectStatusRequest) Reset() {
	*x = GetProjectStatusRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatusRequest) ProtoMessage() {}

func (x *GetProjectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProjectStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{20}
}

func (x *GetProjectStatusRequest) GetPresignedUploadUrl() string {
	if x != nil {
		return x.PresignedUploadUrl
	}
	return ""
}

func (x *GetProjectStatusRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *GetProjectStatusRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type GetProjectStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectStatusResponse) Reset() {
	*x = GetProjectStatusResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatusResponse) ProtoMessage() {}

func (x *GetProjectStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProjectStatusResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{21}
}

func (x *GetProjectStatusResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GitPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectConfig string                 `protobuf:"bytes,1,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"` // GetXxx symbol: GetProjectConfig
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`       // GetXxx symbol: GetProjectName
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitPushRequest) Reset() {
	*x = GitPushRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitPushRequest) ProtoMessage() {}

func (x *GitPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitPushRequest.ProtoReflect.Descriptor instead.
func (*GitPushRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{22}
}

func (x *GitPushRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *GitPushRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type GitPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitPushResponse) Reset() {
	*x = GitPushResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitPushResponse) ProtoMessage() {}

func (x *GitPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitPushResponse.ProtoReflect.Descriptor instead.
func (*GitPushResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{23}
}

func (x *GitPushResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SetupImportedTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // GetXxx symbol: GetTemplateId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupImportedTemplateRequest) Reset() {
	*x = SetupImportedTemplateRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupImportedTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupImportedTemplateRequest) ProtoMessage() {}

func (x *SetupImportedTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupImportedTemplateRequest.ProtoReflect.Descriptor instead.
func (*SetupImportedTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{24}
}

func (x *SetupImportedTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type SetupImportedTemplateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppliedTemplates string                 `protobuf:"bytes,1,opt,name=applied_templates,json=appliedTemplates,proto3" json:"applied_templates,omitempty"` // GetXxx symbol: GetAppliedTemplates
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                               // GetXxx symbol: GetError
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                           // GetXxx symbol: GetMessage
	Success          string                 `protobuf:"bytes,4,opt,name=success,proto3" json:"success,omitempty"`                                           // GetXxx symbol: GetSuccess
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetupImportedTemplateResponse) Reset() {
	*x = SetupImportedTemplateResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupImportedTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupImportedTemplateResponse) ProtoMessage() {}

func (x *SetupImportedTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupImportedTemplateResponse.ProtoReflect.Descriptor instead.
func (*SetupImportedTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{25}
}

func (x *SetupImportedTemplateResponse) GetAppliedTemplates() string {
	if x != nil {
		return x.AppliedTemplates
	}
	return ""
}

func (x *SetupImportedTemplateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetupImportedTemplateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetupImportedTemplateResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type SaveCheckpointRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CheckpointZipUploadUrl string                 `protobuf:"bytes,1,opt,name=checkpoint_zip_upload_url,json=checkpointZipUploadUrl,proto3" json:"checkpoint_zip_upload_url,omitempty"` // GetXxx symbol: GetCheckpointZipUploadUrl
	CheckpointZipUrl       string                 `protobuf:"bytes,2,opt,name=checkpoint_zip_url,json=checkpointZipUrl,proto3" json:"checkpoint_zip_url,omitempty"`                     // GetXxx symbol: GetCheckpointZipUrl
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                         // GetXxx symbol: GetDescription
	LastCheckpointCommit   string                 `protobuf:"bytes,4,opt,name=last_checkpoint_commit,json=lastCheckpointCommit,proto3" json:"last_checkpoint_commit,omitempty"`         // GetXxx symbol: GetLastCheckpointCommit
	ProjectConfig          string                 `protobuf:"bytes,5,opt,name=project_config,json=projectConfig,proto3" json:"project_config,omitempty"`                                // GetXxx symbol: GetProjectConfig
	ProjectName            string                 `protobuf:"bytes,6,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`                                      // GetXxx symbol: GetProjectName
	Timeout                string                 `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                 // GetXxx symbol: GetTimeout
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SaveCheckpointRequest) Reset() {
	*x = SaveCheckpointRequest{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointRequest) ProtoMessage() {}

func (x *SaveCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SaveCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{26}
}

func (x *SaveCheckpointRequest) GetCheckpointZipUploadUrl() string {
	if x != nil {
		return x.CheckpointZipUploadUrl
	}
	return ""
}

func (x *SaveCheckpointRequest) GetCheckpointZipUrl() string {
	if x != nil {
		return x.CheckpointZipUrl
	}
	return ""
}

func (x *SaveCheckpointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SaveCheckpointRequest) GetLastCheckpointCommit() string {
	if x != nil {
		return x.LastCheckpointCommit
	}
	return ""
}

func (x *SaveCheckpointRequest) GetProjectConfig() string {
	if x != nil {
		return x.ProjectConfig
	}
	return ""
}

func (x *SaveCheckpointRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SaveCheckpointRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type SaveCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // GetXxx symbol: GetData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCheckpointResponse) Reset() {
	*x = SaveCheckpointResponse{}
	mi := &file_runtime_v1_webdev_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointResponse) ProtoMessage() {}

func (x *SaveCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_webdev_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SaveCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_webdev_proto_rawDescGZIP(), []int{27}
}

func (x *SaveCheckpointResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_runtime_v1_webdev_proto protoreflect.FileDescriptor

const file_runtime_v1_webdev_proto_rawDesc = "" +
	"\n" +
	"\x17runtime/v1/webdev.proto\x12\n" +
	"runtime.v1\"\xb9\x04\n" +
	"\x12InitProjectRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x01(\tR\fcapabilities\x129\n" +
	"\x19checkpoint_zip_upload_url\x18\x02 \x01(\tR\x16checkpointZipUploadUrl\x12,\n" +
	"\x12checkpoint_zip_url\x18\x03 \x01(\tR\x10checkpointZipUrl\x12\x19\n" +
	"\benv_vars\x18\x04 \x01(\tR\aenvVars\x12 \n" +
	"\vexperiments\x18\x05 \x01(\tR\vexperiments\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12%\n" +
	"\x0eproject_config\x18\a \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\b \x01(\tR\vprojectName\x12#\n" +
	"\rproject_title\x18\t \x01(\tR\fprojectTitle\x12!\n" +
	"\fproject_type\x18\n" +
	" \x01(\tR\vprojectType\x129\n" +
	"\x19source_checkpoint_zip_url\x18\v \x01(\tR\x16sourceCheckpointZipUrl\x12&\n" +
	"\x0fsource_git_repo\x18\f \x01(\tR\rsourceGitRepo\x12\x1f\n" +
	"\vtemplate_id\x18\r \x01(\tR\n" +
	"templateId\x12'\n" +
	"\x0ftemplate_prompt\x18\x0e \x01(\tR\x0etemplatePrompt\")\n" +
	"\x13InitProjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xb5\x03\n" +
	"\x13UpdateConfigRequest\x12#\n" +
	"\rbuild_command\x18\x01 \x01(\tR\fbuildCommand\x12\"\n" +
	"\fcapabilities\x18\x02 \x01(\tR\fcapabilities\x12\x1f\n" +
	"\vdev_command\x18\x03 \x01(\tR\n" +
	"devCommand\x12\x19\n" +
	"\benv_vars\x18\x04 \x01(\tR\aenvVars\x12\x1d\n" +
	"\n" +
	"git_remote\x18\x05 \x01(\tR\tgitRemote\x12\x12\n" +
	"\x04port\x18\x06 \x01(\tR\x04port\x120\n" +
	"\x14presigned_upload_url\x18\a \x01(\tR\x12presignedUploadUrl\x12%\n" +
	"\x0eproject_config\x18\b \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\t \x01(\tR\vprojectName\x12\x18\n" +
	"\asecrets\x18\n" +
	" \x01(\tR\asecrets\x12-\n" +
	"\x12template_overrides\x18\v \x01(\tR\x11templateOverrides\x12!\n" +
	"\ftest_command\x18\f \x01(\tR\vtestCommand\"*\n" +
	"\x14UpdateConfigResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"_\n" +
	"\x13GitSyncCheckRequest\x12%\n" +
	"\x0eproject_config\x18\x01 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\"*\n" +
	"\x14GitSyncCheckResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x93\x01\n" +
	"\x15RestartProjectRequest\x120\n" +
	"\x14presigned_upload_url\x18\x01 \x01(\tR\x12presignedUploadUrl\x12%\n" +
	"\x0eproject_config\x18\x02 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\",\n" +
	"\x16RestartProjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xc3\x01\n" +
	"\x15RestoreProjectRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x01(\tR\fcapabilities\x12 \n" +
	"\vexperiments\x18\x02 \x01(\tR\vexperiments\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12%\n" +
	"\x0eproject_config\x18\x04 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x05 \x01(\tR\vprojectName\",\n" +
	"\x16RestoreProjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xea\x01\n" +
	"\x16RollbackProjectRequest\x129\n" +
	"\x19checkpoint_zip_upload_url\x18\x01 \x01(\tR\x16checkpointZipUploadUrl\x12,\n" +
	"\x12checkpoint_zip_url\x18\x02 \x01(\tR\x10checkpointZipUrl\x12%\n" +
	"\x0eproject_config\x18\x03 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"version_id\x18\x05 \x01(\tR\tversionId\"-\n" +
	"\x17RollbackProjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"G\n" +
	"\x18ApplyWebpageEditsRequest\x12+\n" +
	"\x12edits_by_file_path\x18\x01 \x01(\tR\x0feditsByFilePath\"/\n" +
	"\x19ApplyWebpageEditsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x98\x01\n" +
	"\x18DatabaseOperationRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12%\n" +
	"\x0eproject_config\x18\x02 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\"/\n" +
	"\x19DatabaseOperationResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"?\n" +
	"\x19RefreshGitHubTokenRequest\x12\"\n" +
	"\ruser_git_repo\x18\x01 \x01(\tR\vuserGitRepo\"0\n" +
	"\x1aRefreshGitHubTokenResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"4\n" +
	"\x15RefreshS3TokenRequest\x12\x1b\n" +
	"\ts3_config\x18\x01 \x01(\tR\bs3Config\",\n" +
	"\x16RefreshS3TokenResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x95\x01\n" +
	"\x17GetProjectStatusRequest\x120\n" +
	"\x14presigned_upload_url\x18\x01 \x01(\tR\x12presignedUploadUrl\x12%\n" +
	"\x0eproject_config\x18\x02 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\".\n" +
	"\x18GetProjectStatusResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"Z\n" +
	"\x0eGitPushRequest\x12%\n" +
	"\x0eproject_config\x18\x01 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\"%\n" +
	"\x0fGitPushResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"?\n" +
	"\x1cSetupImportedTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"\x96\x01\n" +
	"\x1dSetupImportedTemplateResponse\x12+\n" +
	"\x11applied_templates\x18\x01 \x01(\tR\x10appliedTemplates\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\tR\asuccess\"\xbc\x02\n" +
	"\x15SaveCheckpointRequest\x129\n" +
	"\x19checkpoint_zip_upload_url\x18\x01 \x01(\tR\x16checkpointZipUploadUrl\x12,\n" +
	"\x12checkpoint_zip_url\x18\x02 \x01(\tR\x10checkpointZipUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x16last_checkpoint_commit\x18\x04 \x01(\tR\x14lastCheckpointCommit\x12%\n" +
	"\x0eproject_config\x18\x05 \x01(\tR\rprojectConfig\x12!\n" +
	"\fproject_name\x18\x06 \x01(\tR\vprojectName\x12\x18\n" +
	"\atimeout\x18\a \x01(\tR\atimeout\",\n" +
	"\x16SaveCheckpointResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\xff\t\n" +
	"\rWebdevService\x12N\n" +
	"\vInitProject\x12\x1e.runtime.v1.InitProjectRequest\x1a\x1f.runtime.v1.InitProjectResponse\x12Q\n" +
	"\fUpdateConfig\x12\x1f.runtime.v1.UpdateConfigRequest\x1a .runtime.v1.UpdateConfigResponse\x12Q\n" +
	"\fGitSyncCheck\x12\x1f.runtime.v1.GitSyncCheckRequest\x1a .runtime.v1.GitSyncCheckResponse\x12W\n" +
	"\x0eRestartProject\x12!.runtime.v1.RestartProjectRequest\x1a\".runtime.v1.RestartProjectResponse\x12W\n" +
	"\x0eRestoreProject\x12!.runtime.v1.RestoreProjectRequest\x1a\".runtime.v1.RestoreProjectResponse\x12Z\n" +
	"\x0fRollbackProject\x12\".runtime.v1.RollbackProjectRequest\x1a#.runtime.v1.RollbackProjectResponse\x12`\n" +
	"\x11ApplyWebpageEdits\x12$.runtime.v1.ApplyWebpageEditsRequest\x1a%.runtime.v1.ApplyWebpageEditsResponse\x12`\n" +
	"\x11DatabaseOperation\x12$.runtime.v1.DatabaseOperationRequest\x1a%.runtime.v1.DatabaseOperationResponse\x12c\n" +
	"\x12RefreshGitHubToken\x12%.runtime.v1.RefreshGitHubTokenRequest\x1a&.runtime.v1.RefreshGitHubTokenResponse\x12W\n" +
	"\x0eRefreshS3Token\x12!.runtime.v1.RefreshS3TokenRequest\x1a\".runtime.v1.RefreshS3TokenResponse\x12]\n" +
	"\x10GetProjectStatus\x12#.runtime.v1.GetProjectStatusRequest\x1a$.runtime.v1.GetProjectStatusResponse\x12B\n" +
	"\aGitPush\x12\x1a.runtime.v1.GitPushRequest\x1a\x1b.runtime.v1.GitPushResponse\x12l\n" +
	"\x15SetupImportedTemplate\x12(.runtime.v1.SetupImportedTemplateRequest\x1a).runtime.v1.SetupImportedTemplateResponse\x12W\n" +
	"\x0eSaveCheckpoint\x12!.runtime.v1.SaveCheckpointRequest\x1a\".runtime.v1.SaveCheckpointResponseB\xca\x01\n" +
	"\x0ecom.runtime.v1B\vWebdevProtoP\x01Zbgithub.com/Helix12-Labs/helix12-maxicore-envd/packages/envd/internal/services/runtime/v1;runtimev1\xa2\x02\x03RXX\xaa\x02\n" +
	"Runtime.V1\xca\x02\n" +
	"Runtime\\V1\xe2\x02\x16Runtime\\V1\\GPBMetadata\xea\x02\vRuntime::V1b\x06proto3"

var (
	file_runtime_v1_webdev_proto_rawDescOnce sync.Once
	file_runtime_v1_webdev_proto_rawDescData []byte
)

func file_runtime_v1_webdev_proto_rawDescGZIP() []byte {
	file_runtime_v1_webdev_proto_rawDescOnce.Do(func() {
		file_runtime_v1_webdev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_webdev_proto_rawDesc), len(file_runtime_v1_webdev_proto_rawDesc)))
	})
	return file_runtime_v1_webdev_proto_rawDescData
}

var file_runtime_v1_webdev_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_runtime_v1_webdev_proto_goTypes = []any{
	(*InitProjectRequest)(nil),            // 0: runtime.v1.InitProjectRequest
	(*InitProjectResponse)(nil),           // 1: runtime.v1.InitProjectResponse
	(*UpdateConfigRequest)(nil),           // 2: runtime.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),          // 3: runtime.v1.UpdateConfigResponse
	(*GitSyncCheckRequest)(nil),           // 4: runtime.v1.GitSyncCheckRequest
	(*GitSyncCheckResponse)(nil),          // 5: runtime.v1.GitSyncCheckResponse
	(*RestartProjectRequest)(nil),         // 6: runtime.v1.RestartProjectRequest
	(*RestartProjectResponse)(nil),        // 7: runtime.v1.RestartProjectResponse
	(*RestoreProjectRequest)(nil),         // 8: runtime.v1.RestoreProjectRequest
	(*RestoreProjectResponse)(nil),        // 9: runtime.v1.RestoreProjectResponse
	(*RollbackProjectRequest)(nil),        // 10: runtime.v1.RollbackProjectRequest
	(*RollbackProjectResponse)(nil),       // 11: runtime.v1.RollbackProjectResponse
	(*ApplyWebpageEditsRequest)(nil),      // 12: runtime.v1.ApplyWebpageEditsRequest
	(*ApplyWebpageEditsResponse)(nil),     // 13: runtime.v1.ApplyWebpageEditsResponse
	(*DatabaseOperationRequest)(nil),      // 14: runtime.v1.DatabaseOperationRequest
	(*DatabaseOperationResponse)(nil),     // 15: runtime.v1.DatabaseOperationResponse
	(*RefreshGitHubTokenRequest)(nil),     // 16: runtime.v1.RefreshGitHubTokenRequest
	(*RefreshGitHubTokenResponse)(nil),    // 17: runtime.v1.RefreshGitHubTokenResponse
	(*RefreshS3TokenRequest)(nil),         // 18: runtime.v1.RefreshS3TokenRequest
	(*RefreshS3TokenResponse)(nil),        // 19: runtime.v1.RefreshS3TokenResponse
	(*GetProjectStatusRequest)(nil),       // 20: runtime.v1.GetProjectStatusRequest
	(*GetProjectStatusResponse)(nil),      // 21: runtime.v1.GetProjectStatusResponse
	(*GitPushRequest)(nil),                // 22: runtime.v1.GitPushRequest
	(*GitPushResponse)(nil),               // 23: runtime.v1.GitPushResponse
	(*SetupImportedTemplateRequest)(nil),  // 24: runtime.v1.SetupImportedTemplateRequest
	(*SetupImportedTemplateResponse)(nil), // 25: runtime.v1.SetupImportedTemplateResponse
	(*SaveCheckpointRequest)(nil),         // 26: runtime.v1.SaveCheckpointRequest
	(*SaveCheckpointResponse)(nil),        // 27: runtime.v1.SaveCheckpointResponse
}
var file_runtime_v1_webdev_proto_depIdxs = []int32{
	0,  // 0: runtime.v1.WebdevService.InitProject:input_type -> runtime.v1.InitProjectRequest
	2,  // 1: runtime.v1.WebdevService.UpdateConfig:input_type -> runtime.v1.UpdateConfigRequest
	4,  // 2: runtime.v1.WebdevService.GitSyncCheck:input_type -> runtime.v1.GitSyncCheckRequest
	6,  // 3: runtime.v1.WebdevService.RestartProject:input_type -> runtime.v1.RestartProjectRequest
	8,  // 4: runtime.v1.WebdevService.RestoreProject:input_type -> runtime.v1.RestoreProjectRequest
	10, // 5: runtime.v1.WebdevService.RollbackProject:input_type -> runtime.v1.RollbackProjectRequest
	12, // 6: runtime.v1.WebdevService.ApplyWebpageEdits:input_type -> runtime.v1.ApplyWebpageEditsRequest
	14, // 7: runtime.v1.WebdevService.DatabaseOperation:input_type -> runtime.v1.DatabaseOperationRequest
	16, // 8: runtime.v1.WebdevService.RefreshGitHubToken:input_type -> runtime.v1.RefreshGitHubTokenRequest
	18, // 9: runtime.v1.WebdevService.RefreshS3Token:input_type -> runtime.v1.RefreshS3TokenRequest
	20, // 10: runtime.v1.WebdevService.GetProjectStatus:input_type -> runtime.v1.GetProjectStatusRequest
	22, // 11: runtime.v1.WebdevService.GitPush:input_type -> runtime.v1.GitPushRequest
	24, // 12: runtime.v1.WebdevService.SetupImportedTemplate:input_type -> runtime.v1.SetupImportedTemplateRequest
	26, // 13: runtime.v1.WebdevService.SaveCheckpoint:input_type -> runtime.v1.SaveCheckpointRequest
	1,  // 14: runtime.v1.WebdevService.InitProject:output_type -> runtime.v1.InitProjectResponse
	3,  // 15: runtime.v1.WebdevService.UpdateConfig:output_type -> runtime.v1.UpdateConfigResponse
	5,  // 16: runtime.v1.WebdevService.GitSyncCheck:output_type -> runtime.v1.GitSyncCheckResponse
	7,  // 17: runtime.v1.WebdevService.RestartProject:output_type -> runtime.v1.RestartProjectResponse
	9,  // 18: runtime.v1.WebdevService.RestoreProject:output_type -> runtime.v1.RestoreProjectResponse
	11, // 19: runtime.v1.WebdevService.RollbackProject:output_type -> runtime.v1.RollbackProjectResponse
	13, // 20: runtime.v1.WebdevService.ApplyWebpageEdits:output_type -> runtime.v1.ApplyWebpageEditsResponse
	15, // 21: runtime.v1.WebdevService.DatabaseOperation:output_type -> runtime.v1.DatabaseOperationResponse
	17, // 22: runtime.v1.WebdevService.RefreshGitHubToken:output_type -> runtime.v1.RefreshGitHubTokenResponse
	19, // 23: runtime.v1.WebdevService.RefreshS3Token:output_type -> runtime.v1.RefreshS3TokenResponse
	21, // 24: runtime.v1.WebdevService.GetProjectStatus:output_type -> runtime.v1.GetProjectStatusResponse
	23, // 25: runtime.v1.WebdevService.GitPush:output_type -> runtime.v1.GitPushResponse
	25, // 26: runtime.v1.WebdevService.SetupImportedTemplate:output_type -> runtime.v1.SetupImportedTemplateResponse
	27, // 27: runtime.v1.WebdevService.SaveCheckpoint:output_type -> runtime.v1.SaveCheckpointResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_webdev_proto_init() }
func file_runtime_v1_webdev_proto_init() {
	if File_runtime_v1_webdev_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_webdev_proto_rawDesc), len(file_runtime_v1_webdev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_webdev_proto_goTypes,
		DependencyIndexes: file_runtime_v1_webdev_proto_depIdxs,
		MessageInfos:      file_runtime_v1_webdev_proto_msgTypes,
	}.Build()
	File_runtime_v1_webdev_proto = out.File
	file_runtime_v1_webdev_proto_goTypes = nil
	file_runtime_v1_webdev_proto_depIdxs = nil
}
